### ISSUE TITLE
新手求助：运行VnTrader文件夹下的run.py报错 UnicodeDecodeError

### ISSUE THREAD

**Issue by Leo70kg** [vnpy/vnpy#1033]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8.1（2018/08/11）

## Issue类型
三选一：Bug

## 重现步骤
C:\vnpy-1.8.1\vnpy-1.8.1\examples\VnTrader>python run.py
Traceback (most recent call last):
  File "run.py", line 24, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway,
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\trader\gateway\oandaGateway\__init__.py", line 4, in <module>
    from oandaGateway import OandaGateway
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\trader\gateway\oandaGateway\oandaGateway.py", line 27, in <module>
    from vnpy.api.oanda import OandaApi
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\api\oanda\__init__.py", line 4, in <module>
    from .vnoanda import OandaApi
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\api\oanda\vnoanda.py", line 5, in <module>
    import requests
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\cryptography\x509\extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "C:\Users\Administrator\Anaconda2\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "C:\Users\Administrator\Anaconda2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
  File "C:\Users\Administrator\Anaconda2\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcd in position 1: invalid continuation byte

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
OANDA接口已停止支持

**Comment by vnpy** [comment]
请从run.py中移除
