### ISSUE TITLE
queue包命名问题

### ISSUE THREAD

**Issue by asxzy** [vnpy/vnpy#1041]
## 环境

python2.7
vnpy 1.9.0

## Issue类型
Bug

```
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    from vnpy.event import EventEngine
  File "/usr/local/lib/python2.7/site-packages/vnpy/event/__init__.py", line 3, in <module>
    from .eventEngine import EventEngine, EventEngine2, Event, EVENT_TIMER
  File "/usr/local/lib/python2.7/site-packages/vnpy/event/eventEngine.py", line 5, in <module>
    from queue import Queue, Empty
ImportError: No module named queue
```
queue包在Python2.7下命名为首字母大写，在Python3下命名为首字母小写

建议
```
try:
    import Queue as queue
except ImportError:
    import queue
```

ref: https://bugs.python.org/issue1005

**Comment by kumapy** [comment]
应将vnpy安装目录下的examples目录，拷贝到vnpy的已安装路径下
比如我的已安装路径是C:\Anaconda2\Lib\site-packages\vnpy-1.9.0-py2.7.egg\vnpy\
然后再运行VnTrader.bat

**Comment by vnpy** [comment]
pip install future可以解决
