### ISSUE TITLE
单独使用example/Datarecording怎么会调用strategy相关模块

### ISSUE THREAD

**Issue by w1dexa2p34** [vnpy/vnpy#1084]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8
## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyDualThrust:
Traceback (most recent call last):
  File "/home/dr/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/home/dr/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/dr/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/strategyDualThrust.py", line 11, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import CtaTemplate, BarGenerator
  File "/home/dr/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/ctaTemplate.py", line 8, in <module>
    import talib
  File "/home/dr/anaconda2/lib/python2.7/site-packages/talib/__init__.py", line 4, in <module>
    from . import common
ImportError: cannot import name common

## 重现步骤
python runDataRecording.py

**Comment by vnpy** [comment]
因为现在DataRecorder里用到的BarGenerator是在CTA模块里的，不过现在看来该组件可以剥离放到底层里了，我来改下吧

**Comment by vnpy** [comment]
已修改
