### ISSUE TITLE
ImportError: twsapi.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 799964990** [vnpy/vnpy#1132]
## 环境

* 操作系统:  Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
 

## Issue类型
parallels@ubuntu:~/vnpy-1.9.0/examples/VnTrader$ python run.py
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    from vnpy.trader.gateway import (ctpGateway, ibGateway)
  File "/home/parallels/anaconda2/lib/python2.7/site-packages/vnpy-1.9.0-py2.7.egg/vnpy/trader/gateway/ibGateway/__init__.py", line 5, in <module>
    from .ibGateway import IbGateway
  File "/home/parallels/anaconda2/lib/python2.7/site-packages/vnpy-1.9.0-py2.7.egg/vnpy/trader/gateway/ibGateway/ibGateway.py", line 21, in <module>
    from vnpy.api.ib import *
  File "/home/parallels/anaconda2/lib/python2.7/site-packages/vnpy-1.9.0-py2.7.egg/vnpy/api/ib/__init__.py", line 4, in <module>
    from .vnib import *
ImportError: twsapi.so: cannot open shared object file: No such file or directory

**Comment by vnpy** [comment]
在LINUX下使用，需要重新编译vnpy.api.ib接口才行，在解压目录下运行build.sh应该就可以自动编译

**Comment by 799964990** [comment]
> 在LINUX下使用，需要重新编译vnpy.api.ib接口才行，在解压目录下运行build.sh应该就可以自动编译

运行了build.sh,还是报同样的错
