### ISSUE TITLE
OptionMaster 运行run.py 报错 No module named pyqtgraph

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#1133]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.9.0

## Issue类型
三选一：Bug

## 预期程序行为
按照教程安装，可以运行VnTrader，运行OptionMaster 报错

## 实际程序行为
runfile('C:/vnpy/examples/OptionMaster/run.py', wdir='C:/vnpy/examples/OptionMaster')
Traceback (most recent call last):

  File "<ipython-input-1-536cdb858298>", line 1, in <module>
    runfile('C:/vnpy/examples/OptionMaster/run.py', wdir='C:/vnpy/examples/OptionMaster')

  File "C:\ProgramData\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 93, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/vnpy/examples/OptionMaster/run.py", line 27, in <module>
    from vnpy.trader.app import (riskManager, optionMaster)

  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.0-py2.7.egg\vnpy\trader\app\optionMaster\__init__.py", line 4, in <module>
    from .uiOmWidget import OmManager

  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.0-py2.7.egg\vnpy\trader\app\optionMaster\uiOmWidget.py", line 16, in <module>
    from .uiOmVolatilityManager import VolatilityChart, VolatilityManager

  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.0-py2.7.egg\vnpy\trader\app\optionMaster\uiOmVolatilityManager.py", line 3, in <module>
    import pyqtgraph as pg

ImportError: No module named pyqtgraph

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\core\formatters.py", line 699, in __call__
    printer.pretty(obj)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 386, in pretty
    return self.type_pprinters[cls](obj, self, cycle)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 707, in _repr_pprint
    p.text(output_line)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 229, in text
    self.output.write(obj)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 122, in write
    cast_unicode(text, encoding=get_stream_enc(sys.stdout)))

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\utils\py3compat.py", line 27, in cast_unicode
    return decode(s, encoding)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\utils\py3compat.py", line 18, in decode
    return s.decode(encoding, "replace")

LookupError: unknown encoding: cp0

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\core\formatters.py", line 699, in __call__
    printer.pretty(obj)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 386, in pretty
    return self.type_pprinters[cls](obj, self, cycle)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 707, in _repr_pprint
    p.text(output_line)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 229, in text
    self.output.write(obj)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 122, in write
    cast_unicode(text, encoding=get_stream_enc(sys.stdout)))

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\utils\py3compat.py", line 27, in cast_unicode
    return decode(s, encoding)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\utils\py3compat.py", line 18, in decode
    return s.decode(encoding, "replace")

LookupError: unknown encoding: cp0

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\core\formatters.py", line 699, in __call__
    printer.pretty(obj)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 386, in pretty
    return self.type_pprinters[cls](obj, self, cycle)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 707, in _repr_pprint
    p.text(output_line)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 229, in text
    self.output.write(obj)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 122, in write
    cast_unicode(text, encoding=get_stream_enc(sys.stdout)))

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\utils\py3compat.py", line 27, in cast_unicode
    return decode(s, encoding)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\utils\py3compat.py", line 18, in decode
    return s.decode(encoding, "replace")

LookupError: unknown encoding: cp0

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

直接运行run.py即可

**Comment by yhmickey** [comment]
pip install pyqtgraph 后，问题解决， 建议修订requirments.txt
