### ISSUE TITLE
打开 vtMain.py 显示No module named ib.ext.Contract

### ISSUE THREAD

**Issue by RaymondXR** [vnpy/vnpy#120]
> C:\vnpy\vn.trader>python vtMain.py
Traceback (most recent call last):
  File "vtMain.py", line 6, in <module>
    from vtEngine import MainEngine
  File "C:\vnpy\vn.trader\vtEngine.py", line 13, in <module>
    from ibGateway import IbGateway
  File "C:\vnpy\vn.trader\ibGateway.py", line 20, in <module>
    from ib.ext.Contract import Contract
ImportError: No module named ib.ext.Contract

**Comment by vnpy** [comment]
没有安装IbPy接口。

使用最新的dev版本，同时如果你不用ib做交易，可以忽略ib相关的报错。

**Comment by RaymondXR** [comment]
明白了，感谢！
