### ISSUE TITLE
策略 error 

### ISSUE THREAD

**Issue by ecithy** [vnpy/vnpy#1234]
1

**Comment by ecithy** [comment]
Traceback (most recent call last):
  File "C:/Users/Quant/Desktop/tools/vnpy/examples/CtaBacktesting/mytest.py", line 42, in <module>
    engine.initStrategy(RsiSignal, d)
  File "C:\Users\Quant\Desktop\tools\vnpy\vnpy\trader\app\ctaStrategy\ctaBacktesting.py", line 320, in initStrategy
    self.strategy = strategyClass(self, setting)
TypeError: __init__() takes exactly 1 argument (3 given)
