### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_vnctpmd)

### ISSUE THREAD

**Issue by shuyuping** [vnpy/vnpy#1295]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: 如Anaconda 4.5.11, Python 3.5
* vn.py版本: 1.9
## Issue类型
Bug:
我在安装完VNPY后运行 example/VnTrader中的run.py

报错如下：

Traceback (most recent call last):
  File "run.py", line 28, in <module>
    from vnpy.trader.gateway import (ctpGateway, ibGateway)
  File "/home/yanmin/anaconda3/lib/python3.5/site-packages/vnpy-1.9.0-py3.5.egg/vnpy/trader/gateway/ctpGateway/__init__.py", line 5, in <module>
    from .ctpGateway import CtpGateway
  File "/home/yanmin/anaconda3/lib/python3.5/site-packages/vnpy-1.9.0-py3.5.egg/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "/home/yanmin/anaconda3/lib/python3.5/site-packages/vnpy-1.9.0-py3.5.egg/vnpy/api/ctp/__init__.py", line 4, in <module>
    from .vnctpmd import MdApi
ImportError: dynamic module does not define module export function (PyInit_vnctpmd)

有什么办法解决么？谢谢指点

**Comment by vnpy** [comment]
目前C++类的接口尚未支持python 3，将在1月底上线。
