### ISSUE TITLE
stopAlgo 中变量名称错误

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#1297]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5
* vn.py版本: 如v19.1

## Issue类型
三选一：Bug

## 预期程序行为
正常运行  

## 实际程序行为
Traceback (most recent call last):
  File "D:\PG\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\PG\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "E:\APP\VNPY\VNPYMASTER1125\vnpy\event\eventEngine.py", line 83, in __run
    self.__process(event)
  File "E:\APP\VNPY\VNPYMASTER1125\vnpy\event\eventEngine.py", line 93, in __process
    [handler(event) for handler in self.__handlers[event.type_]]
  File "E:\APP\VNPY\VNPYMASTER1125\vnpy\trader\app\algoTrading\algoEngine.py", line 75, in processTickEvent
    algo.updateTick(tick)
  File "E:\APP\VNPY\VNPYMASTER1125\vnpy\trader\app\algoTrading\algoTemplate.py", line 50, in updateTick
    self.onTick(tick)
  File "E:\APP\VNPY\VNPYMASTER1125\vnpy\trader\app\algoTrading\algo\stopAlgo.py", line 73, in onTick
    self.vtOrderID = func(self.vtSymbol, price, self.volume, offset=self.offset)
AttributeError: 'StopAlgo' object has no attribute 'volume'

## 重现步骤
可视化界面运行 stopAlgo 

针对Bug类型Issue，请提供具体重现步骤以及报错截图
N/A

**Comment by vnpy** [comment]
已修复，非常感谢。
