### ISSUE TITLE
CryptoTrader 运行报错

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#1323]
## 环境

* 操作系统: Windows 7
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.9.2

## Issue类型
三选一：Bug/Question

## 实际程序行为
未能正常启动

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
C:\vnpy\examples\CryptoTrader>python run.py
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    from vnpy.trader.gateway import (huobiGateway, okexGateway, okexfGateway,
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\tra
der\gateway\bigoneGateway\__init__.py", line 4, in <module>
    from .bigoneGateway import BigoneGateway
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\tra
der\gateway\bigoneGateway\bigoneGateway.py", line 16, in <module>
    from vnpy.api.bigone import BigoneRestApi
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\api
\bigone\__init__.py", line 1, in <module>
    from .vnbigone import BigoneRestApi
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\api
\bigone\vnbigone.py", line 20, in <module>
    from jwt import PyJWS
ImportError: No module named jwt

于是在anaconda prompt 下 pip install jwt
安装jwt后，运行报错：

C:\vnpy\examples\CryptoTrader>python run.py
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    from vnpy.trader.gateway import (huobiGateway, okexGateway, okexfGateway,
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\tra
der\gateway\bigoneGateway\__init__.py", line 4, in <module>
    from .bigoneGateway import BigoneGateway
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\tra
der\gateway\bigoneGateway\bigoneGateway.py", line 16, in <module>
    from vnpy.api.bigone import BigoneRestApi
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\api
\bigone\__init__.py", line 1, in <module>
    from .vnbigone import BigoneRestApi
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\api
\bigone\vnbigone.py", line 20, in <module>
    from jwt import PyJWS
  File "C:\ProgramData\Anaconda2\lib\site-packages\jwt\__init__.py", line 17, in
 <module>
    from .jwk import (
  File "C:\ProgramData\Anaconda2\lib\site-packages\jwt\jwk.py", line 60
    def is_sign_key(self) -> bool:
                          ^
SyntaxError: invalid syntax

**Comment by vnpy** [comment]
这是pyjws接口的问题，应该源于你装了Python 3的版本，所以Python 2报语法错误

**Comment by yhmickey** [comment]
已解决，建议requirements.txt增加PyJWT
