### ISSUE TITLE
ubuntu 18.4打不开vntrader

### ISSUE THREAD

**Issue by KilimanjaroFreeman** [vnpy/vnpy#1364]
## 环境

* 操作系统: Ubuntu 18.04。1
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: V1.9.2

## Issue类型
三选一：Question

## 预期程序行为
我重新安装的系统是ubuntu，然后安了最新的vnpy但是，无法打开vntrader
一运行就报错
我不知道是18.4系统的问题还是其他的问题
我已经 sudo apt-get install libsodium-dev
但是还是打不开VnTrader
希望能帮我指出问题谢谢
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    from vnpy.trader.gateway import xtpGateway
  File "/home/freeman/anaconda2/lib/python2.7/site-packages/vnpy-1.9.2-py2.7.egg/vnpy/trader/gateway/xtpGateway/__init__.py", line 5, in <module>
    from .xtpGateway import XtpGateway
  File "/home/freeman/anaconda2/lib/python2.7/site-packages/vnpy-1.9.2-py2.7.egg/vnpy/trader/gateway/xtpGateway/xtpGateway.py", line 11, in <module>
    from vnpy.api.xtp import *
  File "/home/freeman/anaconda2/lib/python2.7/site-packages/vnpy-1.9.2-py2.7.egg/vnpy/api/xtp/__init__.py", line 4, in <module>
    from .vnxtpquote import QuoteApi
ImportError: libsodium.so.18: cannot open shared object file: No such file or directory

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

![image](https://user-images.githubusercontent.com/32793518/51730990-77f11080-20b4-11e9-8f39-bd64400db292.png)

**Comment by KilimanjaroFreeman** [comment]
![image](https://user-images.githubusercontent.com/32793518/51733005-fcdf2880-20ba-11e9-9582-674303a9e539.png)
我xtp下bash build.sh 并且把xtpapi里的文件全部复制到api/xtp的文件下
但是错误还是存在

**Comment by KilimanjaroFreeman** [comment]
难道是libsodium.so.18复制的文件夹不对吗？我复制到了vnpy/api/xtp/下，但是还是报错

**Comment by vnpy** [comment]
请在run.py中移除xtpGateway的加载即可
