### ISSUE TITLE
ubuntu环境问题

### ISSUE THREAD

**Issue by jayce1212** [vnpy/vnpy#1369]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 20190128最新版
## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
File "/home/weng/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/home/weng/anaconda2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/weng/anaconda2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 17, in <module>
    from . import scimath as emath
ImportError: cannot import name scimath

以安装anaconda4.0包,显示缺少scimath包，尝试pip安装

pip install scimath
Collecting scimath
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fc/da/df00c7c0b55106b5ba67aa20b948238cb303af5fa930053e047d7e64a693/scimath-4.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vKOzPm/scimath/setup.py", line 9, in <module>
        import numpy.distutils.core
      File "/home/weng/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
        from . import add_newdocs
      File "/home/weng/anaconda2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
        from numpy.lib import add_newdoc
      File "/home/weng/anaconda2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
        from .polynomial import *
      File "/home/weng/anaconda2/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
        from numpy.linalg import eigvals, lstsq, inv
      File "/home/weng/anaconda2/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
        from .linalg import *
      File "/home/weng/anaconda2/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
        from numpy.linalg import lapack_lite, _umath_linalg
    ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vKOzPm/scimath/

**Comment by vnpy** [comment]
请尝试使用Anaconda 5.2.0

**Comment by LimingFang** [comment]
我环境是和你一样的，我vnpy安装好后，numpy是1.9的，你把她改成1.10.4试试，反正我ok了
