### ISSUE TITLE
DataRecorder对DCE交易所时间格式识别不正确

### ISSUE THREAD

**Issue by solorez** [vnpy/vnpy#1379]
## 环境

* 操作系统: 如Windows 7或者Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.7发行版或者dev branch 20170920（下载日期）

## Issue类型
三选一：Bug

## 重现步骤
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\VNConda\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\VNConda\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\VNConda\lib\site-packages\vnpy\event\eventEngine.py", line 83, in __run
    self.__process(event)
  File "C:\VNConda\lib\site-packages\vnpy\event\eventEngine.py", line 93, in __process
    [handler(event) for handler in self.__handlers[event.type_]]
  File "C:\VNConda\lib\site-packages\vnpy\trader\app\dataRecorder\drEngine.py", line 189, in procecssTickEvent
    tick.datetime = datetime.strptime(' '.join([tick.date, tick.time]), '%Y%m%d %H:%M:%S.%f')
  File "C:\VNConda\lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '20190214 99:99:99.9' does not match format '%Y%m%d %H:%M:%S.%f'
针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请使用无人值守脚本，定时自动启动关闭行情记录程序

**Comment by vnpy** [comment]
这个垃圾数据只有盘后测试阶段柜台才会发过来
