### ISSUE TITLE
ImportError: No module named strategyAtrRsi

### ISSUE THREAD

**Issue by justinchou** [vnpy/vnpy#1380]
## 环境

* 操作系统: MacOS Mojave 10.14.1 (18B75)
* Anaconda版本: 如Anaconda 4.6.3 Python 2.7.15 :: Anaconda, Inc.
* vn.py版本: v1.9.2 使用 master branch 20190213 进行源代码安装的

## Issue类型

Question

## 预期程序行为

预期使用 `import vnpy.trader.app.ctaStrategy.strategy as cta` 可以正常引入包

## 实际程序行为

报错：提示 `/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py` 文件无法引入相同目录下的其他策略文件，如下：

```txt
--------------------
Failed to import strategy file strategyAtrRsi:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyAtrRsi
--------------------
Failed to import strategy file strategyBollChannel:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyBollChannel
--------------------
Failed to import strategy file strategyDoubleMa:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyDoubleMa
--------------------
Failed to import strategy file strategyMultiTimeframe:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyMultiTimeframe
--------------------
Failed to import strategy file strategyMultiSignal:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyMultiSignal
--------------------
Failed to import strategy file strategyTurtleTrading:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyTurtleTrading
--------------------
Failed to import strategy file strategyKingKeltner:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyKingKeltner
--------------------
Failed to import strategy file strategyDualThrust:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyDualThrust
--------------------
Failed to import strategy file strategyAtrRsi:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyAtrRsi
--------------------
Failed to import strategy file strategyBollChannel:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyBollChannel
--------------------
Failed to import strategy file strategyDoubleMa:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyDoubleMa
--------------------
Failed to import strategy file strategyMultiTimeframe:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyMultiTimeframe
--------------------
Failed to import strategy file strategyMultiSignal:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyMultiSignal
--------------------
Failed to import strategy file strategyTurtleTrading:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyTurtleTrading
--------------------
Failed to import strategy file strategyKingKeltner:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyKingKeltner
--------------------
Failed to import strategy file strategyDualThrust:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyDualThrust
```

## 重现步骤

我在 anaconda python 2.7x 和本机自带的 python 都尝试了，问题相同。

让朋友在其 Windows 电脑下进行相同尝试没有问题。

看了 issues 里面其他的 `ImportError: No module named XXX` 问题貌似都与我的不太相同， 请大神指点~

**Comment by vnpy** [comment]
我估计应该和Mac的路径或者环境变量有关，我这边用Windows机器试了下也没问题，推荐尝试的解决方法：
1. 安装ta-lib
2. 换anaconda2 5.2.0 Py2.7
3. 换回到windows机器

**Comment by justinchou** [comment]
昨天尝试了替代方案：使用 miniconda 替代 anaconda.

安装 miniconda 之后，要使 miniconda 生效：

```bash
echo ". /Users/admin/miniconda2/etc/profile.d/conda.sh" >> ~/.bash_profile
# 增加 miniconda 的路径到 PATH 路径最前
source ~/.bash_profile
```

1. 创建虚拟环境：`conda create -n py27 python=2.7`
2. 切换环境：`conda activate py27`
3. 检查环境是否切换成功：

```bash
conda --version
python --version
pip --version
which conda
which python
which pip
```

4. 安装依赖：

```bash
brew install qt pyqt ta-lib
conda install matplotlib spyder pyqt QtPy future pymongo
pip install pandas numpy ta-lib bs4 tushare vnpy
```

**Comment by shiniantianlang** [comment]
试试在`vnpy\trader\app\ctaStrategy\strategy\__init__.py`文件中`import sys`，并在`path = os.path.abspath(os.path.dirname(__file__))`下面添加一行`sys.path.append(path)`
