### ISSUE TITLE
【2.0版本策略启动异常】

### ISSUE THREAD

**Issue by panrui0226** [vnpy/vnpy#1443]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0

## Issue类型
Question

## 预期程序行为
添加新策略，初始化并启动后，策略能够正常运行

## 实际程序行为
添加新策略，能够成功初始化；启动策略后，当接收到新的Tick后，报错如下：
1234: 触发异常已停止
Traceback (most recent call last):
  File "D:\ProgramData\VNConda\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 446, in call_strategy_func
    func(params)
  File "D:\ProgramData\VNConda\lib\site-packages\vnpy\app\cta_strategy\strategies\MyTest_strategy.py", line 42, in on_tick
    self.buy(tick.last_price + 1, self.fixed_size)
  File "D:\ProgramData\VNConda\lib\site-packages\vnpy\app\cta_strategy\template.py", line 142, in buy
    return self.send_order(CtaOrderType.BUY, price, volume, stop)
  File "D:\ProgramData\VNConda\lib\site-packages\vnpy\app\cta_strategy\template.py", line 174, in send_order
    self, order_type, price, volume, stop
  File "D:\ProgramData\VNConda\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 370, in send_order
    return self.send_limit_order(strategy, order_type, price, volume)
  File "D:\ProgramData\VNConda\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 278, in send_limit_order
    volume=volume,
TypeError: __init__() got an unexpected keyword argument 'dierction'

## 重现步骤
将附件后缀名改为 .py ，放到 VNConda\Lib\site-package\vnpy\app\cta_strategy\strategies 文件夹下，启动vnpy后添加策略，初始化并启动策略

[MyTest_strategy.txt](https://github.com/vnpy/vnpy/files/2929246/MyTest_strategy.txt)

**Comment by vnpy** [comment]
已修复
