### ISSUE TITLE
用tick数据回测报错

### ISSUE THREAD

**Issue by bailzx5522** [vnpy/vnpy#146]
2016-08-30 16:37:39.495689      开始载入数据
2016-08-30 16:37:40.252924      载入完成，数据量：32114
2016-08-30 16:37:40.253018      开始回测
Traceback (most recent call last):
  File "strategyAtrRsi.py", line 283, in <module>
    engine.runBacktesting()
  File "/opt/vnpy/vn.trader/ctaAlgo/ctaBacktesting.py", line 165, in runBacktesting
    self.strategy.onInit()
  File "/opt/vnpy/vn.trader/ctaAlgo/strategyAtrRsi.py", line 101, in onInit
    self.onBar(bar)
  File "/opt/vnpy/vn.trader/ctaAlgo/strategyAtrRsi.py", line 163, in onBar
    self.closeArray[-1] = bar.close
AttributeError: 'CtaBarData' object has no attribute 'close'

使用tick数据的时候ctaEngine的loadBar方法初始化的是CtaBarData
没有将tick源数据转换成bar类型。所以取bar.close的时候报错

**Comment by vnpy** [comment]
这个策略的代码写的时候使用的是bar回测的模式，享用tick回测的话需要自己做一些修改。

**Comment by msincenselee** [comment]
我已经修改好，具体请参考：
https://github.com/msincenselee/vnpy/
