### ISSUE TITLE
bitfinex api错错

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#1463]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: 如miniconda2 Python 2.7 64位
* vn.py版本: vnpy-1.9.2
## Issue类型
三选一：Bug

## 预期程序行为
报错如下，无法下单，且不能获取账户信息
未改过程序

## 实际程序行为

Traceback (most recent call last):
  File "/home/dev/miniconda2/envs/py27_quant/lib/python2.7/site-packages/vnpy-1.9.2-py2.7.egg/vnpy/api/bitfinex/vnbitfinex.py", line 64, in run
    self.onData(data)
  File "/home/dev/miniconda2/envs/py27_quant/lib/python2.7/site-packages/vnpy-1.9.2-py2.7.egg/vnpy/trader/gateway/bitfinexGateway/bitfinexGateway.py", line 305, in onData
    self.onUpdate(data)
  File "/home/dev/miniconda2/envs/py27_quant/lib/python2.7/site-packages/vnpy-1.9.2-py2.7.egg/vnpy/trader/gateway/bitfinexGateway/bitfinexGateway.py", line 327, in onUpdate
    self.onTradeUpdate(data)
  File "/home/dev/miniconda2/envs/py27_quant/lib/python2.7/site-packages/vnpy-1.9.2-py2.7.egg/vnpy/trader/gateway/bitfinexGateway/bitfinexGateway.py", line 446, in onTradeUpdate
    self.onWallet(l)
  File "/home/dev/miniconda2/envs/py27_quant/lib/python2.7/site-packages/vnpy-1.9.2-py2.7.egg/vnpy/trader/gateway/bitfinexGateway/bitfinexGateway.py", line 469, in onWallet
    account.available = float(data[-1])
TypeError: float() argument must be a string or a number

**Comment by yhmickey** [comment]
补充：可以获取实时行情

**Comment by vnpy** [comment]
看起来是Bitfinex接口升级了，我们的测试账户已经不能用了，能否尝试打印onWallet函数返回的数据并贴在这里？

**Comment by vnpy** [comment]
无更新，关闭issue，我们将在2.0中重新开发Bitfinex接口
