### ISSUE TITLE
ubuntu　 ctp导入问题

### ISSUE THREAD

**Issue by somewheve** [vnpy/vnpy#1477]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: Python 3.7 64位
* vn.py版本: DEV-2.0.1 branch 20190313（下载日期）

## Issue类型
三选一：Buｇ

## 预期程序行为
```
from vnpy.gateway.ctp import ctp_gateway导入成功
## 实际程序行为
'''from vnpy.gateway.ctp.ctp_gateway import CtpGateWay
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vnpy/vnpy/vnpy/gateway/ctp/__init__.py", line 1, in <module>
    from .ctp_gateway import CtpGateway
  File "/home/vnpy/vnpy/vnpy/gateway/ctp/ctp_gateway.py", line 6, in <module>
    from vnpy.api.ctp import (
  File "/home/vnpy/vnpy/vnpy/api/ctp/__init__.py", line 1, in <module>
    from .vnctpmd import MdApi
ModuleNotFoundError: No module named 'vnpy.api.ctp.vnctpmd'
```

## 重现步骤

```
删除setup下面的oes安装模块   
git clone -b v2.0.1-DEV https://github.com/vnpy/vnpy
cd vnpy
vim setup.py   #具体删除删除相关代码即可 
chmod +x install.sh  && ./install.sh   
# 安装会正常进行 
```

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
@nanoric 请帮忙看下

**Comment by somewheve** [comment]
@nanoric  还是老样子 无法得到修复 。 请新建一个用户 + anaconda3 环境测试

**Comment by nanoric** [comment]
请检查你载入的vnpy```import vnpy; vnpy```确定你载入的vnpy不是源码。你载入的vnpy应该编译安装后的vnpy，是也就是在site-packages里面的，而不是vnpy的源码。
你可以试一试换个目录运行你的vnpy。

**Comment by somewheve** [comment]
```
>>> from vnpy.gateway.ctp.ctp_gateway import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vnpy/anaconda3/lib/python3.7/site-packages/vnpy-2.0-py3.7-linux-x86_64.egg/vnpy/gateway/ctp/__init__.py", line 1, in <module>
    from .ctp_gateway import CtpGateway
  File "/home/vnpy/anaconda3/lib/python3.7/site-packages/vnpy-2.0-py3.7-linux-x86_64.egg/vnpy/gateway/ctp/ctp_gateway.py", line 6, in <module>
    from vnpy.api.ctp import (
  File "/home/vnpy/anaconda3/lib/python3.7/site-packages/vnpy-2.0-py3.7-linux-x86_64.egg/vnpy/api/ctp/__init__.py", line 1, in <module>
    from .vnctpmd import MdApi
ImportError: libthosttraderapi.so: cannot open shared object file: No such file or directory

```
> 不懂为啥还是找不到  尝试过这种可能性 ， 你能在一台全新的环境下的ubuntu安装吗  或者贴下你的操作过程 ？

**Comment by nanoric** [comment]
libthosttraderapi.so: cannot open shared object file: No such file or directory：
这个问题是vnpy的BUG。在新版本中会修复^_^

**Comment by somewheve** [comment]
好的 ～～～   希望能尽早推出 /  能不能把编译好的 libthosttraderapi.so 弄到一个特定的固定位置 。 每次安装 先从那个位置查找  ，或者外部调用默认也从这个地方   感觉放在build下面很奇怪

**Comment by nanoric** [comment]
谢谢你的提议^_^
新版本中就不需要手动设置路径了

**Comment by somewheve** [comment]
ojbk  等待这个bug修复  这样 就可以尝试升级到Python3了

**Comment by somewheve** [comment]
```
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vnpy.gateway.ctp import ctp_gateway
>>> 
>>> 
>>> 
# 成功  ，但是仍然在执行install.sh下面出现vnoes的编译错误 。 不过后来在setup.py里面删除掉vnoes安装的模块 ，再执行./install.sh 可以成功安装  感谢 

```

**Comment by somewheve** [comment]
```
 building 'vnpy.api.oes.vnoes' extension
  creating build/temp.linux-x86_64-3.7/vnpy/api/oes
  creating build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes
  creating build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes/generated_files
  gcc -pthread -B /home/vnpy/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DBRIGAND_NO_BOOST_SUPPORT=1 -Ivnpy/api/oes/include -Ivnpy/api/oes/vnoes -I/home/vnpy/anaconda3/include/python3.7m -c vnpy/api/oes/vnoes/generated_files/classes_1.cpp -o build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes/generated_files/classes_1.o -std=c++17 -Wno-delete-incomplete -Wno-sign-compare
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from vnpy/api/oes/include/autocxxpy/autocxxpy.hpp:8:0,
                   from vnpy/api/oes/vnoes/generated_files/classes_1.cpp:4:
  vnpy/api/oes/include/autocxxpy/callback_wrapper.hpp:76:106: warning: ‘selectany’ attribute directive ignored [-Wattributes]
       AUTOCXXPY_SELECT_ANY pybind11::detail::overload_caster_t<ret_type> pybind11_static_caster<ret_type>::caster;
                                                                                                            ^~~~~~
  gcc -pthread -B /home/vnpy/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DBRIGAND_NO_BOOST_SUPPORT=1 -Ivnpy/api/oes/include -Ivnpy/api/oes/vnoes -I/home/vnpy/anaconda3/include/python3.7m -c vnpy/api/oes/vnoes/generated_files/classes_2.cpp -o build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes/generated_files/classes_2.o -std=c++17 -Wno-delete-incomplete -Wno-sign-compare
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from vnpy/api/oes/include/autocxxpy/autocxxpy.hpp:8:0,
                   from vnpy/api/oes/vnoes/generated_files/classes_2.cpp:4:
  vnpy/api/oes/include/autocxxpy/callback_wrapper.hpp:76:106: warning: ‘selectany’ attribute directive ignored [-Wattributes]
       AUTOCXXPY_SELECT_ANY pybind11::detail::overload_caster_t<ret_type> pybind11_static_caster<ret_type>::caster;
                                                                                                            ^~~~~~
  gcc -pthread -B /home/vnpy/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DBRIGAND_NO_BOOST_SUPPORT=1 -Ivnpy/api/oes/include -Ivnpy/api/oes/vnoes -I/home/vnpy/anaconda3/include/python3.7m -c vnpy/api/oes/vnoes/generated_files/module.cpp -o build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes/generated_files/module.o -std=c++17 -Wno-delete-incomplete -Wno-sign-compare
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from vnpy/api/oes/include/autocxxpy/autocxxpy.hpp:8:0,
                   from vnpy/api/oes/vnoes/generated_files/module.cpp:4:
  vnpy/api/oes/include/autocxxpy/callback_wrapper.hpp:76:106: warning: ‘selectany’ attribute directive ignored [-Wattributes]
       AUTOCXXPY_SELECT_ANY pybind11::detail::overload_caster_t<ret_type> pybind11_static_caster<ret_type>::caster;
                                                                                                            ^~~~~~
  gcc -pthread -shared -B /home/vnpy/anaconda3/compiler_compat -L/home/vnpy/anaconda3/lib -Wl,-rpath=/home/vnpy/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes/generated_files/classes_1.o build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes/generated_files/classes_2.o build/temp.linux-x86_64-3.7/vnpy/api/oes/vnoes/generated_files/module.o -Lvnpy/api/oes/libs -loes_api -o build/lib.linux-x86_64-3.7/vnpy/api/oes/vnoes.cpython-37m-x86_64-linux-gnu.so -lstdc++
  /home/vnpy/anaconda3/compiler_compat/ld: vnpy/api/oes/libs/liboes_api.a: error adding symbols: file format not recognized
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for vnpy
  Running setup.py clean for vnpy
Failed to build vnpy
```
> 提个小意见   1，先检测ta-lib有没有安装 再执行下载编译安装?  2，输出信息太庞大了 ，可以适当删减 。 ^_^

**Comment by somewheve** [comment]
可能是内存不够 ， 不管了  issue closed  ^_^ Thanks for your  help.
