### ISSUE TITLE
OrderRequest类 单词direction拼写错误

### ISSUE THREAD

**Issue by raoshuaix1** [vnpy/vnpy#1482]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版

## Issue类型
三选一：Bug
## 实际程序行为
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files\Anaconda3\lib\site-packages\vnpy-2.0-py3.7.egg\vnpy\event\engine.py", line 60, in _run
    self._process(event)
  File "D:\Program Files\Anaconda3\lib\site-packages\vnpy-2.0-py3.7.egg\vnpy\event\engine.py", line 73, in _process
    [handler(event) for handler in self._handlers[event.type]]
  File "D:\Program Files\Anaconda3\lib\site-packages\vnpy-2.0-py3.7.egg\vnpy\event\engine.py", line 73, in <listcomp>
    [handler(event) for handler in self._handlers[event.type]]
  File "D:\Program Files\Anaconda3\lib\site-packages\vnpy-2.0-py3.7.egg\vnpy\app\cta_strategy\engine.py", line 165, in process_tick_event
    self.check_stop_order(tick)
  File "D:\Program Files\Anaconda3\lib\site-packages\vnpy-2.0-py3.7.egg\vnpy\app\cta_strategy\engine.py", line 233, in check_stop_order
    strategy, stop_order.order_type, price, stop_order.volume
  File "D:\Program Files\Anaconda3\lib\site-packages\vnpy-2.0-py3.7.egg\vnpy\app\cta_strategy\engine.py", line 278, in send_limit_order
    volume=volume,
TypeError: __init__() got an unexpected keyword argument 'dierction'

## 重现步骤
vnpy/app/cta_strategy/engine.py 274行
dierction=direction,    第一个单词写错

**Comment by vnpy** [comment]
dev分支已经修复了
