### ISSUE TITLE
for stop_order in self.stop_orders.values(): RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by raoshuaix1** [vnpy/vnpy#1486]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版

## Issue类型
三选一：Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files\Anaconda3\lib\site-packages\vnpy-2.0-py3.7.egg\vnpy\event\engine.py", line 60, in _run
    self._process(event)
  File "D:\Program Files\Anaconda3\lib\site-packages\vnpy-2.0-py3.7.egg\vnpy\event\engine.py", line 73, in _process
    [handler(event) for handler in self._handlers[event.type]]
  File "D:\Program Files\Anaconda3\lib\site-packages\vnpy-2.0-py3.7.egg\vnpy\event\engine.py", line 73, in <listcomp>
    [handler(event) for handler in self._handlers[event.type]]
  File "D:\Program Files\Anaconda3\lib\site-packages\vnpy-2.0-py3.7.egg\vnpy\app\cta_strategy\engine.py", line 165, in process_tick_event
    self.check_stop_order(tick)
  File "D:\Program Files\Anaconda3\lib\site-packages\vnpy-2.0-py3.7.egg\vnpy\app\cta_strategy\engine.py", line 204, in check_stop_order
    for stop_order in self.stop_orders.values():
RuntimeError: dictionary changed size during iteration

master vnpy\app\cta_strategy\engine.py 204行for循环     239行pop  
DEV中也是这样写 应该也会报错

**Comment by raoshuaix1** [comment]
同文件389行  for vt_orderid in vt_orderids:
                self.cancel_order(strategy, vt_orderid)
再遍历中删除元素也报同样的错误这是个set 上个是dict

**Comment by vnpy** [comment]
已修复
