### ISSUE TITLE
jupyter notebook import strategy异常错误

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#1512]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 如Anaconda2 5.2 Python 2.7 32位
* vn.py版本: 如v1.9

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

--------------------
Failed to import strategy file strategyAtrRsi:
--------------------
Failed to import strategy file strategyBollChannel:
--------------------
Failed to import strategy file strategyDoubleMa:
--------------------
Failed to import strategy file strategyDualThrust:
--------------------
Failed to import strategy file strategyKingKeltner:
--------------------
Failed to import strategy file strategyMultiSignal:
--------------------
Failed to import strategy file strategyMultiTimeframe:
--------------------
Failed to import strategy file strategyTurtleTrading:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\ProgramData\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyAtrRsi
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\ProgramData\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyBollChannel
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\ProgramData\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyDoubleMa
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\ProgramData\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyDualThrust
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\ProgramData\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyKingKeltner
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\ProgramData\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyMultiSignal
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\ProgramData\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyMultiTimeframe
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.9.2-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\ProgramData\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyTurtleTrading

**Comment by yhmickey** [comment]
![捕获](https://user-images.githubusercontent.com/34559558/54808450-3d25e600-4cbb-11e9-90f2-013d26e6c85b.PNG)

**Comment by yhmickey** [comment]
不知道为什么，将vnpy文件夹放在一个干净的磁盘下， 重新安装一遍就不报错了

**Comment by vnpy** [comment]
可能和环境变量的配置有关系了
