### ISSUE TITLE
HBDM Restful API网络断开异常没有处理

### ISSUE THREAD

**Issue by JasonXu-SH** [vnpy/vnpy#1731]
## 环境

* 操作系统: Windows 2008R2
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0.3  （2019/05/17）

## Issue类型
三选一：Bug

## 预期程序行为
当RestFul接口出现网络异常的时候，可以自动重连

## 实际程序行为
当网络异常的时候，系统出现未处理异常。

## 重现步骤

当连接HBDM足够长时间，就会出现这个议程未处理的情况。
![vpny_异常](https://user-images.githubusercontent.com/50890972/58136028-29691280-7c5f-11e9-87bc-4d28097f61d7.JPG)

后台的异常信息

[2019-05-22T00:03:06.380371]: Unhandled RestClient Error:<class 'requests.exceptions.ConnectionError'>
request:request : POST /api/v1/contract_account_info error because terminated: 
headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36', 'Content-Type': 'application/json'}
params: {'AccessKeyId': '1c50b0c7-#########-00276c0a-gr4edfki8l', 'SignatureMethod': 'HmacSHA256', 'SignatureVersion': '2', 'Timestamp': '2019-05-21T16:03:06', 'Signature': 'paaMk/cXjLG1/+$$$$$$$$$$$+VtCtc='}
data: None
response:

Exception trace: 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 299, in recv_into
    raise SocketError(str(e))
OSError: (10054, 'WSAECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 299, in recv_into
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\vnpy2\vnpy\api\rest\rest_client.py", line 257, in _process_request
    proxies=self.proxies,
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')"))

**Comment by vnpy** [comment]
1. requests层抛出的异常被正常捕捉住了
2. 你这里弹窗显示的是另一个由于openssl导致的底层断开错误，无法直接捕捉，同时这种错误最好也是直接抛出来

解决方案就是使用SS代理或者海外服务器
