### ISSUE TITLE
在Ubuntu环境下安装后不能启动

### ISSUE THREAD

**Issue by liujun1105** [vnpy/vnpy#1744]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: conda 4.6.11 Python 3.7 64位
* vn.py版本: 2.0.3

## Issue类型
Question

## 预期程序行为
正常启动

## 实际程序行为
找不到MdApi和TdApi
from .vnctpmd import MdApi
from .vnctptd import TdApi

tests/trader$ python run.py 
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    from vnpy.gateway.femas import FemasGateway
  File "/home/liujunju/TradingSpace/anaconda3/envs/vnpy/lib/python3.7/site-packages/vnpy/gateway/femas/__init__.py", line 1, in <module>
    from .femas_gateway import FemasGateway
  File "/home/liujunju/TradingSpace/anaconda3/envs/vnpy/lib/python3.7/site-packages/vnpy/gateway/femas/femas_gateway.py", line 7, in <module>
    from vnpy.api.femas import (
  File "/home/liujunju/TradingSpace/anaconda3/envs/vnpy/lib/python3.7/site-packages/vnpy/api/femas/__init__.py", line 1, in <module>
    from .vnfemasmd import MdApi
ModuleNotFoundError: No module named 'vnpy.api.femas.vnfemasmd'

## 重现步骤

tests/trader$ python run.py

**Comment by vnpy** [comment]
飞马接口不支持Ubuntu环境，请移除后再启动
