### ISSUE TITLE
No module named 'vnpy.api.ctp.vnctpmd' Installation Failed

### ISSUE THREAD

**Issue by ZeweiChu** [vnpy/vnpy#1747]
## 环境
Mac OS Mojave version 10.14.4
Anaconda版本 conda 4.6.11 
vn.py版本 2.0.3

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question
Bug

## 预期程序行为
python run.py 运行

## 实际程序行为
```
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from vnpy.gateway.ctp import CtpGateway
  File "/anaconda3/lib/python3.7/site-packages/vnpy/gateway/ctp/__init__.py", line 1, in <module>
    from .ctp_gateway import CtpGateway
  File "/anaconda3/lib/python3.7/site-packages/vnpy/gateway/ctp/ctp_gateway.py", line 6, in <module>
    from vnpy.api.ctp import (
  File "/anaconda3/lib/python3.7/site-packages/vnpy/api/ctp/__init__.py", line 1, in <module>
    from .vnctpmd import MdApi
ModuleNotFoundError: No module named 'vnpy.api.ctp.vnctpmd'
```

## 重现步骤
```
bash install_osx.sh
python run.py
```

针对Bug类型Issue，请提供具体重现步骤以及报错截图
```
bash install_osx.sh 
Requirement already up-to-date: pip in /anaconda3/lib/python3.7/site-packages (19.1.1)
Requirement already up-to-date: setuptools in /anaconda3/lib/python3.7/site-packages (41.0.1)
Requirement already up-to-date: wheel in /anaconda3/lib/python3.7/site-packages (0.33.4)
/tmp ~/work/merlintech/vnpy-2.0.3
--2019-05-26 19:43:51--  http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
Resolving prdownloads.sourceforge.net (prdownloads.sourceforge.net)... 216.105.38.13
Connecting to prdownloads.sourceforge.net (prdownloads.sourceforge.net)|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz [following]
--2019-05-26 19:43:51--  http://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Reusing existing connection to prdownloads.sourceforge.net:80.
HTTP request sent, awaiting response... 302 Found
Location: https://pilotfiber.dl.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz [following]
--2019-05-26 19:43:51--  https://pilotfiber.dl.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz
Resolving pilotfiber.dl.sourceforge.net (pilotfiber.dl.sourceforge.net)... 69.12.26.12
Connecting to pilotfiber.dl.sourceforge.net (pilotfiber.dl.sourceforge.net)|69.12.26.12|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1330299 (1.3M) [application/x-gzip]
Saving to: ‘ta-lib-0.4.0-src.tar.gz.4’

ta-lib-0.4.0-src.ta 100%[===================>]   1.27M  1.11MB/s    in 1.1s    

2019-05-26 19:43:53 (1.11 MB/s) - ‘ta-lib-0.4.0-src.tar.gz.4’ saved [1330299/1330299]

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... i386-apple-darwin18.5.0
checking host system type... i386-apple-darwin18.5.0
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognise dependent libraries... pass_all
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for g77... no
checking for xlf... no
checking for f77... no
checking for frt... no
checking for pgf77... no
checking for cf77... no
checking for fort77... no
checking for fl32... no
checking for af77... no
checking for xlf90... no
checking for f90... no
checking for pgf90... no
checking for pghpf... no
checking for epcf90... no
checking for gfortran... no
checking for g95... no
checking for xlf95... no
checking for f95... no
checking for fort... no
checking for ifort... no
checking for ifc... no
checking for efc... no
checking for pgf95... no
checking for lf95... no
checking for ftn... no
checking whether we are using the GNU Fortran 77 compiler... no
checking whether  accepts -g... no
checking the maximum length of command line arguments... 196608
checking command to parse /usr/bin/nm -B output from gcc object... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
checking if gcc supports -fno-rtti -fno-exceptions... rm: conftest.dSYM: is a directory
yes
checking for gcc option to produce PIC... -fno-common
checking if gcc PIC flag -fno-common works... rm: conftest.dSYM: is a directory
yes
checking if gcc static flag -static works... rm: conftest.dSYM: is a directory
no
checking if gcc supports -c -o file.o... rm: conftest.dSYM: is a directory
yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
configure: creating libtool
appending configuration tag "CXX" to libtool
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common
checking if g++ PIC flag -fno-common works... rm: conftest.dSYM: is a directory
yes
checking if g++ static flag -static works... rm: conftest.dSYM: is a directory
no
checking if g++ supports -c -o file.o... rm: conftest.dSYM: is a directory
yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.5.0 dyld
checking how to hardcode library paths into programs... immediate
appending configuration tag "F77" to libtool
checking for dlopen in -ldl... yes
checking for pthread_create in -lpthread... yes
checking for ANSI C header files... (cached) yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for working volatile... yes
checking for ptrdiff_t... yes
checking return type of signal handlers... void
checking for working strcoll... yes
checking for strftime... yes
checking for working strtod... yes
checking for vprintf... yes
checking for _doprnt... no
checking for floor... yes
checking for isascii... yes
checking for localeconv... yes
checking for mblen... yes
checking for memmove... yes
checking for memset... yes
checking for modf... yes
checking for pow... yes
checking for sqrt... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/ta_abstract/Makefile
config.status: creating src/ta_common/Makefile
config.status: creating src/ta_func/Makefile
config.status: creating src/tools/Makefile
config.status: creating src/tools/gen_code/Makefile
config.status: creating src/tools/ta_regtest/Makefile
config.status: creating ta-lib-config
config.status: creating ta-lib.spec
config.status: creating ta-lib.dpkg
config.status: creating include/ta_config.h
config.status: include/ta_config.h is unchanged
config.status: executing depfiles commands
Making all in src
Making all in ta_abstract
make[2]: Nothing to be done for `all'.
Making all in ta_common
make[2]: Nothing to be done for `all'.
Making all in ta_func
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all-am'.
Making all in src/tools
Making all in gen_code
/Library/Developer/CommandLineTools/usr/bin/make  gen_code
make[3]: `gen_code' is up to date.
cp gen_code ../../../bin
Making all in ta_regtest
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all-am'.
make[1]: Nothing to be done for `all-am'.
Password:
Making install in src
Making install in ta_abstract
make[3]: Nothing to be done for `install-exec-am'.
test -z "/user/local/include/ta-lib/" || ../.././install-sh -c -d "/user/local/include/ta-lib/"
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/user/local/include/ta-lib//ta_defs.h'
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/user/local/include/ta-lib//ta_libc.h'
 /usr/bin/install -c -m 644 '../../include/ta_abstract.h' '/user/local/include/ta-lib//ta_abstract.h'
Making install in ta_common
make[3]: Nothing to be done for `install-exec-am'.
test -z "/user/local/include/ta-lib/" || ../.././install-sh -c -d "/user/local/include/ta-lib/"
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/user/local/include/ta-lib//ta_defs.h'
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/user/local/include/ta-lib//ta_libc.h'
 /usr/bin/install -c -m 644 '../../include/ta_common.h' '/user/local/include/ta-lib//ta_common.h'
Making install in ta_func
make[3]: Nothing to be done for `install-exec-am'.
test -z "/user/local/include/ta-lib/" || ../.././install-sh -c -d "/user/local/include/ta-lib/"
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/user/local/include/ta-lib//ta_defs.h'
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/user/local/include/ta-lib//ta_libc.h'
 /usr/bin/install -c -m 644 '../../include/ta_func.h' '/user/local/include/ta-lib//ta_func.h'
test -z "/user/local/lib" || .././install-sh -c -d "/user/local/lib"
 /bin/sh ../libtool --mode=install /usr/bin/install -c  'libta_lib.la' '/user/local/lib/libta_lib.la'
/usr/bin/install -c .libs/libta_lib.0.0.0.dylib /user/local/lib/libta_lib.0.0.0.dylib
(cd /user/local/lib && { ln -s -f libta_lib.0.0.0.dylib libta_lib.0.dylib || { rm -f libta_lib.0.dylib && ln -s libta_lib.0.0.0.dylib libta_lib.0.dylib; }; })
(cd /user/local/lib && { ln -s -f libta_lib.0.0.0.dylib libta_lib.dylib || { rm -f libta_lib.dylib && ln -s libta_lib.0.0.0.dylib libta_lib.dylib; }; })
/usr/bin/install -c .libs/libta_lib.lai /user/local/lib/libta_lib.la
/usr/bin/install -c .libs/libta_lib.a /user/local/lib/libta_lib.a
chmod 644 /user/local/lib/libta_lib.a
ranlib /user/local/lib/libta_lib.a
libtool: install: warning: remember to run `libtool --finish /Users/zeweichu/software/lib'
make[3]: Nothing to be done for `install-data-am'.
Making install in src/tools
Making install in gen_code
/Library/Developer/CommandLineTools/usr/bin/make  gen_code
make[3]: `gen_code' is up to date.
cp gen_code ../../../bin
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in ta_regtest
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
test -z "/user/local/bin" || ./install-sh -c -d "/user/local/bin"
 /usr/bin/install -c 'ta-lib-config' '/user/local/bin/ta-lib-config'
make[2]: Nothing to be done for `install-data-am'.
~/work/merlintech/vnpy-2.0.3
Requirement already satisfied: numpy in /anaconda3/lib/python3.7/site-packages (1.16.2)
Looking in indexes: https://pypi.org/simple, https://rquser:****@py.ricequant.com/simple/
Requirement already satisfied: rqdatac in /anaconda3/lib/python3.7/site-packages (2.2.0)
Requirement already satisfied: six in /anaconda3/lib/python3.7/site-packages (from rqdatac) (1.12.0)
Requirement already satisfied: pandas; python_version > "3.4" or python_version == "2.7" in /anaconda3/lib/python3.7/site-packages (from rqdatac) (0.24.2)
Requirement already satisfied: brotli in /anaconda3/lib/python3.7/site-packages (from rqdatac) (1.0.7)
Requirement already satisfied: python-rapidjson; python_version > "3.3" in /anaconda3/lib/python3.7/site-packages (from rqdatac) (0.7.1)
Requirement already satisfied: requests in /anaconda3/lib/python3.7/site-packages (from rqdatac) (2.21.0)
Requirement already satisfied: msgpack>=0.5.2 in /anaconda3/lib/python3.7/site-packages (from rqdatac) (0.6.1)
Requirement already satisfied: PySocks in /anaconda3/lib/python3.7/site-packages (from rqdatac) (1.6.8)
Requirement already satisfied: pymysql in /anaconda3/lib/python3.7/site-packages (from rqdatac) (0.9.3)
Requirement already satisfied: SQLAlchemy in /anaconda3/lib/python3.7/site-packages (from rqdatac) (1.3.1)
Requirement already satisfied: python-dateutil in /anaconda3/lib/python3.7/site-packages (from rqdatac) (2.8.0)
Requirement already satisfied: numpy>=1.12.0 in /anaconda3/lib/python3.7/site-packages (from pandas; python_version > "3.4" or python_version == "2.7"->rqdatac) (1.16.2)
Requirement already satisfied: pytz>=2011k in /anaconda3/lib/python3.7/site-packages (from pandas; python_version > "3.4" or python_version == "2.7"->rqdatac) (2018.9)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /anaconda3/lib/python3.7/site-packages (from requests->rqdatac) (1.24.1)
Requirement already satisfied: idna<2.9,>=2.5 in /anaconda3/lib/python3.7/site-packages (from requests->rqdatac) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from requests->rqdatac) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.7/site-packages (from requests->rqdatac) (2019.3.9)
Requirement already satisfied: ta-lib in /anaconda3/lib/python3.7/site-packages (0.4.17)
Requirement already satisfied: numpy in /anaconda3/lib/python3.7/site-packages (from ta-lib) (1.16.2)
Requirement already satisfied: ibapi==9.75.1 from https://vnpy-pip.oss-cn-shanghai.aliyuncs.com/colletion/ibapi-9.75.1-py3-none-any.whl in /anaconda3/lib/python3.7/site-packages (9.75.1)
Ignoring dataclasses: markers 'python_version <= "3.6"' don't match your environment
Requirement already satisfied: PyQt5<5.12 in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (5.11.3)
Requirement already satisfied: pyqtgraph in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.10.0)
Requirement already satisfied: qdarkstyle in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (2.6.8)
Requirement already satisfied: requests in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.21.0)
Requirement already satisfied: websocket-client in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (0.56.0)
Requirement already satisfied: peewee in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (3.9.5)
Requirement already satisfied: pymysql in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (0.9.3)
Requirement already satisfied: psycopg2 in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (2.8.2)
Requirement already satisfied: mongoengine in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (0.17.0)
Requirement already satisfied: numpy in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (1.16.2)
Requirement already satisfied: pandas in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (0.24.2)
Requirement already satisfied: matplotlib in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (3.0.3)
Requirement already satisfied: seaborn in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (0.9.0)
Requirement already satisfied: futu-api in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (3.9.1)
Requirement already satisfied: tigeropen in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 16)) (1.1.2)
Requirement already satisfied: rqdatac in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 17)) (2.2.0)
Requirement already satisfied: ta-lib in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 18)) (0.4.17)
Requirement already satisfied: ibapi in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 19)) (9.75.1)
Requirement already satisfied: deap in /anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 20)) (1.2.2)
Requirement already satisfied: PyQt5_sip<4.20,>=4.19.11 in /anaconda3/lib/python3.7/site-packages (from PyQt5<5.12->-r requirements.txt (line 1)) (4.19.17)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /anaconda3/lib/python3.7/site-packages (from requests->-r requirements.txt (line 5)) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.7/site-packages (from requests->-r requirements.txt (line 5)) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in /anaconda3/lib/python3.7/site-packages (from requests->-r requirements.txt (line 5)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from requests->-r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: six in /anaconda3/lib/python3.7/site-packages (from websocket-client->-r requirements.txt (line 6)) (1.12.0)
Requirement already satisfied: pymongo>=2.7.1 in /anaconda3/lib/python3.7/site-packages (from mongoengine->-r requirements.txt (line 10)) (3.8.0)
Requirement already satisfied: python-dateutil>=2.5.0 in /anaconda3/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 12)) (2.8.0)
Requirement already satisfied: pytz>=2011k in /anaconda3/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 12)) (2018.9)
Requirement already satisfied: cycler>=0.10 in /anaconda3/lib/python3.7/site-packages (from matplotlib->-r requirements.txt (line 13)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /anaconda3/lib/python3.7/site-packages (from matplotlib->-r requirements.txt (line 13)) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /anaconda3/lib/python3.7/site-packages (from matplotlib->-r requirements.txt (line 13)) (2.3.1)
Requirement already satisfied: scipy>=0.14.0 in /anaconda3/lib/python3.7/site-packages (from seaborn->-r requirements.txt (line 14)) (1.2.1)
Requirement already satisfied: simplejson in /anaconda3/lib/python3.7/site-packages (from futu-api->-r requirements.txt (line 15)) (3.16.0)
Requirement already satisfied: protobuf in /anaconda3/lib/python3.7/site-packages (from futu-api->-r requirements.txt (line 15)) (3.7.1)
Requirement already satisfied: PyCryptodome in /anaconda3/lib/python3.7/site-packages (from futu-api->-r requirements.txt (line 15)) (3.8.1)
Requirement already satisfied: stomp.py in /anaconda3/lib/python3.7/site-packages (from tigeropen->-r requirements.txt (line 16)) (4.1.22)
Requirement already satisfied: pyasn1==0.4.4 in /anaconda3/lib/python3.7/site-packages (from tigeropen->-r requirements.txt (line 16)) (0.4.4)
Requirement already satisfied: rsa==4.0 in /anaconda3/lib/python3.7/site-packages (from tigeropen->-r requirements.txt (line 16)) (4.0)
Requirement already satisfied: delorean in /anaconda3/lib/python3.7/site-packages (from tigeropen->-r requirements.txt (line 16)) (1.0.0)
Requirement already satisfied: msgpack>=0.5.2 in /anaconda3/lib/python3.7/site-packages (from rqdatac->-r requirements.txt (line 17)) (0.6.1)
Requirement already satisfied: SQLAlchemy in /anaconda3/lib/python3.7/site-packages (from rqdatac->-r requirements.txt (line 17)) (1.3.1)
Requirement already satisfied: python-rapidjson; python_version > "3.3" in /anaconda3/lib/python3.7/site-packages (from rqdatac->-r requirements.txt (line 17)) (0.7.1)
Requirement already satisfied: brotli in /anaconda3/lib/python3.7/site-packages (from rqdatac->-r requirements.txt (line 17)) (1.0.7)
Requirement already satisfied: PySocks in /anaconda3/lib/python3.7/site-packages (from rqdatac->-r requirements.txt (line 17)) (1.6.8)
Requirement already satisfied: setuptools in /anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->-r requirements.txt (line 13)) (41.0.1)
Requirement already satisfied: docopt>=0.6.2 in /anaconda3/lib/python3.7/site-packages (from stomp.py->tigeropen->-r requirements.txt (line 16)) (0.6.2)
Requirement already satisfied: tzlocal>=1.2 in /anaconda3/lib/python3.7/site-packages (from delorean->tigeropen->-r requirements.txt (line 16)) (1.5.1)
Requirement already satisfied: babel>=2.1.1 in /anaconda3/lib/python3.7/site-packages (from delorean->tigeropen->-r requirements.txt (line 16)) (2.6.0)
Requirement already satisfied: humanize>=0.5.1 in /anaconda3/lib/python3.7/site-packages (from delorean->tigeropen->-r requirements.txt (line 16)) (0.5.1)
sudo: locale-gen: command not found
Processing /Users/zeweichu/work/merlintech/vnpy-2.0.3
Requirement already satisfied: PyQt5<5.12 in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (5.11.3)
Requirement already satisfied: qdarkstyle in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (2.6.8)
Requirement already satisfied: requests in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (2.21.0)
Requirement already satisfied: websocket-client in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (0.56.0)
Requirement already satisfied: peewee in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (3.9.5)
Requirement already satisfied: pymysql in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (0.9.3)
Requirement already satisfied: mongoengine in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (0.17.0)
Requirement already satisfied: numpy in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (1.16.2)
Requirement already satisfied: pandas in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (0.24.2)
Requirement already satisfied: matplotlib in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (3.0.3)
Requirement already satisfied: seaborn in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (0.9.0)
Requirement already satisfied: futu-api in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (3.9.1)
Requirement already satisfied: tigeropen in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (1.1.2)
Requirement already satisfied: rqdatac in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (2.2.0)
Requirement already satisfied: ta-lib in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (0.4.17)
Requirement already satisfied: ibapi in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (9.75.1)
Requirement already satisfied: deap in /anaconda3/lib/python3.7/site-packages (from vnpy==2.0.3) (1.2.2)
Requirement already satisfied: PyQt5_sip<4.20,>=4.19.11 in /anaconda3/lib/python3.7/site-packages (from PyQt5<5.12->vnpy==2.0.3) (4.19.17)
Requirement already satisfied: idna<2.9,>=2.5 in /anaconda3/lib/python3.7/site-packages (from requests->vnpy==2.0.3) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /anaconda3/lib/python3.7/site-packages (from requests->vnpy==2.0.3) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.7/site-packages (from requests->vnpy==2.0.3) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.7/site-packages (from requests->vnpy==2.0.3) (2019.3.9)
Requirement already satisfied: six in /anaconda3/lib/python3.7/site-packages (from websocket-client->vnpy==2.0.3) (1.12.0)
Requirement already satisfied: pymongo>=2.7.1 in /anaconda3/lib/python3.7/site-packages (from mongoengine->vnpy==2.0.3) (3.8.0)
Requirement already satisfied: pytz>=2011k in /anaconda3/lib/python3.7/site-packages (from pandas->vnpy==2.0.3) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in /anaconda3/lib/python3.7/site-packages (from pandas->vnpy==2.0.3) (2.8.0)
Requirement already satisfied: cycler>=0.10 in /anaconda3/lib/python3.7/site-packages (from matplotlib->vnpy==2.0.3) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /anaconda3/lib/python3.7/site-packages (from matplotlib->vnpy==2.0.3) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /anaconda3/lib/python3.7/site-packages (from matplotlib->vnpy==2.0.3) (2.3.1)
Requirement already satisfied: scipy>=0.14.0 in /anaconda3/lib/python3.7/site-packages (from seaborn->vnpy==2.0.3) (1.2.1)
Requirement already satisfied: simplejson in /anaconda3/lib/python3.7/site-packages (from futu-api->vnpy==2.0.3) (3.16.0)
Requirement already satisfied: protobuf in /anaconda3/lib/python3.7/site-packages (from futu-api->vnpy==2.0.3) (3.7.1)
Requirement already satisfied: PyCryptodome in /anaconda3/lib/python3.7/site-packages (from futu-api->vnpy==2.0.3) (3.8.1)
Requirement already satisfied: pyasn1==0.4.4 in /anaconda3/lib/python3.7/site-packages (from tigeropen->vnpy==2.0.3) (0.4.4)
Requirement already satisfied: stomp.py in /anaconda3/lib/python3.7/site-packages (from tigeropen->vnpy==2.0.3) (4.1.22)
Requirement already satisfied: rsa==4.0 in /anaconda3/lib/python3.7/site-packages (from tigeropen->vnpy==2.0.3) (4.0)
Requirement already satisfied: delorean in /anaconda3/lib/python3.7/site-packages (from tigeropen->vnpy==2.0.3) (1.0.0)
Requirement already satisfied: python-rapidjson; python_version > "3.3" in /anaconda3/lib/python3.7/site-packages (from rqdatac->vnpy==2.0.3) (0.7.1)
Requirement already satisfied: PySocks in /anaconda3/lib/python3.7/site-packages (from rqdatac->vnpy==2.0.3) (1.6.8)
Requirement already satisfied: SQLAlchemy in /anaconda3/lib/python3.7/site-packages (from rqdatac->vnpy==2.0.3) (1.3.1)
Requirement already satisfied: msgpack>=0.5.2 in /anaconda3/lib/python3.7/site-packages (from rqdatac->vnpy==2.0.3) (0.6.1)
Requirement already satisfied: brotli in /anaconda3/lib/python3.7/site-packages (from rqdatac->vnpy==2.0.3) (1.0.7)
Requirement already satisfied: setuptools in /anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->vnpy==2.0.3) (41.0.1)
Requirement already satisfied: docopt>=0.6.2 in /anaconda3/lib/python3.7/site-packages (from stomp.py->tigeropen->vnpy==2.0.3) (0.6.2)
Requirement already satisfied: humanize>=0.5.1 in /anaconda3/lib/python3.7/site-packages (from delorean->tigeropen->vnpy==2.0.3) (0.5.1)
Requirement already satisfied: babel>=2.1.1 in /anaconda3/lib/python3.7/site-packages (from delorean->tigeropen->vnpy==2.0.3) (2.6.0)
Requirement already satisfied: tzlocal>=1.2 in /anaconda3/lib/python3.7/site-packages (from delorean->tigeropen->vnpy==2.0.3) (1.5.1)
Building wheels for collected packages: vnpy
  Building wheel for vnpy (setup.py) ... done
  Stored in directory: /Users/zeweichu/Library/Caches/pip/wheels/67/8f/b9/1cf75460cfb73518ce01a4f58003224f6d47b8e93f8fc18eec
Successfully built vnpy
Installing collected packages: vnpy
Successfully installed vnpy-2.0.3
```

```
python run.py 
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from vnpy.gateway.ctp import CtpGateway
  File "/anaconda3/lib/python3.7/site-packages/vnpy/gateway/ctp/__init__.py", line 1, in <module>
    from .ctp_gateway import CtpGateway
  File "/anaconda3/lib/python3.7/site-packages/vnpy/gateway/ctp/ctp_gateway.py", line 6, in <module>
    from vnpy.api.ctp import (
  File "/anaconda3/lib/python3.7/site-packages/vnpy/api/ctp/__init__.py", line 1, in <module>
    from .vnctpmd import MdApi
ModuleNotFoundError: No module named 'vnpy.api.ctp.vnctpmd'
```

**Comment by vnpy** [comment]
CTP API不支持苹果，请勿加载

**Comment by ZeweiChu** [comment]
请问这样是否表示无法用mac连接simnow进行测试呢？

**Comment by vnpy** [comment]
没错，测不了的

**Comment by jonwinters** [comment]
ubuntu也不能用

**Comment by Yihen** [comment]
这个问题解决了吗？我也遇到了

**Comment by hengkx** [comment]
解决了吗 2.0.8 同样的问题

**Comment by liuyxpp** [comment]
VNPY好多功能Mac都用不了。2.1.7包里的安装脚本也有很多错误。

**Comment by kaiqiangh** [comment]
ubuntu 20.04 也不行

**Comment by CYorick** [comment]
> CTP API不支持苹果，请勿加载

请问mac上能够用什么gateway交易期货？

**Comment by vnpy** [comment]
> > CTP API不支持苹果，请勿加载
> 
> 请问mac上能够用什么gateway交易期货？

目前没有支持的，我们明年会增加Mac的CTP支持

**Comment by CYorick** [comment]
请问mac是否支持vnpy_binance？
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/117757861/210198003-96ab5218-580c-4c6a-95e1-9eebbd20df3c.png">
