### ISSUE TITLE
Bug：rqdata.py 中 RqdataClient 类的 query_history 方法如果查询无数据则会抛出异常

### ISSUE THREAD

**Issue by nov12** [vnpy/vnpy#1754]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: Anaconda Python 3.7 64位
* vn.py版本: v2.0.3

## Issue类型
三选一：Bug

## 预期程序行为
如果下载不到数据返回空列表

## 实际程序行为
会引发异常：
\vnpy\trader\rqdata.py in query_history(self, req)
    123 
    124         data: List[BarData] = []
--> 125         for ix, row in df.iterrows():
    126             bar = BarData(
    127                 symbol=symbol,

AttributeError: 'NoneType' object has no attribute 'iterrows'

## 重现步骤

例如下载AP88，2005年的数据或者其他合约十一假期的数据

**Comment by eachout** [comment]
bitmex和hbdm gateway也有这个问题。下载历史数据总是下不完，建议加上异常捕捉。

**Comment by eachout** [comment]
```
Traceback (most recent call last):
  File "E:\Quant\my-vnpy\venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "E:\Quant\my-vnpy\venv\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "E:\Quant\my-vnpy\venv\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bitmex.com', port=443): Max retries exceeded with url: /api/v1/trade/bucketed?binSize=1m&symbol=XBTUSD&count=750&startTime=2018-11-19+00%3A00%3A00&endTime=2019-06-02 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Quant\my-vnpy\vnpy\app\cta_backtester\engine.py", line 355, in run_downloading
    data = self.main_engine.query_history(req, contract.gateway_name)
  File "E:\Quant\my-vnpy\vnpy\trader\engine.py", line 205, in query_history
    return gateway.query_history(req)
  File "E:\Quant\my-vnpy\vnpy\gateway\bitmex\bitmex_gateway.py", line 144, in query_history
    return self.rest_api.query_history(req)
  File "E:\Quant\my-vnpy\vnpy\gateway\bitmex\bitmex_gateway.py", line 324, in query_history
    params=params
  File "E:\Quant\my-vnpy\vnpy\api\rest\rest_client.py", line 322, in request
    proxies=self.proxies,
  File "E:\Quant\my-vnpy\venv\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Quant\my-vnpy\venv\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Quant\my-vnpy\venv\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "E:\Quant\my-vnpy\venv\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.bitmex.com', port=443): Max retries exceeded with url: /api/v1/trade/bucketed?binSize=1m&symbol=XBTUSD&count=750&startTime=2018-11-19+00%3A00%3A00&endTime=2019-06-02 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

```

**Comment by vnpy** [comment]
已修复，目前来看BitMEX和HBDM的异常最好是抛出让上层知道，而不是简单的返回空数据结果，因此暂时不做修改
