### ISSUE TITLE
websocket Exception: socket is already closed

### ISSUE THREAD

**Issue by toints** [vnpy/vnpy#184]
在 https://github.com/vnpy/vnpy/issues/130 中，OKcoin需要安装websocket-client，我本地通过pip install websocket-client来安装的,但是在运行vn.okcoin/test.py的时候，出现如下的错误：

Traceback (most recent call last):
  File "test.py", line 22, in <module>
    api.subscribeSpotTicker(SYMBOL_BTC)
  File "/home/vnpy-master/vn.okcoin/vnokcoin.py", line 210, in subscribeSpotTicker
    self.sendMarketDataRequest('ok_sub_spot%s_%s_ticker' %(self.currency, symbol))
  File "/home/vnpy-master/vn.okcoin/vnokcoin.py", line 183, in sendMarketDataRequest
    self.ws.send(j)
  File "/opt/anaconda/lib/python2.7/site-packages/websocket_client-0.39.0-py2.7.egg/websocket/_app.py", line 117, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/anaconda/lib/python2.7/site-packages/websocket_client-0.39.0-py2.7.egg/websocket/_core.py", line 234, in send
    return self.send_frame(frame)
  File "/opt/anaconda/lib/python2.7/site-packages/websocket_client-0.39.0-py2.7.egg/websocket/_core.py", line 259, in send_frame
    l = self._send(data)
  File "/opt/anaconda/lib/python2.7/site-packages/websocket_client-0.39.0-py2.7.egg/websocket/_core.py", line 423, in _send
    return send(self.sock, data)
  File "/opt/anaconda/lib/python2.7/site-packages/websocket_client-0.39.0-py2.7.egg/websocket/_socket.py", line 113, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

而且，我从github：https://github.com/liris/websocket-client 上下载的websocket-client，然后手动安装，运行还是出现一样的错误。请问如何解决？

**Comment by vnpy** [comment]
你得修改下test.py里面的apiKey和secretKey为你的账号对应的信息。

**Comment by toints** [comment]
@vnpy 这个我修改过了，我在OKcoin的网站上申请的 APIkey 和secretKey，我试过了，我自己写的HTTPS的接口是没问题的，但是这个websocket接口就不行。

**Comment by vnpy** [comment]
能看看

**Comment by toints** [comment]
@vnpy  我之前是pip安装的，现在用的是https://github.com/liris/websocket-client 这个版本。我测试了他的例子：https://github.com/liris/websocket-client#long-lived-connection  ， 也不能通过，出现：[Errno -2] Name or service not known的错误 。应该是websocket-client库的原因。

**Comment by vnpy** [comment]
我这里可以，检查下是否和你的电脑网络设置有关，还有防火墙之类的因素

**Comment by toints** [comment]
@vnpy  谢谢你了！ 这些基本的配置我都知道，我调试过了，是多线程的原因，Python 中thread和theading库是有差别的，我把vn.okcoin改成使用thead库就好使了。
