### ISSUE TITLE
测试grid交易报错

### ISSUE THREAD

**Issue by HorsenLi** [vnpy/vnpy#1841]
## 环境

* 操作系统: macos
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0.4 dev branch
* gateway: Binance

## Issue类型
Bug

## 预期程序行为
grid交易

## 实际程序行为
报错：
Traceback (most recent call last):
  File "/Users/horsen/anaconda3/envs/vnpy-conda/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/horsen/anaconda3/envs/vnpy-conda/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/horsen/anaconda3/envs/vnpy-conda/lib/python3.7/site-packages/vnpy/event/engine.py", line 60, in _run
    self._process(event)
  File "/Users/horsen/anaconda3/envs/vnpy-conda/lib/python3.7/site-packages/vnpy/event/engine.py", line 73, in _process
    [handler(event) for handler in self._handlers[event.type]]
  File "/Users/horsen/anaconda3/envs/vnpy-conda/lib/python3.7/site-packages/vnpy/event/engine.py", line 73, in <listcomp>
    [handler(event) for handler in self._handlers[event.type]]
  File "/Users/horsen/anaconda3/envs/vnpy-conda/lib/python3.7/site-packages/vnpy/app/algo_trading/engine.py", line 100, in process_timer_event
    algo.update_timer()
  File "/Users/horsen/anaconda3/envs/vnpy-conda/lib/python3.7/site-packages/vnpy/app/algo_trading/template.py", line 61, in update_timer
    self.on_timer()
  File "/Users/horsen/anaconda3/envs/vnpy-conda/lib/python3.7/site-packages/vnpy/app/algo_trading/algos/grid_algo.py", line 106, in on_timer
    min(target_sell_volume, self.last_tick.bid_volume_1)
  File "/Users/horsen/anaconda3/envs/vnpy-conda/lib/python3.7/site-packages/vnpy/app/algo_trading/template.py", line 152, in sell
    offset
  File "/Users/horsen/anaconda3/envs/vnpy-conda/lib/python3.7/site-packages/vnpy/app/algo_trading/engine.py", line 175, in send_order
    volume = round_to(volume, contract.min_volume)
  File "/Users/horsen/anaconda3/envs/vnpy-conda/lib/python3.7/site-packages/vnpy/trader/utility.py", line 113, in round_to
    rounded = int(round(value / target)) * target
TypeError: unsupported operand type(s) for /: 'float' and 'str'

## 重现步骤
执行grid交易
代码：xxxx
价格：0.0055
网格交易间距：0.0005
交易数量：100
交易间隔：10

**Comment by HorsenLi** [comment]
sniper算法也有同样的问题

**Comment by HorsenLi** [comment]
改写round_to函数，可以解决问题：

def round_to(value: float, target: float):
    """
    Round price to price tick value.
    """
    tmp = float(target)
    rounded = int(round(value / tmp)) * tmp
    return rounded
