### ISSUE TITLE
turtle strategy - TypeError: ufunc 'true_divide' not supported for the input types

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#1902]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
```

turtle_test1: Trigger exception has stopped
Traceback (most recent call last):
  File "E:\WARTER\python\python.v3_portable\App\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 564, in call_strategy_func
    func(params)
  File "E:\WARTER\python\python.v3_portable\App\lib\site-packages\vnpy\app\cta_strategy\strategies\turtle_signal_strategy.py", line 69, in on_tick
    self.bg.update_tick(tick)
  File "E:\WARTER\python\python.v3_portable\App\lib\site-packages\vnpy\trader\utility.py", line 165, in update_tick
    self.on_bar(self.bar)
  File "E:\WARTER\python\python.v3_portable\App\lib\site-packages\vnpy\app\cta_strategy\strategies\turtle_signal_strategy.py", line 92, in on_bar
    self.send_buy_orders(self.entry_up)
  File "E:\WARTER\python\python.v3_portable\App\lib\site-packages\vnpy\app\cta_strategy\strategies\turtle_signal_strategy.py", line 136, in send_buy_orders
    self.buy(price, self.fixed_size, True)
  File "E:\WARTER\python\python.v3_portable\App\lib\site-packages\vnpy\app\cta_strategy\template.py", line 155, in buy
    return self.send_order(Direction.LONG, Offset.OPEN, price, volume, stop, lock)
  File "E:\WARTER\python\python.v3_portable\App\lib\site-packages\vnpy\app\cta_strategy\template.py", line 189, in send_order
    self, direction, offset, price, volume, stop, lock
  File "E:\WARTER\python\python.v3_portable\App\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 475, in send_order
    price = round_to(price, contract.pricetick)
  File "E:\WARTER\python\python.v3_portable\App\lib\site-packages\vnpy\trader\utility.py", line 113, in round_to
    rounded = int(round(value / target)) * target
TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
![ccccccccccccccccccccccccccccccc](https://user-images.githubusercontent.com/9572613/60669441-854acc00-9e98-11e9-8c86-85a39a6da7e1.PNG)

**Comment by vnpy** [comment]
请问是否有自行修改TurtleStrategy？

**Comment by cbogithub** [comment]
> 
> 
> 请问是否有自行修改TurtleStrategy？


我没有修改过TurtleStrategy。 我克隆了最新的vnpy到其他文件夹并再次运行，仍然得到这个erorr

**Comment by vnpy** [comment]
我们试着来还原下吧，整体上这个报错是target和value中有一个数据是numpy结构导致的，应该都是float

**Comment by cbogithub** [comment]
我再次测试看到'price'是numpy float64和
 'contract.pricetick'是int

**Comment by vnpy** [comment]
请试着打印下price和contract.pricetick的数值？

**Comment by cbogithub** [comment]
price value : 0.000775 ,type:  <class 'numpy.float64'>
contract.pricetick value:  0.00000100 ,type:  <class 'str'>

**Comment by vnpy** [comment]
知道了，就是这个类型为str的pricetick问题，币安接口问题，我们来修复下

**Comment by vnpy** [comment]
我们检查了下代码，这个pricetick问题在之前版本中已经修改为float类型了：

`    
def on_query_contract(self, data, request):
        """"""
        for d in data["symbols"]:
            base_currency = d["baseAsset"]
            quote_currency = d["quoteAsset"]
            name = f"{base_currency.upper()}/{quote_currency.upper()}"

            pricetick = 1
            min_volume = 1

            for f in d["filters"]:
                if f["filterType"] == "PRICE_FILTER":
                    pricetick = float(f["tickSize"])
                elif f["filterType"] == "LOT_SIZE":
                    min_volume = float(f["stepSize"])

            contract = ContractData(
                symbol=d["symbol"],
                exchange=Exchange.BINANCE,
                name=name,
                pricetick=pricetick,
                size=1,
                min_volume=min_volume,
                product=Product.SPOT,
                gateway_name=self.gateway_name,
            )
            self.gateway.on_contract(contract)

            symbol_name_map[contract.symbol] = contract.name

        self.gateway.write_log("合约信息查询成功")
`

请升级到最新的2.0.5发行版再试试吧
