### ISSUE TITLE
TypeError: Object of type int64 is not JSON serializable

### ISSUE THREAD

**Issue by chdl21cn** [vnpy/vnpy#1909]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本: 无
* vn.py版本: v2.0.4程序更新升级到v2.0.5

## Issue类型
三选一：Bug

## 预期程序行为
订单成交，正常触发process_trade_event(self, event: Event)订单处理

## 实际程序行为
触发process_trade_event(self, event: Event)时，由于新版程序新增调用了sync_strategy_data(strategy)，在保存json文件时，出现数据类型错误。

## 重现步骤
当需要保存到json文件中的数据包含numpy.int64类型的数据时（网上看还有其他numpy数据类型如浮点、数组等也一样，用pandas包处理数据时，经常会返回numpy类型数据），由于JSON模块不兼容相关类型，导致程序出错。
错误提示为：
Traceback (most recent call last):
File "D:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\ui\widget.py", line
246, in stop_strategy
self.cta_engine.stop_strategy(self.strategy_name)
File "D:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 688
, in stop_strategy
self.sync_strategy_data(strategy)
File "D:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 785
, in sync_strategy_data
save_json(self.data_filename, self.strategy_data)
File "D:\vnstudio\lib\site-packages\vnpy\trader\utility.py", line 105, in save
_json
ensure_ascii=False
File "D:\vnstudio\lib\json__init.py", line 179, in dump
for chunk in iterable:
File "D:\vnstudio\lib\json\encoder.py", line 431, in _iterencode
yield from _iterencode_dict(o, _current_indent_level)
File "D:\vnstudio\lib\json\encoder.py", line 405, in _iterencode_dict
yield from chunks
File "D:\vnstudio\lib\json\encoder.py", line 405, in _iterencode_dict
yield from chunks
File "D:\vnstudio\lib\json\encoder.py", line 438, in _iterencode
o = _default(o)
File "D:\vnstudio\lib\json\encoder.py", line 179, in default
raise TypeError(f'Object of type {o.class.name__} '
TypeError: Object of type int64 is not JSON serializable

**Comment by xldistance** [comment]
#--------------------------------------------------------------------------------------------------
    def get_variables(self):
        """
        Get strategy variables dict.
        """
        strategy_variables = {}
        for name in self.variables:
            if(type(getattr(self, name))) in [np.int32]:
                #json写入不支持np.int32需要转化
                strategy_variables[name] = int(getattr(self, name))
            else:
                strategy_variables[name] = getattr(self, name)

        return strategy_variables

**Comment by vnpy** [comment]
在策略中的某个数据的类型，可能是任何一种，更多应该由用户自行控制进行转换（在策略代码内部），因此不进行相关处理。
