### ISSUE TITLE
v2.0.4行情数据记录出现转换异常

### ISSUE THREAD

**Issue by jacklpng** [vnpy/vnpy#1916]
## 环境

* 操作系统: 如Windows 7
* Anaconda版本:  Python 3.7 64位
* vn.py版本: v2.0.4
*数据存储: MYSQL

## Issue类型
三选一：Bug

## 预期程序行为
数据能够正常记录记录到数据库

## 实际程序行为
程序一旦出现异常，下次启动则直接异常

## 重现步骤
1、数据记录中不定时出现异常，一旦出现异常，重启程序则依然会异常
2、去掉异常合约的行情订阅，则程序可正常启动

针对Bug类型Issue，请提供具体重现步骤以及报错截图
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2949, in execute_sql
    cursor.execute(sql, params or ())
  File "C:\Anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1367, "Illegal double '1.79769313486232e+308' value found during parsing")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\workspace\vnpy-2.0.4\vnpy\app\data_recorder\engine.py", line 76, in run
    database_manager.save_tick_data([data])
  File "C:\workspace\vnpy-2.0.4\vnpy\trader\database\database_sql.py", line 560, in save_tick_data
    self.class_tick.save_all(ds)
  File "C:\workspace\vnpy-2.0.4\vnpy\trader\database\database_sql.py", line 321, in save_all
    DbTickData.insert_many(c).on_conflict_replace().execute()
  File "C:\Anaconda3\lib\site-packages\peewee.py", line 1785, in inner
    return method(self, database, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\peewee.py", line 1856, in execute
    return self._execute(database)
  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2572, in _execute
    return super(Insert, self)._execute(database)
  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2320, in _execute
    cursor = database.execute(self)
  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2962, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2956, in execute_sql
    self.commit()
  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2732, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Anaconda3\lib\site-packages\peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2949, in execute_sql
    cursor.execute(sql, params or ())
  File "C:\Anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
peewee.InternalError: (1367, "Illegal double '1.79769313486232e+308' value found during parsing")

**Comment by xldistance** [comment]
换postgres就正常了，上postgres吧😁

**Comment by vnpy** [comment]
这块我们测试后无法保证重现，猜测可能和接口过来的原始数据溢出有关，如果确实频繁出现就请用postgresql数据库吧
