### ISSUE TITLE
order exception

### ISSUE THREAD

**Issue by sunzhouhong** [vnpy/vnpy#1964]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7.4 64位
* vn.py版本: 如v2.0.3发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug

## 实际程序行为
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\vnpy_2.0.3_20190614_1\vnpy\event\event_engine.py", line 59, in _run
    self._process(event)
  File "D:\vnpy_2.0.3_20190614_1\vnpy\event\event_engine.py", line 72, in _process
    [handler(event) for handler in self._handlers[event.type]]
  File "D:\vnpy_2.0.3_20190614_1\vnpy\event\event_engine.py", line 72, in <listcomp>
    [handler(event) for handler in self._handlers[event.type]]
  File "D:\vnpy_2.0.3_20190614_1\vnpy\app\cta_strategy\cta_trading_engine.py", line 166, in process_order_event
    self.offset_converter.update_order(order_data)
  File "D:\vnpy_2.0.3_20190614_1\vnpy\app\cta_strategy\converter.py", line 45, in update_order
    position_holding.update_order(order_data)
  File "D:\vnpy_2.0.3_20190614_1\vnpy\app\cta_strategy\converter.py", line 138, in update_order
    self.calculate_frozen()
  File "D:\vnpy_2.0.3_20190614_1\vnpy\app\cta_strategy\converter.py", line 200, in calculate_frozen
    frozen = order_data.volume - order_data.traded
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
使用的什么交易接口？

**Comment by sunzhouhong** [comment]
huobi

**Comment by vnpy** [comment]
请升级到最新的2.0.6试试吧
