### ISSUE TITLE
 round_to函数 中 遇到float NaN数据强转int,导致程序崩溃

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#1970]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: v2.0.5

## Issue类型
三选一：Bug/Enhancement/Question

## 重现步骤

Exception in thread Thread-8:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\threading.py", line 917, in _boo
tstrap_inner
    self.run()
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_backt
ester\engine.py", line 272, in run_optimization
    output=False
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_strat
egy\backtesting.py", line 673, in run_ga_optimization
    halloffame=hof
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\deap\algorithms.py
", line 302, in eaMuPlusLambda
    for ind, fit in zip(invalid_ind, fitnesses):
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_strat
egy\backtesting.py", line 1197, in ga_optimize
    return _ga_optimize(tuple(parameter_values))
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_strat
egy\backtesting.py", line 1190, in _ga_optimize
    ga_mode
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_strat
egy\backtesting.py", line 1164, in optimize
    engine.run_backtesting()
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_strat
egy\backtesting.py", line 293, in run_backtesting
    func(data)
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_strat
egy\backtesting.py", line 708, in new_bar
    self.strategy.on_bar(bar)
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_strat
egy\strategies\turtle_signal_strategy.py", line 92, in on_bar
    self.send_buy_orders(self.entry_up)
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_strat
egy\strategies\turtle_signal_strategy.py", line 136, in send_buy_orders
    self.buy(price, self.fixed_size, True)
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_strat
egy\template.py", line 155, in buy
    return self.send_order(Direction.LONG, Offset.OPEN, price, volume, stop, loc
k)
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_strat
egy\template.py", line 189, in send_order
    self, direction, offset, price, volume, stop, lock
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\app\cta_strat
egy\backtesting.py", line 906, in send_order
    price = round_to(price, self.pricetick)
  File "D:\ProgramData\Anaconda3\envs\vnpy2\lib\site-packages\vnpy\trader\utilit
y.py", line 116, in round_to
    rounded = int(round(value / target)) * target
ValueError: cannot convert float NaN to integer

**Comment by vnpy** [comment]
这是因为pricetick设置太小导致的，自己检查下吧

**Comment by xldistance** [comment]
def round_to(value: float, target: float):
    """
    Round price to price tick value.
    """
    tmp = float(target)
    rounded = int(round(np.nan_to_num(value) / tmp)) * tmp
    return rounded
