### ISSUE TITLE
vnpy 2.0.6运行xtp_gateway报错

### ISSUE THREAD

**Issue by 15759101796** [vnpy/vnpy#1995]
## 环境

* 操作系统: Ubuntu 18.04
* Anaconda版本: Python 3.7 64位
* vn.py版本: v2.0.6

## Issue类型
三选一：Bug

## 预期程序行为
运行XTP

## 实际程序行为
>> python run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from vnpy.gateway.xtp import XtpGateway
  File "/opt/miniconda3/lib/python3.7/site-packages/vnpy-2.0.6-py3.7-linux-x86_64.egg/vnpy/gateway/xtp/__init__.py", line 1, in <module>
    from .xtp_gateway import XtpGateway
  File "/opt/miniconda3/lib/python3.7/site-packages/vnpy-2.0.6-py3.7-linux-x86_64.egg/vnpy/gateway/xtp/xtp_gateway.py", line 5, in <module>
    from vnpy.api.xtp.vnxtp import (
ImportError: cannot import name 'XTP' from 'vnpy.api.xtp.vnxtp' (unknown location)
>> ./generate_xtp.sh
Usage: __main__.py [OPTIONS] COMMAND [ARGS]...
Try "__main__.py --help" for help.

Error: No such command "vnxtp".
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
2.0.6没有支持xtp的ubuntu版本
