### ISSUE TITLE
[Error] TypeError: unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by cbogithub** [vnpy/vnpy#2036]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* Anaconda版本: 如Anaconda 18.12 Python 3.7 64位
* vn.py版本: 如v2.0发行版或者dev branch 20190101（下载日期）

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python37\lib\site-packages\vnpy\event\engine.py", line 60, in _run
    self._process(event)
  File "C:\Python37\lib\site-packages\vnpy\event\engine.py", line 73, in _process
    [handler(event) for handler in self._handlers[event.type]]
  File "C:\Python37\lib\site-packages\vnpy\event\engine.py", line 73, in <listcomp>
    [handler(event) for handler in self._handlers[event.type]]
  File "C:\Python37\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 165, in process_order_event
    self.offset_converter.update_order(order)
  File "C:\Python37\lib\site-packages\vnpy\app\cta_strategy\converter.py", line 45, in update_order
    holding.update_order(order)
  File "C:\Python37\lib\site-packages\vnpy\app\cta_strategy\converter.py", line 138, in update_order
    self.calculate_frozen()
  File "C:\Python37\lib\site-packages\vnpy\app\cta_strategy\converter.py", line 200, in calculate_frozen
    frozen = order.volume - order.traded
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
请问使用的是什么版本的vn.py？以及具体使用的交易接口

**Comment by cbogithub** [comment]
I use vnpy 2.07 dev newest version. And run cta_strategy with Binace gateway

**Comment by vnpy** [comment]
This bug is very old and has been fixed in previous version. If you install from dev branch, then there should be something wrong during your installation. Please use latest version of VNStudio 2.0.6.
