### ISSUE TITLE
策略文件加载失败

### ISSUE THREAD

**Issue by caimmy** [vnpy/vnpy#2072]
## 环境

* 操作系统: Windows 10
* vn.py版本: v2.0.6发行版

## Issue类型
三选一：Question

## 预期程序行为
能够从策略下拉列表中选中自定义策略

## 实际程序行为
自定义的策略文件没有加载成功

报错信息如下
`
策略文件strategies.demo_strategy加载失败，触发异常：
Traceback (most recent call last):
  File "D:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 760, in load_strategy_class_from_module
    module = importlib.import_module(module_name)
  File "D:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\vnpy_models\strategies\demo_strategy.py", line 2, in <module>
    from nvpy.app.cta_strategy import (
ModuleNotFoundError: No module named 'nvpy'

`

## 重现步骤

自定义策略文件复制的知乎vnpy专栏的例子。

**Comment by caimmy** [comment]
![image](https://user-images.githubusercontent.com/4225093/64394775-4c8ec500-d08a-11e9-9600-6acc377d60f6.png)
在vnpy的prompt下面通过pip查看安装的包，能看到vnpy。

**Comment by caimmy** [comment]
在prompt下面直接执行策略脚本文件。
![image](https://user-images.githubusercontent.com/4225093/64394808-7942dc80-d08a-11e9-809e-ac21f13f61f1.png)

界面的策略日志：
![image](https://user-images.githubusercontent.com/4225093/64394825-8a8be900-d08a-11e9-93e7-2f225b439fbb.png)

在prompt的命令行，尝试直接导入：
![image](https://user-images.githubusercontent.com/4225093/64394866-b313e300-d08a-11e9-9eb3-048a3b7467ae.png)
