### ISSUE TITLE
回测tick数据提示last_price错误

### ISSUE THREAD

**Issue by Lsgo** [vnpy/vnpy#2128]
## 环境

* 操作系统: Windows 10
* Python版本: python3.7.4
* vn.py版本: v2.0.7

## Issue类型
三选一：Bug

## 预期程序行为
我有一个tick的策略需要回测
设置 mode = BacktestingMode.TICK 进行回测时提示错误 错误日志如下
(python37) PS E:\myquant\vnpy_coding> & D:/Anaconda3/envs/python37/python.exe e:/myquant/vnpy_coding/strategies/pulse_trade.py
2019-10-05 14:42:07.954554      开始加载历史数据
2019-10-05 14:42:15.188163      加载进度：########## [100%]
2019-10-05 14:42:15.189161      历史数据加载完成，数据量：31839
Traceback (most recent call last):
  File "e:/myquant/vnpy_coding/strategies/pulse_trade.py", line 177, in <module>
    engine.run_backtesting()
  File "D:\Anaconda3\envs\python37\lib\site-packages\vnpy\app\cta_strategy\backtesting.py", line 282, in run_backtesting
    self.callback(data)
  File "D:\Anaconda3\envs\python37\lib\site-packages\vnpy\app\cta_strategy\strategies\pulse_trade.py", line 77, in on_bar
    self.bg.update_bar(bar)
  File "D:\Anaconda3\envs\python37\lib\site-packages\vnpy\trader\utility.py", line 231, in update_bar
    self.window_bar.close_price = bar.close_price
AttributeError: 'TickData' object has no attribute 'close_price'

我看了tick bar确实没有 close_price字段. 值有last_price 

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
对于tick回测模式的策略来说，请在策略代码中使用load_tick函数来加载历史数据，而不是load_bar
