### ISSUE TITLE
在加载RPC模块的情况下，关闭程序会弹出两个错误提示

### ISSUE THREAD

**Issue by linbozhong** [vnpy/vnpy#2163]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.7

## 实际程序行为

错误提示1：

如果不连接RPC，关闭程序会弹出如下错误提示：
这个容易排查，因为没有连接rpc，所以self.__thread的值一直是None，而关闭的时候没有对此做判断。

Traceback (most recent call last):
  File "E:\vnpy\vnpy-2.0.7\vnpy\trader\ui\mainwindow.py", line 253, in closeEvent
    self.main_engine.close()
  File "E:\vnpy\vnpy-2.0.7\vnpy\trader\engine.py", line 223, in close
    gateway.close()
  File "E:\vnpy\vnpy-2.0.7\vnpy\gateway\rpc\rpc_gateway.py", line 104, in close
    self.client.join()
  File "E:\vnpy\vnpy-2.0.7\vnpy\rpc\__init__.py", line 244, in join
    if self.__thread.isAlive():
AttributeError: 'NoneType' object has no attribute 'isAlive'

错误提示2：
如果连接了RPC，关闭程序后会弹出如下错误提示：

因为没有对zmq做深入研究，所以不清楚这个提示怎么来的。

Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\vnstudio\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\vnstudio\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "E:\vnpy\vnpy-2.0.7\vnpy\rpc\__init__.py", line 254, in run
    if not self.__socket_sub.poll(pull_tolerance):
  File "C:\vnstudio\lib\site-packages\zmq\sugar\socket.py", line 697, in poll
    evts = dict(p.poll(timeout))
  File "C:\vnstudio\lib\site-packages\zmq\sugar\poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq\backend\cython\_poll.pyx", line 143, in zmq.backend.cython._poll.zmq_poll
  File "zmq\backend\cython\_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
  File "zmq\backend\cython\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Unknown error

这两个错误提示都是在程序关闭的时候弹出的，对程序的运行没有太大的影响，但是如果能修复的话是最好了。

**Comment by vnpy** [comment]
1. 已经修复了
2. 我们来看下吧

**Comment by vnpy** [comment]
查了pyzmq官方的issue记录，似乎第二个问题没法定位：

https://github.com/zeromq/pyzmq/issues/783
