### ISSUE TITLE
CTA回测报错：TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#2184]
## 环境

* 操作系统: 如Windows 10
* Python版本: python37
* vn.py版本: v2.0.7

## Issue类型
Question

## 预期程序行为
正常输出backtest结果

## 实际程序行为
```
pydev debugger: process 7232 is connecting

Connected to pydev debugger (build 192.6603.34)
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Users\lcxly\vnstudio\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\lcxly\vnstudio\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\lcxly\PycharmProjects\quantopy\vnpy\app\cta_backtester\engine.py", line 167, in run_backtesting
    engine.run_backtesting()
  File "C:\Users\lcxly\PycharmProjects\quantopy\vnpy\app\cta_strategy\backtesting.py", line 282, in run_backtesting
    self.callback(data)
TypeError: 'NoneType' object is not callable
```

策略已经对没有使用的回调函数pass操作，实在找不到原因，求帮助。

**Comment by WeiZhou2372** [comment]
我也遇到类似问题，在tick回测模式下才会报错，你是怎么解决的？
