### ISSUE TITLE
报错求助，macos开启ss代理的情况下无法连接火币服务器

### ISSUE THREAD

**Issue by Roverzed** [vnpy/vnpy#2192]
## 环境

* 操作系统: macos
* Python版本: anaconda3-5.3.1 python3.7
* vn.py版本: 20191111
## Issue类型
三选一：Question

## 报错
`Exception trace: 
Traceback (most recent call last):
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 815, in _prepare_proxy
    conn.connect()
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/urllib3/connection.py", line 324, in connect
    self._tunnel()
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/http/client.py", line 906, in _tunnel
    (version, code, message) = response._read_status()
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/http/client.py", line 278, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/urllib3/connectionpool.py", line 815, in _prepare_proxy
    conn.connect()
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/urllib3/connection.py", line 324, in connect
    self._tunnel()
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/http/client.py", line 906, in _tunnel
    (version, code, message) = response._read_status()
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/http/client.py", line 278, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\x05\x00\x05\x07\x00\x01'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zed/vnpy/vnpy/vnpy/api/rest/rest_client.py", line 278, in _process_request
    proxies=self.proxies,
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/zed/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x05\x00\x05\x07\x00\x01'))
`![image](https://user-images.githubusercontent.com/29392414/68660736-b9d04200-0574-11ea-8d69-ea59c4468365.png)`

**Comment by vnpy** [comment]
要在VN Trader连接对话框，具体指定SS客户端的本地地址和端口，全局配置是没用的。

请检查下是不是这个原因吧

**Comment by Roverzed** [comment]
我已经指定了，终端里可以走代理的，
