### ISSUE TITLE
example/no_ui/run.py程序，使用mysql数据库，每次快到交易时间启动子进程，策略读数据时会报连接错误，重启整个run进程就没问题。

### ISSUE THREAD

**Issue by linbozhong** [vnpy/vnpy#2208]
## 环境

* 操作系统: Ubuntu 16.04
* Python版本: 如VNStudio-2.0.7

## Issue类型
三选一：Bug

## 预期程序行为
cta engine能正常查询mysql数据库的数据

## 实际程序行为
报连接异常

## 重现步骤

使用mysql数据库存在下面问题：
每次快到交易时间，重新启动交易系统子进程的时候都会出现这个连接异常。只要关闭进程，重新启动整个run进程就可以正常连接mysql读取数据。
我对mysql和peewee这个orm还不是特别了解，猜测是不是收盘过段时间后，交易系统子进程被直接kill掉导致的？

下面整个错误提示在早上8：46分和晚上8：46，交易系统子进程启动，策略加载mysql数据的时候都会出现，后面还有大量因为没有成功连接而出现的其他异常。这里我只截取一部分。

```
...
....

2019-11-20 08:46:11,754  INFO: CTA策略全部初始化
2019-11-20 08:46:11,757  INFO: cu: 策略启动
2019-11-20 08:46:11,786  INFO: cu: 触发异常已停止
Traceback (most recent call last):
  File "/home/lbz/miniconda3/lib/python3.7/site-packages/pymysql/connections.py", line 713, in _write_bytes
    self._sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lbz/miniconda3/lib/python3.7/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
  File "/home/lbz/miniconda3/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/lbz/miniconda3/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/lbz/miniconda3/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/lbz/miniconda3/lib/python3.7/site-packages/pymysql/connections.py", line 771, in _execute_command
    self._write_bytes(packet)
  File "/home/lbz/miniconda3/lib/python3.7/site-packages/pymysql/connections.py", line 718, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")

....
....

```

**补充：**

我改变了run文件的判断trading的代码，以便模拟父进程关闭子进程然后开启子进程的整个过程。中间只停了2分钟左右，这样的测试发现没有异常，可以正常加载mysql的数据。

看来似乎中间要停留较长时间才会报出异常，之前对网络编程和数据库并不是太了解，简单查了下资料。
用这个命令netstat -atulnp | grep 3306查看连接，发现父进程关闭子进程之后，这个连接仍然存在。所以猜测会不会因为子进程获取完数据后没有关闭连接，然后过了一晚上之后超出mysql的wait_time默认的8小时，再次连接的时候就出错？
于是缩短了wait_timeout和interactive_timeout，再次做测试，果然弹出了异常，不过这个异常错误是：
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
而此前的异常是：
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")

并不一样，所以目前仍然还不确定是否是因为子进程mysql连接未关闭引起的。

**再补充：**

早上起来，应该已经过了8个小时了。用mysql的show processlist查看连接，已经销毁了这个连接。然后用netstat查看端口连接，这次发现run进程和3306端口的连接已经消失不见了。再想起报2006异常之前还有一个异常：BrokenPipeError: [Errno 32] Broken pipe。
所以我猜测，可能是mysql超时关闭后，又过了一段时间，连接3306端口的管道也关闭了，但是启动新的交易子进程可能没办法重新建立起新的管道连接，导致无网络连接可用的缘故把。
我先试试把mysql的wait_timeout设置到16个小时，让它一直保持住这个连接，看是否能暂时解决这个问题。

**后续**

把mysql的wait_timeout设置更久之后，可以保持住这个长连接，问题可以临时得到解决。

**Comment by liuagng** [comment]
you can set the Mysql connect max count to fix this problem.

**Comment by vnpy** [comment]
非常感谢后续更新，这么看其实没必要的话还不如用SQLite了，可以省去很多折腾的时间
