### ISSUE TITLE
打开vnstudio CTA 回测模块报错

### ISSUE THREAD

**Issue by wew20000** [vnpy/vnpy#2249]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.8
* vn.py版本: 如v2.0.8发

## Issue类型
三选一：Bug

## 预期程序行为
vnstudio中正常打开回测模块

## 实际程序行为

如题 米矿突然开始报错。无法进入回测模块。

## 重现步骤

Traceback (most recent call last):
File "C:\vnstudio\lib\site-packages\vnpy\trader\ui\mainwindow.py", line 278, in open_widget
widget = widget_class(self.main_engine, self.event_engine)
File "C:\vnstudio\lib\site-packages\vnpy\app\cta_backtester\ui\widget.py", line 43, in init
self.backtester_engine.init_engine()
File "C:\vnstudio\lib\site-packages\vnpy\app\cta_backtester\engine.py", line 60, in init_engine
self.init_rqdata()
File "C:\vnstudio\lib\site-packages\vnpy\app\cta_backtester\engine.py", line 66, in init_rqdata
result = rqdata_client.init()
File "C:\vnstudio\lib\site-packages\vnpy\trader\rqdata.py", line 56, in init
use_pool=True,
File "C:\vnstudio\lib\site-packages\rqdatac\client.py", line 167, in init
remaining_days = quota["remaining_days"]
TypeError: 'NoneType' object is not subscriptable

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
> C:\vnstudio\lib\site-packages\rqdatac\client.py

查了下，该报错来源于rqdatac内部，请尝试通过pip install rqdatac --upgrade升级到最新版
