### ISSUE TITLE
ByBit接口 websocket报错

### ISSUE THREAD

**Issue by 1122455801** [vnpy/vnpy#2266]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.0.8

## Issue类型
三选一：Bug

## 实际程序行为

[2020-01-02T10:58:15.274153]: Unhandled WebSocket Error:<class 'websocket._excep
tions.WebSocketBadStatusException'>
LastSentText:
{"op": "subscribe", "args": ["orderBookL2_25.BTCUSD"]}
LastReceivedText:
{"topic":"orderBookL2_25.BTCUSD","type":"delta","data":{"delete":[],"update":[{"
price":"7144.00","symbol":"BTCUSD","id":71440000,"side":"Sell","size":62629},{"p
rice":"7145.50","symbol":"BTCUSD","id":71455000,"side":"Sell","size":42139}],"in
sert":[],"transactTimeE6":0},"cross_seq":1007623845,"timestamp_e6":1577933894667
476}
Exception trace:
Traceback (most recent call last):
  File "C:\vnpy-master\vnpy\api\websocket\websocket_client.py", line 197, in _ru
n
    self._ensure_connection()
  File "C:\vnpy-master\vnpy\api\websocket\websocket_client.py", line 170, in _en
sure_connection
    header=self.header
  File "C:\vnpy-master\vnpy\api\websocket\websocket_client.py", line 158, in _cr
eate_connection
    return websocket.create_connection(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\websocket\_core.py", line 515
, in create_connection
    websock.connect(url, **options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\websocket\_core.py", line 226
, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\websocket\_handshake.py", lin
e 80, in handshake
    status, resp = _get_resp_headers(sock)
  File "C:\ProgramData\Anaconda3\lib\site-packages\websocket\_handshake.py", lin
e 165, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_m
essage, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 502 Bad Gate
way

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
已修复
