### ISSUE TITLE
okexf的rest接口问题

### ISSUE THREAD

**Issue by qinxi1122** [vnpy/vnpy#2273]
D:\Miniconda3\envs\vnpy2-xiaoyou\python.exe E:/QuantProject/vnpy2-晓优/examples/vn_trader/run_test.py
[2020-01-06T21:37:59.646885]: Unhandled RestClient Error:<class 'requests.exceptions.ConnectionError'>
request:request: GET /api/futures/v3/orders/ETH-USDT-200117?status=1 terminated: 
full_url: https://www.okex.com/api/futures/v3/orders/ETH-USDT-200117?status=1
status: error
headers: {'OK-ACCESS-KEY': '313d5cf8-4357-44c0-b95f-9cdd378450cf', 'OK-ACCESS-SIGN': b'6PvXX0pdNSH0hg8ELTFOPLlALMqovAzA2cxx8YqrWQM=', 'OK-ACCESS-TIMESTAMP': '2020-01-06T13:37:59.611Z', 'OK-ACCESS-PASSPHRASE': 'cz111111', 'Content-Type': 'application/json'}
params: None
data: null
response: None

Exception trace: 
Traceback (most recent call last):
  File "D:\Miniconda3\envs\vnpy2-xiaoyou\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "D:\Miniconda3\envs\vnpy2-xiaoyou\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "D:\Miniconda3\envs\vnpy2-xiaoyou\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Miniconda3\envs\vnpy2-xiaoyou\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "D:\Miniconda3\envs\vnpy2-xiaoyou\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "D:\Miniconda3\envs\vnpy2-xiaoyou\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "D:\Miniconda3\envs\vnpy2-xiaoyou\lib\site-packages\urllib3\connection.py", line 334, in connect
    conn = self._new_conn()
  File "D:\Miniconda3\envs\vnpy2-xiaoyou\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000223B22943C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Miniconda3\envs\vnpy2-xiaoyou\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Miniconda3\envs\vnpy2-xiaoyou\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Miniconda3\envs\vnpy2-xiaoyou\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.okex.com', port=443): Max retries exceeded with url: /api/futures/v3/orders/ETH-USDT-200117?status=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000223B22943C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by vnpy** [comment]
这个报错是标准的网络问题了，请检查下是否网络断开或者翻墙的梯子挂了
