### ISSUE TITLE
windows下 使用多进程参数优化BUG

### ISSUE THREAD

**Issue by qmzhn** [vnpy/vnpy#2308]
## 环境

* 操作系统: Windows 10
* Python版本: Python 3.7.4
* vn.py版本: v2.0.9

## Issue类型
三选一：Bug

## 重现步骤
2020-01-20 01:22:51.361774	开始回放历史数据
2020-01-20 01:22:51.361774	逐日盯市盈亏计算完成
2020-01-20 01:22:51.361774	开始计算策略统计指标
2020-01-20 01:22:51.380722	历史数据回放结束
2020-01-20 01:22:51.380722	开始计算逐日盯市盈亏
2020-01-20 01:22:51.386706	逐日盯市盈亏计算完成
2020-01-20 01:22:51.386706	开始计算策略统计指标
Exception in thread Thread-4:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "G:\ProgramData\Anaconda3\lib\site-packages\talib\__init__.py", line 20, in wrapper
    for arg in chain(args, kwargs.values())
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "G:\ProgramData\Anaconda3\lib\site-packages\vnpy\app\cta_strategy\backtesting.py", line 1210, in optimize
    engine.run_backtesting()
  File "G:\ProgramData\Anaconda3\lib\site-packages\vnpy\app\cta_strategy\backtesting.py", line 294, in run_backtesting
    func(data)
  File "G:\ProgramData\Anaconda3\lib\site-packages\vnpy\app\cta_strategy\backtesting.py", line 724, in new_bar
    self.strategy.on_bar(bar)
  File "G:\ProgramData\Anaconda3\lib\site-packages\vnpy\app\cta_strategy\strategies\double_ma_strategy.py", line 73, in on_bar
    fast_ma = am.sma(self.fast_window, array=True)
  File "G:\ProgramData\Anaconda3\lib\site-packages\vnpy\trader\utility.py", line 377, in sma
    result = talib.SMA(self.close, n)
  File "G:\ProgramData\Anaconda3\lib\site-packages\talib\__init__.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "_func.pxi", line 9954, in talib._ta_lib.SMA
  File "_common.pxi", line 30, in talib._ta_lib._ta_check_success
Exception: TA_SMA function failed with error code 2: Bad Parameter (TA_BAD_PARAM)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\ProgramData\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "G:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "G:\ProgramData\Anaconda3\lib\site-packages\vnpy\app\cta_backtester\engine.py", line 295, in run_optimization
    output=False
  File "G:\ProgramData\Anaconda3\lib\site-packages\vnpy\app\cta_strategy\backtesting.py", line 569, in run_optimization
    result_values = [result.get() for result in results]
  File "G:\ProgramData\Anaconda3\lib\site-packages\vnpy\app\cta_strategy\backtesting.py", line 569, in <listcomp>
    result_values = [result.get() for result in results]
  File "G:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
Exception: TA_SMA function failed with error code 2: Bad Parameter (TA_BAD_PARAM)
因为回测的是的双均线策略，提示TA_SMA错误，自己捣鼓了半天没弄出来。

**Comment by vnpy** [comment]
Exception: TA_SMA function failed with error code 2: Bad Parameter

这里的报错，我猜测可能是第二个参数n，优化时出现了0或者负数

**Comment by qmzhn** [comment]
经晓优大神提点，测试后发现TA_SMA的n不能为1……
