### ISSUE TITLE
zha==

### ISSUE THREAD

**Issue by hanfeng1982** [vnpy/vnpy#2361]
## 环境

* 操作系统: Ubuntu 18.04
* Python版本: 3.7.4（gcc:7.3.0）
* vn.py版本: v2.1.0
## Issue类型
Question

## 预期程序行为
正常运行
## 实际程序行为
报错

## 重现步骤
python run.py 
(base) root@iZj6c8yz09wrirsl1dqqo5Z:~/vnpy-2.1.0/examples/vn_trader# python run.py 
Traceback (most recent call last):
  File "run.py", line 36, in <module>
    from vnpy.gateway.uft import UftGateway
  File "/root/miniconda3/lib/python3.7/site-packages/vnpy/gateway/uft/__init__.py", line 1, in <module>
    from .uft_gateway import UftGateway
  File "/root/miniconda3/lib/python3.7/site-packages/vnpy/gateway/uft/uft_gateway.py", line 8, in <module>
    from vnpy.api.uft import (
  File "/root/miniconda3/lib/python3.7/site-packages/vnpy/api/uft/__init__.py", line 3, in <module>
    from .vnuftmd import MdApi
ModuleNotFoundError: No module named 'vnpy.api.uft.vnuftmd'

用阿里云的ubuntu18.0.4按照官方按照完成，运行run.sh的时候说找不到vnpy.api.uft.vnuftmd，咋办呀？
另外，海外的windows版本服务器好贵，用ubuntu安装调试了好久，问题好多。请教下ubuntu下有没有啥简单的方法安装使用呀？

**Comment by vnpy** [comment]
UFT接口不支持Ubuntu系统，请在run.py中移除即可
