### ISSUE TITLE
ModuleNotFoundError: No module named 'vnpy.api.uft.vnuftmd'

### ISSUE THREAD

**Issue by ForyoungYu** [vnpy/vnpy#2367]
## 环境

* 操作系统: Ubuntu 18.04.4
* Python版本: python3.7.4
* vn.py版本: v2.1.0

## Issue类型
Bug

## 预期程序行为

能正常运行examples/vn_trader/run.py文件

## 实际程序行为
首次运行run.py报错如下：
Traceback (most recent call last):
  File "/home/salt/下载/vnpy-2.1.0/examples/vn_trader/run.py", line 36, in <module>
    from vnpy.gateway.uft import UftGateway
  File "/home/salt/miniconda3/lib/python3.7/site-packages/vnpy/gateway/uft/__init__.py", line 1, in <module>
    from .uft_gateway import UftGateway
  File "/home/salt/miniconda3/lib/python3.7/site-packages/vnpy/gateway/uft/uft_gateway.py", line 8, in <module>
    from vnpy.api.uft import (
  File "/home/salt/miniconda3/lib/python3.7/site-packages/vnpy/api/uft/__init__.py", line 3, in <module>
    from .vnuftmd import MdApi
ModuleNotFoundError: No module named 'vnpy.api.uft.vnuftmd'

该如何解决？
另外ubuntu环境下安装曲折，我是将install.sh 里的代码一步一步输的。

## 重现步骤
无

**Comment by vnpy** [comment]
移除run.py中的uft_gateway加载即可，UBUNTU只支持CTP/IB/FUTU/数字货币类的接口
