### ISSUE TITLE
电子眼,豆粕期权,白糖期权"开始定价"抛出异常 ZeroDivisionError: float division

### ISSUE THREAD

**Issue by Austin-7** [vnpy/vnpy#2379]
## 环境

* 操作系统: 如Windows 10 
* Python版本: 如VNStudio-2.1.0
* vn.py版本: 如v2.1.0发行版 和  vnpy-master-20200303下载 都有测试,

## Issue类型
三选一：Bug

## 实际程序行为
电子眼,豆粕期权, 白糖期权 "开始定价"抛出异常 ZeroDivisionError: float division

## 重现步骤
此问题好像来自二叉树--美式期货期权 定价模型,
经过多次反复测试, 在IO股指期权(black 76欧式期货期权定价), 铜期权(black 76欧式期货期权定价)上,没有这个问题,
在豆粕期权和白糖期权(二叉树--美式期货期权 定价), 上可以重现这个问题， 在白糖期权上面更是很容易出现,反复出现（进入Ｔ型报价就重现）， 但是在棉花期权（同样是二叉树--美式期货期权 定价）则可以正常进入电子眼未见抛出异常，奇怪ing．．．．．

针对Bug类型Issue，请提供具体重现步骤以及报错截图

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\vnstudio\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\vnstudio\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.0.1-py3.7.egg\vnpy\event\engine.py", line 60, in _run
    self._process(event)
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.0.1-py3.7.egg\vnpy\event\engine.py", line 73, in _process
    [handler(event) for handler in self._handlers[event.type]]
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.0.1-py3.7.egg\vnpy\event\engine.py", line 73, in <listcomp>
    [handler(event) for handler in self._handlers[event.type]]
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.0.1-py3.7.egg\vnpy\app\option_master\engine.py", line 173, in process_tick_event
    portfolio.update_tick(tick)
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.0.1-py3.7.egg\vnpy\app\option_master\base.py", line 522, in update_tick
    chain.update_tick(tick)
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.0.1-py3.7.egg\vnpy\app\option_master\base.py", line 375, in update_tick
    option.update_tick(tick)
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.0.1-py3.7.egg\vnpy\app\option_master\base.py", line 229, in update_tick
    self.calculate_option_impv()
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.0.1-py3.7.egg\vnpy\app\option_master\base.py", line 162, in calculate_option_impv
    self.option_type
  File "binomial_tree_cython.pyx", line 245, in binomial_tree_cython.calculate_impv
  File "binomial_tree_cython.pyx", line 77, in binomial_tree_cython.calculate_price
  File "binomial_tree_cython.pyx", line 30, in binomial_tree_cython.generate_tree
ZeroDivisionError: float division

**Comment by vnpy** [comment]
已在dev-portfolio-strategy修复，非常感谢
