### ISSUE TITLE
期权合约计算隐波的calculate_option_impv函数会抛出异常:underlying_price = self.underlying.mid_price AttributeError: 'NoneType' object has no attribute 'mid_price'

### ISSUE THREAD

**Issue by Austin-7** [vnpy/vnpy#2499]
## 环境

* 操作系统: Windows 10 
* Python版本: VNStudio-2.1.0 ?
* vn.py版本: vnpy-2.1.2

## Issue类型
三选一：Bug   

## 实际程序行为
    期权合约计算隐波的calculate_option_impv函数会抛出异常:underlying_price = self.underlying.mid_price AttributeError: 'NoneType' object has no attribute 'mid_price'
    此现象在之前发布的几个版本上好像都有遇到过,
## 重现步骤
     这个问题偶而会出现, 尤其是在交易的已经开市正在交易时段, 启动vnpy后, 接着就连接CTP, 接着启动OptionMaster, 接着就进行配置,  有一定的概率会出现,如果网络传速比较慢的环境下, 重现概率会比较高些,不知道是不是因为underlying还未设置好, 就有期权合约的Tick进来,然后就开始计算隐波了?
    是不是可以像calculate_cash_greeks函数那样, 在calculate_option_impv函数开头,加一个:
    if not self.underlying:
        return
     如果underlying还未设置好,就先暂时不要继续计算隐波了

针对Bug类型Issue，请提供具体重现步骤以及报错截图:
Exception in thread Thread-3:
Traceback (most recent call last):
File "C:\vnstudio\lib\threading.py", line 917, in _bootstrap_inner
self.run()
File "C:\vnstudio\lib\threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\event\engine.py", line 60, in _run
self._process(event)
File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\event\engine.py", line 73, in _process
[handler(event) for handler in self._handlers[event.type]]
File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\event\engine.py", line 73, in <listcomp>
[handler(event) for handler in self._handlers[event.type]]
File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\engine.py", line 173, in process_tick_event
portfolio.update_tick(tick)
File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\base.py", line 606, in update_tick
chain.update_tick(tick)
File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\base.py", line 436, in update_tick
option.update_tick(tick)
File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\base.py", line 279, in update_tick
self.calculate_option_impv()
File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\base.py", line 176, in calculate_option_impv
underlying_price = self.underlying.mid_price
AttributeError: 'NoneType' object has no attribute 'mid_price'

**Comment by vnpy** [comment]
已修复，非常感谢
