### ISSUE TITLE
OptionMaster在配置时,  option_master\ui\manager.py", line 869, in update_pricing_impv     cells = self.cells[(chain_symbol, index)] KeyError: ('m2009.DCE', '2450.0')

### ISSUE THREAD

**Issue by Austin-7** [vnpy/vnpy#2500]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.1.0
* vn.py版本: v2.1.2

## Issue类型
三选一：Bug/Enhancement/Question

## 实际程序行为
OptionMaster在配置时,  option_master\ui\manager.py", line 869, in update_pricing_impv     cells = self.cells[(chain_symbol, index)] KeyError: ('m2009.DCE', '2450.0')

## 重现步骤
这个问题偶而会出现, 尤其是在交易的已经开市正在交易时段, 启动vnpy后, 接着就连接CTP, 接着启动OptionMaster, 接着就进行配置, 有一定的概率会出现,  感觉好像是UI还未初始化完成就收到Tick进来了吗?   
 
针对Bug类型Issue，请提供具体重现步骤以及报错截图:
Traceback (most recent call last):
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\ui\widget.py", line 131, in open_portfolio_dialog
    self.init_widgets()
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\ui\widget.py", line 143, in init_widgets
    self.pricing_manager = PricingVolatilityManager(self.option_engine, self.portfolio_name)
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\ui\manager.py", line 650, in __init__
    self.init_ui()
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\ui\manager.py", line 748, in init_ui
    self.update_pricing_impv(chain_symbol)
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\ui\manager.py", line 869, in update_pricing_impv
    cells = self.cells[(chain_symbol, index)]
KeyError: ('m2009.DCE', '2450.0')

**Comment by vnpy** [comment]
已修复，非常感谢
