### ISSUE TITLE
option_master\ui\monitor.py", line 291, in update_price AttributeError: 'NoneType' object has no attribute 'bid_price_1'

### ISSUE THREAD

**Issue by Austin-7** [vnpy/vnpy#2502]
## 环境

* 操作系统: 如Windows 10 
* Python版本: 如VNStudio-2.1.0
* vn.py版本: 如v2.1.2

## Issue类型
三选一：Bug

## 重现步骤
    本来是配置好了豆粕期权组合的, 白天工作的好好的, 但是下午收盘之后, vnpy程序未关闭, 一直开到晚上夜盘开市之后,就出现了这个状况

针对Bug类型Issue，请提供具体重现步骤以及报错截图
Traceback (most recent call last):
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\ui\monitor.py", line 254, in process_tick_event
    self.update_price(tick.vt_symbol)
  File "C:\vnstudio\lib\site-packages\vnpy-2.1.2-py3.7.egg\vnpy\app\option_master\ui\monitor.py", line 291, in update_price
    option_cells["bid_price"].setText(f'{tick.bid_price_1:0.4f}')
AttributeError: 'NoneType' object has no attribute 'bid_price_1'

**Comment by vnpy** [comment]
每天下午收盘必须关闭vn.py，夜盘开盘前重启
