### ISSUE TITLE
cta回测报错：TypeError: __init__() missing 1 required positional argument: 'accountid'

### ISSUE THREAD

**Issue by jieyujing** [vnpy/vnpy#2513]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.1.3.1
* vn.py版本: master最新版

## Issue类型
三选一：Question

## 预期程序行为
None

## 实际程序行为

2020-05-26 20:54:20.970566      触发异常，回测终止
2020-05-26 20:54:20.976543      Traceback (most recent call last):
  File "c:\Users\lcxly\quantopy\vnpy\app\cta_strategy\backtesting.py", line 287, in run_backtesting
    func(data)
  File "c:\Users\lcxly\quantopy\vnpy\app\cta_strategy\backtesting.py", line 738, in new_bar
    self.strategy.on_bar(bar)
  File "c:\Users\lcxly\quantopy\vnpy\app\cta_strategy\strategies\atr_rsi_strategy.py", line 108, in on_bar
    self.buy(bar.close_price + 5, self.fixed_size)
  File "c:\Users\lcxly\quantopy\vnpy\app\cta_strategy\template.py", line 155, in buy
    return self.send_order(Direction.LONG, Offset.OPEN, price, volume, stop, lock)
  File "c:\Users\lcxly\quantopy\vnpy\app\cta_strategy\template.py", line 189, in send_order
    self, direction, offset, price, volume, stop, lock
  File "c:\Users\lcxly\quantopy\vnpy\app\cta_strategy\backtesting.py", line 922, in send_order
    volume)
  File "c:\Users\lcxly\quantopy\vnpy\app\cta_strategy\backtesting.py", line 959, in send_limit_order
    datetime=self.datetime)
TypeError: __init__() missing 1 required positional argument: 'accountid'

## 重现步骤
from vnpy.app.cta_strategy.backtesting import BacktestingEngine, OptimizationSetting
from vnpy.app.cta_strategy.strategies.atr_rsi_strategy import (
    AtrRsiStrategy, )
from datetime import datetime

# %%
engine = BacktestingEngine()
engine.set_parameters(
    vt_symbol="ru9999.SHFE",
    interval="1m",
    start=datetime(2020, 1, 1),
    end=datetime(2020, 5, 30),
    rate=0.3 / 10000,
    slippage=0.2,
    size=300,
    pricetick=0.2,
    capital=1_000_000,
)
engine.add_strategy(AtrRsiStrategy, {})

# %%
engine.load_data()
engine.run_backtesting()
df = engine.calculate_result()
engine.calculate_statistics()
engine.show_chart()

**Comment by vnpy** [comment]
这么看是自行对object.py中的数据结构做了扩展，请进行排查吧。

或者卸载掉后重装v2.1.3.1即可。

**Comment by jieyujing** [comment]
好的，谢谢
