### ISSUE TITLE
IB gateway 成交返回EXCHANGE之外的值，导致异常

### ISSUE THREAD

**Issue by porfavor** [vnpy/vnpy#2524]
## 环境

* 操作系统: 如Windows 10或者Ubuntu 18.04
* vn.py版本: 如v2.1.2发行版

ib_gateway 成交返回值会有有些不在Exchange的枚举之内的指。这些异常值会导致TradeData传入的exchange为str类型，导致self.exchange.value报错

![image](https://user-images.githubusercontent.com/1224203/83444175-9243b700-a47d-11ea-9514-773b2652ea10.png)

**Comment by porfavor** [comment]
Exception in thread Thread-11:
Traceback (most recent call last):
  File "D:\Anaconda\Anaconda3_x86_64\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\Anaconda3_x86_64\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\GitRepos\vnpy2\vnpy\gateway\ib\ib_gateway.py", line 817, in run
    self.decoder.interpret(fields)
  File "D:\Anaconda\Anaconda3_x86_64\lib\site-packages\ibapi\decoder.py", line 1280, in interpret
    handleInfo.processMeth(self, iter(fields))
  File "D:\Anaconda\Anaconda3_x86_64\lib\site-packages\ibapi\decoder.py", line 487, in processExecutionDataMsg
    self.wrapper.execDetails(reqId, contract, execution)
  File "D:\GitRepos\vnpy2\vnpy\gateway\ib\ib_gateway.py", line 573, in execDetails
    gateway_name=self.gateway_name,
  File "<string>", line 12, in __init__
  File "D:\GitRepos\vnpy2\vnpy\trader\object.py", line 166, in __post_init__
    self.vt_symbol = f"{self.symbol}.{self.exchange.value}"
AttributeError: 'str' object has no attribute 'value'

**Comment by porfavor** [comment]
我目前看了下，美股的gateway比较多，我现在知道的有这么一些。
![image](https://user-images.githubusercontent.com/1224203/83445269-44c84980-a47f-11ea-8245-e7ec91b9cbab.png)
![image](https://user-images.githubusercontent.com/1224203/83445295-4db91b00-a47f-11ea-82c9-f540587f326c.png)

**Comment by vnpy** [comment]
OK，我们来升级下

**Comment by vnpy** [comment]
已添加EDGEA和ISLAND的支持
