### ISSUE TITLE
火币交割合约上线了次季合约，目前接口不支持

### ISSUE THREAD

**Issue by yxl560** [vnpy/vnpy#2582]
## 环境

* 操作系统: 如Windows 2016 服务器系统
* Python版本: 如VNStudio-2.0.6
* vn.py版本: 2.1.4

C:\Users\Administrator>python -m vnstation
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_ciphersuites
qt.network.ssl: QSslSocket: cannot resolve SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
Traceback (most recent call last):
  File "C:\vnstudio\lib\site-packages\vnpy\app\data_recorder\ui\widget.py", line 152, in add_bar_recording
    self.recorder_engine.add_bar_recording(vt_symbol)
  File "C:\vnstudio\lib\site-packages\vnpy\app\data_recorder\engine.py", line 117, in add_bar_recording
    self.subscribe(contract)
  File "C:\vnstudio\lib\site-packages\vnpy\app\data_recorder\engine.py", line 270, in subscribe
    self.main_engine.subscribe(req, contract.gateway_name)
  File "C:\vnstudio\lib\site-packages\vnpy\trader\engine.py", line 174, in subscribe
    gateway.subscribe(req)
  File "C:\vnstudio\lib\site-packages\vnpy\gateway\huobif\huobif_gateway.py", line 157, in subscribe
    self.market_ws_api.subscribe(req)
  File "C:\vnstudio\lib\site-packages\vnpy\gateway\huobif\huobif_gateway.py", line 931, in subscribe
    ws_contract_type = CONTRACT_TYPE_MAP[contract_type]
KeyError: 'next_quarter'

**Comment by vnpy** [comment]
已修复
