### ISSUE TITLE
火币交易所接口BUG问题

### ISSUE THREAD

**Issue by yxl560** [vnpy/vnpy#2608]
请官方帮助修复接口 BUG
火币交易所，报错代码如下，win版死机，报python 停止工作

qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback
[2020-07-31T14:03:01.177387]: Unhandled WebSocket Error:<class 'OSError'>
LastSentText:
{"pong": 1596175381119}
LastReceivedText:
b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x00\xabV*\xc8\xccKW\xb224\xb543475\xb6044\xb4\xac\x05\x00\x8d\x9e\xe2\x99\x16\x00\x00\x00'
Exception trace:
Traceback (most recent call last):
  File "C:\vnstudio\lib\site-packages\vnpy\api\websocket\websocket_client.py", line 249, in _run_ping
    self._ping()
  File "C:\vnstudio\lib\site-packages\vnpy\api\websocket\websocket_client.py", line 266, in _ping
    ws.send("ping", websocket.ABNF.OPCODE_PING)
  File "C:\vnstudio\lib\site-packages\websocket\_core.py", line 253, in send
    return self.send_frame(frame)
  File "C:\vnstudio\lib\site-packages\websocket\_core.py", line 279, in send_frame
    l = self._send(data)
  File "C:\vnstudio\lib\site-packages\websocket\_core.py", line 449, in _send
    return send(self.sock, data)
  File "C:\vnstudio\lib\site-packages\websocket\_socket.py", line 157, in send
    return _send()
  File "C:\vnstudio\lib\site-packages\websocket\_socket.py", line 139, in _send
    return sock.send(data)
  File "C:\vnstudio\lib\ssl.py", line 984, in send
    return self._sslobj.write(data)
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
Traceback (most recent call last):
  File "C:\vnstudio\lib\site-packages\vnpy\api\websocket\websocket_client.py", line 249, in _run_ping
    self._ping()
  File "C:\vnstudio\lib\site-packages\vnpy\api\websocket\websocket_client.py", line 266, in _ping
    ws.send("ping", websocket.ABNF.OPCODE_PING)
  File "C:\vnstudio\lib\site-packages\websocket\_core.py", line 253, in send
    return self.send_frame(frame)
  File "C:\vnstudio\lib\site-packages\websocket\_core.py", line 279, in send_frame
    l = self._send(data)
  File "C:\vnstudio\lib\site-packages\websocket\_core.py", line 449, in _send
    return send(self.sock, data)
  File "C:\vnstudio\lib\site-packages\websocket\_socket.py", line 157, in send
    return _send()
  File "C:\vnstudio\lib\site-packages\websocket\_socket.py", line 139, in _send
    return sock.send(data)
  File "C:\vnstudio\lib\ssl.py", line 984, in send
    return self._sslobj.write(data)
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_set_psk_use_session_callback

火币 交易所报错

**Comment by vnpy** [comment]
我们这边无法重现，搜了下网上资料，建议这么处理：
1. 检查你的代理是否稳定，最可能出现的原因就是代理闪断了
2. 运行命令`netsh winsock reset`
