### ISSUE TITLE
Windows Server 2008/2016 r2 安装VN Studio 2.1.4 后无法启动图形界面，发生qt相关错误。

### ISSUE THREAD

**Issue by forhonourlx** [vnpy/vnpy#2613]
Hi @vnpy 

我在Windows Server 2008/2016 r2安装VN Studio 2.1.4 遇到错误，请求帮助，先行谢过，感谢！

## 环境
* 操作系统: 如Windows Server 2008 r2 / Windows Server 2016 r2
* Python版本: 如VNStudio-2.1.4
* vn.py版本: 如v2.1.4

## Issue类型
三选一：Bug

## 预期程序行为
预期VN Studio 安装后，图形界面能够正常运行（如WIN10）。

## 实际程序行为
1.尝试Windows Server 2008 r2 / Windows Server 2016 r2安装 VN STUDIO 2.1.4后，双击图标无反应。

2.直接运行`run.py`:
```
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from vnpy.trader.ui import QtGui, create_qapp
  File "C:\vnstudio\lib\site-packages\vnpy\trader\ui\__init__.py", line 11, in <
module>
    from .mainwindow import MainWindow
  File "C:\vnstudio\lib\site-packages\vnpy\trader\ui\mainwindow.py", line 28, in
 <module>
    from .editor import CodeEditor
  File "C:\vnstudio\lib\site-packages\vnpy\trader\ui\editor.py", line 4, in <mod
ule>
    from PyQt5 import QtWidgets, Qsci, QtGui
ImportError: DLL load failed: 找不到指定的模块。
```

3.升级`pip install -U pyqt5 sip`后再次运行`run.py`：
遇到弹框错误：
```
python.exe - 系统错误
无法启动此程序，因为计算机中丢失 MFPlat.DLL。尝试重新安装该程序以解决此问题。

QtWebEngineProcess.exe - 系统错误
无法启动此程序，因为计算机中丢失 MFPlat.DLL。尝试重新安装该程序以解决此问题。
```
确定后：
```
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_ciphersuites
qt.network.ssl: QSslSocket: cannot resolve SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot resolve SSL_SESSION_is_resumable
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket: OpenSSL >= 1.1.1 is required; OpenSSL 1.1.0i  14 Aug
 2018 was found instead
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
```

**Comment by vnpy** [comment]
请下载安装vcredist x64 2019

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

安装好后重启电脑，再运行vn.py
