### ISSUE TITLE
使用dev的paper account app的报错

### ISSUE THREAD

**Issue by yhmickey** [vnpy/vnpy#2696]
手动下单后，报错如下：
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\vnpy\trader\ui\widget.py", line 893, in send_order
    self.main_engine.send_order(req, gateway_name)
  File "C:\ProgramData\Miniconda3\lib\site-packages\vnpy\app\paper_account\engine.py", line 189, in send_order
    active_orders.pop(orderid)
UnboundLocalError: local variable 'active_orders' referenced before assignment

**Comment by vnpy** [comment]
已在DEV分支修复
