### ISSUE TITLE
币安行情频繁断开，并且频繁弹出报错窗口直接卡住然后崩溃

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#2815]
## 环境

* 操作系统: 如Windows 10
* Python版本: Python 3.7
* vn.py版本: VNPY2.1.8

## Issue类型
三选一：Bug

```
Exception trace: 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\urllib3\connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\urllib3\connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001B45E5BE608>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fapi.binance.com', port=443): Max retries exceeded with url: /fapi/v1/listenKey?listenKey=e1sW6afr8m4PmL4

```

**Comment by vnpy** [comment]
请问您的：
1. 云服务器所在地区，或者翻墙工具？
2. 使用的vn.py版本是？

**Comment by AITrading2020** [comment]
1. 云服务器在新加坡
2.  vnpy版本是2.1.8

**Comment by gaozhong301** [comment]
我也是碰到以上一样的情况：
日子记录如下：
2021-01-17 04:45:01,074 INFO: 委托失败，状态码：400，信息：{"code":-4003,"msg":"Quantity less than zero."}
2021-01-17 05:00:01,533 INFO: 委托失败，状态码：400，信息：{"code":-4003,"msg":"Quantity less than zero."}
2021-01-17 07:45:01,202 INFO: 委托失败，状态码：400，信息：{"code":-4003,"msg":"Quantity less than zero."}
2021-01-17 09:00:00,286 INFO: 委托失败，状态码：400，信息：{"code":-4003,"msg":"Quantity less than zero."}
![image](https://user-images.githubusercontent.com/46582179/105139122-d41a8e00-5b30-11eb-85c7-9a032d1b5d71.png)

我个人认为应该是：平仓的时候，出现仓位负数导致，无法交易。
在系统重复发送过多错误交易后，远程服务器关闭了连接

**Comment by vnpy** [comment]
社区反馈该情况最近已经消失，前段时间出现应该是由于币安服务器自身问题，所以网络连接层没有可以处理的地方。
