### ISSUE TITLE
OES接口不能正常订阅

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#2818]
## 环境

* 操作系统: 如Windows 10 
* Python版本: 3.7.8
* vn.py版本: 如v2.1.5

## Issue类型
三选一：Bug/Enhancement/Question
BUG

## 预期程序行为
OES可正常订阅合约

## 实际程序行为
无法订阅股票

## 重现步骤
连接OES网关，订阅 SSE: 605006
`E:\APP\VNPY\VNPYMASTER20200901\examples\vn_trader>python run.py
2021-01-19 22:28:28,277  INFO: 成功连接到行情服务器
2021-01-19 22:28:28,776  INFO: 成功连接到交易服务器
2021-01-19 22:28:54,293  INFO: 合约信息查询成功
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\ShellMount\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\ShellMount\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\APP\VNPY\VNPYMASTER20200901\vnpy\gateway\oes\oes_md.py", line 128, in _message_loop
    self._on_message)
  File "E:\APP\VNPY\VNPYMASTER20200901\vnpy\gateway\oes\oes_md.py", line 113, in _on_message
    self.message_handlers[head.msgId](b)
  File "E:\APP\VNPY\VNPYMASTER20200901\vnpy\gateway\oes\oes_md.py", line 168, in on_init_tick
    tick.__dict__['bid_volume_' + str(i + 1)] = data.BidLevels[i].QrderQty / 100
AttributeError: 'vnpy.api.oes.vnoes._MdsPriceLevelEntry' object has no attribute 'QrderQty'
`
![image](https://user-images.githubusercontent.com/12572507/105048576-b274c480-5aa6-11eb-9dab-14ef8f7894fe.png)

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
目前OES的接口我们只支持了期权，没有支持股票版本呢

**Comment by ShellMount** [comment]
1, 我看文档介绍中，OES支持A股。
2，我订阅605006时，并不是不成功，也能看得到行情信息，是咋回事？（只是会出现这个报错）
3，能够正常交易股票，大概在什么时候能提供这个功能？

**Comment by vnpy** [comment]
查了下你使用的是老版本OES代码，目前已经不再支持，请升级到新版本再试试吧。

**Comment by ShellMount** [comment]
测试了最新版本: 2.1.5

这个报错依然存在。
