### ISSUE TITLE
vnpy2.1.9 版本无法启动VN Trader Pro，报错：AttributeError: module 'urllib3.contrib' has no attribute 'pyopenssl'

### ISSUE THREAD

**Issue by Xib1uvXi** [vnpy/vnpy#2845]
## 环境

* 操作系统: Windows 10
* Python版本: VNStudio-2.5.5
* vn.py版本: 2.1.9

## Issue类型
三选一：Bug

## 预期程序行为
正常启动

## 实际程序行为

更新最新版本后，选择火币永续+CTA策略&回测后无法启动VNTrader

![image](https://user-images.githubusercontent.com/13687858/108527431-3a9bf300-730d-11eb-9085-9974519344d1.png)

报错：

```log
Traceback (most recent call last):
  File "d:\vnstudio\lib\site-packages\vnstation\cli.py", line 83, in run_trader
    module = importlib.import_module(d["module"])
  File "d:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\vnstudio\lib\site-packages\vnpy\gateway\huobis\__init__.py", line 1, in <module>
    from .huobis_gateway import HuobisGateway
  File "d:\vnstudio\lib\site-packages\vnpy\gateway\huobis\huobis_gateway.py", line 22, in <module>
    from vnpy.api.rest import RestClient, Request
  File "d:\vnstudio\lib\site-packages\vnpy\api\rest\__init__.py", line 1, in <module>
    from .rest_client import Request, RequestStatus, RestClient
  File "d:\vnstudio\lib\site-packages\vnpy\api\rest\rest_client.py", line 14, in <module>
    requests.packages.urllib3.contrib.pyopenssl.extract_from_urllib3()
AttributeError: module 'urllib3.contrib' has no attribute 'pyopenssl'
```

![image](https://user-images.githubusercontent.com/13687858/108527723-92d2f500-730d-11eb-981c-17dc6cfa6498.png)

**Comment by MrKoooooo** [comment]
这个问题是因为requests 的版本不对导致的，试试安装2.17的版本。我昨晚也遇到同样的问题。。。

**Comment by vnpy** [comment]
新的2.1.9.1更新已修复，请通过VN Station自动更新即可
