### ISSUE TITLE
vntrader 2.1.9 参数优化有bug 超过5个以上条件的参数优化会报错而停下来 剩下的python会一直挂起

### ISSUE THREAD

**Issue by xiecheng7511** [vnpy/vnpy#2847]
## 环境

* 操作系统: 如Windows 10 内存16g
* 数据库为;mongoDB
* Python版本: 如VNStudio-2.1.9
* vn.py版本: VNStudio-2.1.9集成安装版本

## Issue类型
三选一：Bug/

## 预期程序行为
多进程参数优化

## 实际程序行为
多进程参数优化被中止 出现bug

## 重现步骤
参数优化时 选择10个以上的参数以上的参数优化
比如 优化____均线周期.  起始 10 步长 1 终止 20,会报错
优化____均线周期.  起始 15 步长 1 终止 20, 则不会报错 会顺利运行

针对Bug类型Issue，请提供具体重现步骤以及报错截图
Process SpawnPoolWorker-16:
Process SpawnPoolWorker-18:
Process SpawnPoolWorker-22:
Process SpawnPoolWorker-20:
Process SpawnPoolWorker-19:
Process SpawnPoolWorker-14:
Traceback (most recent call last):
  File "G:\vnstudio\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
Process SpawnPoolWorker-13:
  File "G:\vnstudio\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "G:\vnstudio\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
  File "G:\vnstudio\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "G:\vnstudio\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
Process SpawnPoolWorker-23:
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\__init__.py", line 9, in <module>
    from .engine import CtaEngine
  File "G:\vnstudio\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 10, in <module>
    from concurrent.futures import ThreadPoolExecutor
Traceback (most recent call last):
  File "G:\vnstudio\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
  File "G:\vnstudio\lib\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
Process SpawnPoolWorker-17:
  File "G:\vnstudio\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "G:\vnstudio\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "G:\vnstudio\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
Process SpawnPoolWorker-21:
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\__init__.py", line 9, in <module>
    from .engine import CtaEngine
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "G:\vnstudio\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 40, in <module>
    from vnpy.trader.rqdata import rqdata_client
  File "G:\vnstudio\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "G:\vnstudio\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "G:\vnstudio\lib\site-packages\vnpy\trader\rqdata.py", line 6, in <module>
    from rqdatac import init as rqdata_init
  File "G:\vnstudio\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\__init__.py", line 9, in <module>
    from .engine import CtaEngine
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 21, in <module>
    __go()
  File "G:\vnstudio\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
Traceback (most recent call last):
  File "G:\vnstudio\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 40, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 18, in __go
    importlib.import_module(module_name)
  File "G:\vnstudio\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "G:\vnstudio\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "G:\vnstudio\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "G:\vnstudio\lib\site-packages\vnpy\trader\rqdata.py", line 6, in <module>
    from rqdatac import init as rqdata_init
  File "G:\vnstudio\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "G:\vnstudio\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "G:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\__init__.py", line 9, in <module>
    from .engine import CtaEngine
  File "G:\vnstudio\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "G:\vnstudio\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
MemoryError
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 21, in <module>
    __go()
  File "G:\vnstudio\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "G:\vnstudio\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "G:\vnstudio\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 40, in <module>
    from vnpy.trader.rqdata import rqdata_client
  File "G:\vnstudio\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
Traceback (most recent call last):
  File "G:\vnstudio\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 18, in __go
    importlib.import_module(module_name)
  File "G:\vnstudio\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
  File "G:\vnstudio\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "G:\vnstudio\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "G:\vnstudio\lib\site-packages\vnpy\trader\rqdata.py", line 6, in <module>
    from rqdatac import init as rqdata_init
  File "G:\vnstudio\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "G:\vnstudio\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\__init__.py", line 9, in <module>
    from .engine import CtaEngine
  File "G:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\vnstudio\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
Process SpawnPoolWorker-15:
  File "G:\vnstudio\lib\multiprocessing\pool.py", line 110, in worker
  File "G:\vnstudio\lib\multiprocessing\queues.py", line 354, in get
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 21, in <module>
    __go()
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\__init__.py", line 9, in <module>
    from .engine import CtaEngine
  File "G:\vnstudio\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 40, in <module>
    from vnpy.trader.rqdata import rqdata_client
  File "G:\vnstudio\lib\site-packages\rqdatac\services\financial.py", line 12, in <module>
    from sqlalchemy import Column
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\__init__.py", line 9, in <module>
    from .engine import CtaEngine
  File "G:\vnstudio\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\__init__.py", line 6, in <module>
    from vnpy.trader.utility import BarGenerator, ArrayManager
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 18, in __go
    importlib.import_module(module_name)
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 40, in <module>
    from vnpy.trader.rqdata import rqdata_client
  File "G:\vnstudio\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
  File "G:\vnstudio\lib\site-packages\vnpy\trader\rqdata.py", line 6, in <module>
    from rqdatac import init as rqdata_init
  File "G:\vnstudio\lib\site-packages\sqlalchemy\__init__.py", line 10, in <module>
    from .schema import BLANK_SCHEMA  # noqa
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 40, in <module>
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\__init__.py", line 9, in <module>
    from .engine import CtaEngine
  File "G:\vnstudio\lib\site-packages\vnpy\trader\utility.py", line 14, in <module>
    import talib
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "G:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\vnstudio\lib\site-packages\vnpy\trader\rqdata.py", line 6, in <module>
    from rqdatac import init as rqdata_init
  File "G:\vnstudio\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 21, in <module>
    __go()
  File "G:\vnstudio\lib\site-packages\sqlalchemy\schema.py", line 12, in <module>
    from .sql.base import SchemaVisitor  # noqa
  File "G:\vnstudio\lib\site-packages\vnpy\trader\rqdata.py", line 6, in <module>
    from rqdatac import init as rqdata_init
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 40, in <module>
    from vnpy.trader.rqdata import rqdata_client
  File "G:\vnstudio\lib\site-packages\talib\__init__.py", line 43, in <module>
    from ._ta_lib import (
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "G:\vnstudio\lib\site-packages\rqdatac\services\financial.py", line 12, in <module>
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 21, in <module>
    __go()
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\__init__.py", line 9, in <module>
    from .engine import CtaEngine
Traceback (most recent call last):
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 18, in __go
    importlib.import_module(module_name)
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\__init__.py", line 8, in <module>
    from .expression import Alias  # noqa
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 21, in <module>
    __go()
  File "G:\vnstudio\lib\site-packages\vnpy\trader\rqdata.py", line 6, in <module>
    from rqdatac import init as rqdata_init
ImportError: DLL load failed: 页面文件太小，无法完成操作。
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "G:\vnstudio\lib\site-packages\sqlalchemy\__init__.py", line 10, in <module>
    from .schema import BLANK_SCHEMA  # noqa
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 18, in __go
    importlib.import_module(module_name)
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 40, in <module>
  File "G:\vnstudio\lib\multiprocessing\process.py", line 297, in _bootstrap
  File "G:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\expression.py", line 90, in <module>
    from .dml import Delete  # noqa
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 18, in __go
    importlib.import_module(module_name)
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 21, in <module>
    __go()
MemoryError
  File "G:\vnstudio\lib\site-packages\sqlalchemy\schema.py", line 12, in <module>
    from .sql.base import SchemaVisitor  # noqa
  File "G:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\vnstudio\lib\site-packages\vnpy\trader\rqdata.py", line 6, in <module>
    from rqdatac import init as rqdata_init
  File "G:\vnstudio\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "G:\vnstudio\lib\site-packages\rqdatac\services\financial.py", line 12, in <module>
    from sqlalchemy import Column
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\dml.py", line 12, in <module>
    from . import util as sql_util
  File "G:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 18, in __go
    importlib.import_module(module_name)
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\__init__.py", line 106, in <module>
    __go(locals())
  File "G:\vnstudio\lib\site-packages\rqdatac\services\financial.py", line 12, in <module>
    from sqlalchemy import Column
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 21, in <module>
    __go()
  File "G:\vnstudio\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
  File "G:\vnstudio\lib\site-packages\sqlalchemy\__init__.py", line 10, in <module>
    from .schema import BLANK_SCHEMA  # noqa
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\util.py", line 15, in <module>
    from . import operators
  File "G:\vnstudio\lib\site-packages\rqdatac\services\financial.py", line 12, in <module>
    from sqlalchemy import Column
  File "G:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\__init__.py", line 103, in __go
    from . import naming  # noqa
  File "G:\vnstudio\lib\site-packages\sqlalchemy\__init__.py", line 10, in <module>
    from .schema import BLANK_SCHEMA  # noqa
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 18, in __go
    importlib.import_module(module_name)
  File "G:\vnstudio\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "G:\vnstudio\lib\site-packages\sqlalchemy\schema.py", line 12, in <module>
    from .sql.base import SchemaVisitor  # noqa
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "G:\vnstudio\lib\site-packages\sqlalchemy\__init__.py", line 10, in <module>
    from .schema import BLANK_SCHEMA  # noqa
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\naming.py", line 27, in <module>
    from .. import events  # noqa
  File "G:\vnstudio\lib\site-packages\sqlalchemy\schema.py", line 12, in <module>
    from .sql.base import SchemaVisitor  # noqa
  File "G:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\__init__.py", line 9, in <module>
    from .engine import CtaEngine
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\__init__.py", line 8, in <module>
    from .expression import Alias  # noqa
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "G:\vnstudio\lib\site-packages\sqlalchemy\schema.py", line 12, in <module>
    from .sql.base import SchemaVisitor  # noqa
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\__init__.py", line 8, in <module>
    from .expression import Alias  # noqa
  File "G:\vnstudio\lib\site-packages\rqdatac\services\financial.py", line 12, in <module>
    from sqlalchemy import Column
  File "G:\vnstudio\lib\site-packages\vnpy\app\cta_strategy\engine.py", line 40, in <module>
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\expression.py", line 90, in <module>
    from .dml import Delete  # noqa
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\__init__.py", line 8, in <module>
    from .expression import Alias  # noqa
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\expression.py", line 90, in <module>
    from .dml import Delete  # noqa
  File "G:\vnstudio\lib\site-packages\sqlalchemy\__init__.py", line 10, in <module>
    from .schema import BLANK_SCHEMA  # noqa
  File "G:\vnstudio\lib\site-packages\vnpy\trader\rqdata.py", line 6, in <module>
    from rqdatac import init as rqdata_init
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\dml.py", line 12, in <module>
    from . import util as sql_util
  File "<frozen importlib._bootstrap>", line 316, in __enter__
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\expression.py", line 90, in <module>
    from .dml import Delete  # noqa
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\dml.py", line 12, in <module>
    from . import util as sql_util
  File "G:\vnstudio\lib\site-packages\sqlalchemy\schema.py", line 12, in <module>
    from .sql.base import SchemaVisitor  # noqa
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 21, in <module>
    __go()
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\util.py", line 34, in <module>
MemoryError
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\dml.py", line 12, in <module>
    from . import util as sql_util
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\util.py", line 22, in <module>
    from .ddl import sort_tables  # noqa
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\__init__.py", line 8, in <module>
    from .expression import Alias  # noqa
  File "G:\vnstudio\lib\site-packages\rqdatac\__init__.py", line 18, in __go
    importlib.import_module(module_name)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\util.py", line 34, in <module>
    from .schema import Column
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\ddl.py", line 17, in <module>
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\expression.py", line 90, in <module>
    from .dml import Delete  # noqa
  File "G:\vnstudio\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\dml.py", line 12, in <module>
    from . import util as sql_util
  File "G:\vnstudio\lib\site-packages\rqdatac\services\financial.py", line 12, in <module>
    from sqlalchemy import Column
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
MemoryError
MemoryError
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\util.py", line 34, in <module>
    from .schema import Column
  File "G:\vnstudio\lib\site-packages\sqlalchemy\__init__.py", line 10, in <module>
    from .schema import BLANK_SCHEMA  # noqa
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "G:\vnstudio\lib\site-packages\sqlalchemy\schema.py", line 12, in <module>
    from .sql.base import SchemaVisitor  # noqa
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\__init__.py", line 8, in <module>
    from .expression import Alias  # noqa
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\expression.py", line 90, in <module>
    from .dml import Delete  # noqa
MemoryError
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\dml.py", line 12, in <module>
MemoryError
MemoryError
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\util.py", line 22, in <module>
    from .ddl import sort_tables  # noqa
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\ddl.py", line 32, in <module>
  File "G:\vnstudio\lib\site-packages\sqlalchemy\sql\ddl.py", line 106, in DDLElement
    "The :meth:`.DDLElement.execute_at` method is deprecated and will "
  File "G:\vnstudio\lib\site-packages\sqlalchemy\util\deprecations.py", line 85, in decorate
    header,
MemoryError
  File "G:\vnstudio\lib\site-packages\sqlalchemy\util\deprecations.py", line 256, in _decorate_with_warning
    decorated = warned(func)
  File "G:\vnstudio\lib\site-packages\sqlalchemy\util\langhelpers.py", line 152, in decorate
  File "G:\vnstudio\lib\site-packages\sqlalchemy\util\langhelpers.py", line 162, in _exec_code_in_env
    exec(code, env)
MemoryError

**Comment by xiecheng7511** [comment]
使用VNStudio 2.1.2安装的话 多进程参数优化就没有这个问题了.   测试了VNStudio 2.1.5安装的版本一样会出现这个问题 不过这个版本只运行前面 5个python程序 就停止挂起了 也不报错 后面的python优化程序都在挂起 cpu也没动用

**Comment by vnpy** [comment]
MemoryError是指内存不足程序挂了，请提高系统硬件配置，或者缩短优化的时间周期吧
