### ISSUE TITLE
数据管理，删除数据时报错

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2885]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.1.x（下载最新的版本的，1.9之后的克隆的下载）

## Issue类型
三选一：Bug

群主，您好
数据管理，删除数据时报错，错误信息如下：

## 实际程序行为
Traceback (most recent call last):
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 3099, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\app\data_manager\ui\widget.py", line 343, in delete_data
    interval
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\app\data_manager\engine.py", line 167, in delete_bar_data
    interval
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\database\postgresql\postgresql_database.py", line 296, in delete_bar_data
    count = d.execute()
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 1886, in inner
    return method(self, database, *args, **kwargs)
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 1957, in execute
    return self._execute(database)
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 2442, in _execute
    cursor = database.execute(self)
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 3112, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 3106, in execute_sql
    self.commit()
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 2873, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "E:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 3099, in execute_sql
    cursor.execute(sql, params or ())
peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block

**Comment by vnpy** [comment]
已修复，非常感谢
