### ISSUE TITLE
登录ib，退出程序报错：OSError: [WinError 10038] 在一个非套接字上尝试了一个操作

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#2913]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.1.9.x

## Issue类型
三选一：Bug/Question

## 预期程序行为

群主，您好

登录ib后，不做任何操作，退出整个程序，报错，错误信息如下：

unhandled exception in EReader thread
Traceback (most recent call last):
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\ibapi\reader.py", line 34, in run
    data = self.conn.recvMsg()
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\ibapi\connection.py", line 99, in recvMsg
    buf = self._recvAllMsg()
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\ibapi\connection.py", line 119, in _recvAllMsg
    buf = self.socket.recv(4096)
OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。

------------------
以前没碰到过这类问题的，另外在ibapi中也没头绪，恳请您指导下该如何解决这个问题，谢谢！

**Comment by vnpy** [comment]
这个问题来源于IB的Python API底层，在vn.py中无法处理，因为在退出时才会出现，所以忽略即可
