### ISSUE TITLE
influxdb导入数据，"time"字段时间格式不一致，导致取数据时时间解析失败

### ISSUE THREAD

**Issue by missgoon** [vnpy/vnpy#2988]
## 环境

* 操作系统: win10系统
* VN Station2.2版本

## Issue类型
Bug

## 预期程序行为
预期从influxdb数据取出数据的"time"字段时间格式为"%Y-%m-%dT%H:%M:%SZ"

文件：https://github.com/vnpy/vnpy/blob/master/vnpy/database/influxdb/influxdb_database.py
方法：load_tick_data()  
第238行：dt = datetime.strptime(d["time"], "%Y-%m-%dT%H:%M:%SZ") 

## 实际程序行为
取出数据的"time"时间为“2020-01-02T08:59:00.500000Z”

报错信息：
![image](https://user-images.githubusercontent.com/11384969/117912267-c7a18780-b311-11eb-8594-86fac6e87a0e.png)

`Traceback (most recent call last):
  File "D:\programs\JetBrains\PyCharm 2020.3\plugins\python\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\programs\JetBrains\PyCharm 2020.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/projects/vnpy-master/works/generate_bar_data.py", line 49, in <module>
    begin('2020-01-01', '2021-01-01')
  File "D:/projects/vnpy-master/works/generate_bar_data.py", line 35, in begin
    start=begin_datetime, end=end_datetime)
  File "D:\projects\vnpy-master\vnpy\database\influxdb\influxdb_database.py", line 238, in load_tick_data
    dt = datetime.strptime(d["time"], "%Y-%m-%dT%H:%M:%SZ")
  File "D:\programs\Anaconda3\envs\python37\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "D:\programs\Anaconda3\envs\python37\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2020-01-02T08:59:00.500000Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
python-BaseException`

## 重现步骤

调用database_manager.load_tick_data()

针对Bug类型Issue，请提供具体重现步骤以及报错截图

经分析发现是，将数据存入influxdb时，"time"字段的时间格式不一致导致的。具体代码在：
文件：https://github.com/vnpy/vnpy/blob/master/vnpy/database/influxdb/influxdb_database.py
方法：save_tick_data()
第124行： "time": tick.datetime.isoformat(),
这里将 tick.datetime转换为字符串，使用isoformat()。 isoformat()方法有个参数timespec默认为“auto”。
如果timespec参数为“auto”在转换的时候会判断数据是否有毫秒数据，导致最终生成的字符串格式不一致。
如果有毫秒数据字符串格式："%Y-%m-%dT%H:%M:%S.%fZ"
如果没有毫秒数据字符串格式："%Y-%m-%dT%H:%M:%SZ"
![image](https://user-images.githubusercontent.com/11384969/117911842-0a169480-b311-11eb-803b-7df673282066.png)
![image](https://user-images.githubusercontent.com/11384969/117912009-4ea23000-b311-11eb-8b02-39e5d00f5b3c.png)

**Comment by vnpy** [comment]
已修复
