### ISSUE TITLE
Binance现货接口, Deribit 等数字货币接口，对于手动挂的市价止损预埋单等手动挂单会报错

### ISSUE THREAD

**Issue by AITrading2020** [vnpy/vnpy#2998]
## 环境

* 操作系统: 如Windows 10
* Python版本: python3.7
* vn.py版本: 全部版本

## Issue类型
三选一：Bug

## 重现步骤
手动在Binance现货接口, Deribit等数字货币接口挂市价止损预埋单，然后再用vnpy连接该接口时报错。
如果是先登录上的VNPY 接口，然后再手动挂单的话，依然会报该错误。
目前在Binance现货接口 和 Deribit接口都发现了该问题。

以下是Deribit接口的报错：
[2021-05-20T11:11:07.366032]: Unhandled WebSocket Error:<class 'KeyError'>
LastSentText:
{"jsonrpc": "2.0", "id": 4, "method": "public/get_instruments", "params": {"currency": "ETH", "expired": false}}
LastReceivedText:
{"jsonrpc":"2.0","id":2,"error":{"message":"unauthorized","code":13009},"usIn":XXXXXX"usOut":XXXXXX,"usDiff":602,"testnet":false}
Exception trace: 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\vnpy\api\websocket\websocket_client.py", line 216, in _run
    self.on_packet(data)
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\vnpy\gateway\deribit\deribit_gateway.py", line 349, in on_packet
    callback(packet)
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\vnpy\gateway\deribit\deribit_gateway.py", line 360, in on_access_token
    data = packet["result"]
KeyError: 'result'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\vnpy\api\websocket\websocket_client.py", line 216, in _run
    self.on_packet(data)
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\vnpy\gateway\deribit\deribit_gateway.py", line 349, in on_packet
    callback(packet)
  File "C:\ProgramData\Anaconda3\envs\vnpy2.1.8\lib\site-packages\vnpy\gateway\deribit\deribit_gateway.py", line 360, in on_access_token
    data = packet["result"]
KeyError: 'result'

**Comment by AITrading2020** [comment]
Deribit 接口，我发现是有之前的手动交易的持仓的时候，就会报错，不仅仅是有挂止损单的时候。 BINANCE的现货接口是在有手工挂单的时候会报错

**Comment by fengjiansunren** [comment]
什么意思

**Comment by noranhe** [comment]
目前版本的币安现货只支持市价单和市价单，deribit接口只支持市价单、限价单和交易所停止单。支持的订单类型接口文件里的委托类型映射字典里都有写。自己有需求的话请基于接口的API文档进行个性化修改了。deribit报错13009，“unauthorized”，具体原因api文档里有写。如果是实盘账号，请检查一下token或者签名。如果用了测试账号，可能是登陆了实盘环境导致的。之前的版本不支持测试账户，想跑测试账户可以自行拉取vnpy_deribit试试看

**Comment by AITrading2020** [comment]
> 目前版本的币安现货只支持限价单和市价单，deribit接口只支持市价单、限价单和交易所停止单。支持的订单类型接口文件里的委托类型映射字典里都有写。自己有需求的话请基于接口的API文档进行个性化修改了。deribit报错13009，“unauthorized”，具体原因api文档里有写。如果是实盘账号，请检查一下token或者签名。如果用了测试账号，可能是登陆了实盘环境导致的。之前的版本不支持测试账户，想跑测试账户可以自行拉取vnpy_deribit试试看

你好，上述两个问题，我都是在实盘账号中遇到的，我感觉问题是出在了对于“市价预埋单”是否支持的问题上了。 希望对这个“市价预埋单”也进行支持。 现在我发现 币安的USDT永续合约挂了“市价预埋单”再使用api是不会报错的，但是币安币币现货和deribit的期权，挂了“市价预埋单”之后，连接api都会报错的；已经到了api，再手工挂过“市价预埋单”，也会把连接的api卡死的。

**Comment by vnpy** [comment]
1. 币安现货接口问题，已经在vnpy_binance项目中修复，会自动过滤限价和市价以外的委托类型
2. Deribit接口问题，在新的vnpy_deribit中已经修复
