### ISSUE TITLE
关闭程序时报错

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy#3008]
发现一些情况下会导致整个vnpy卡死，比如：
策略发了一个委托，trader拆分成一个平仓，一个开仓。

报错信息：
Exception ignored in: <function BaseMonitor.__del__ at 0x000002C47CF73268>
Traceback (most recent call last):
  File "C:\vnstudio\lib\site-packages\vnpy\trader\ui\widget.py", line 213, in __del__
    self.save_setting()
  File "C:\vnstudio\lib\site-packages\vnpy\trader\ui\widget.py", line 357, in save_setting
    settings.setValue("column_state", self.horizontalHeader().saveState())
RuntimeError: wrapped C/C++ object of type LogMonitor has been deleted
Exception ignored in: <function BaseMonitor.__del__ at 0x000002C47CF73268>
Traceback (most recent call last):
  File "C:\vnstudio\lib\site-packages\vnpy\trader\ui\widget.py", line 213, in __del__
    self.save_setting()
  File "C:\vnstudio\lib\site-packages\vnpy\trader\ui\widget.py", line 357, in save_setting
    settings.setValue("column_state", self.horizontalHeader().saveState())
RuntimeError: wrapped C/C++ object of type StopOrderMonitor has been deleted

两个委托都成交了，时间记录是同一秒完成的

**Comment by vnpy** [comment]
已在vnpy_ctastrategy项目中修复
