### ISSUE TITLE
运行vntrader报错，上周还没问题，今天就不行了 。

### ISSUE THREAD

**Issue by FallacyWalker** [vnpy/vnpy#301]
Ubuntu 16.4 LTS
Python 2.7.12
vnpy version不知道在代码里怎么查看；
已经装好的报错，clone最新版也不行；

walker@ubuntu:/home/Vnpy/vnpy/vn.trader$ python vtMain.py
Traceback (most recent call last):
  File "/home/Vnpy/vnpy/vn.trader/gateway/__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/Vnpy/vnpy/vn.trader/gateway/ctpGateway/__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway as gateway
  File "/home/Vnpy/vnpy/vn.trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnctpmd import MdApi
ImportError: libthostmduserapi.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/Vnpy/vnpy/vn.trader/gateway/__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/Vnpy/vnpy/vn.trader/gateway/ltsGateway/__init__.py", line 4, in <module>
    from ltsGateway import LtsGateway as gateway
  File "/home/Vnpy/vnpy/vn.trader/gateway/ltsGateway/ltsGateway.py", line 10, in <module>
    from vnltsmd import MdApi
ImportError: libsecuritymduserapi.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/Vnpy/vnpy/vn.trader/gateway/__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/Vnpy/vnpy/vn.trader/gateway/qdpGateway/__init__.py", line 4, in <module>
    from qdpGateway import QdpGateway as gateway
  File "/home/Vnpy/vnpy/vn.trader/gateway/qdpGateway/qdpGateway.py", line 16, in <module>
    from vnqdpmd import MdApi
ImportError: No module named vnqdpmd
Traceback (most recent call last):
  File "/home/Vnpy/vnpy/vn.trader/gateway/__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/Vnpy/vnpy/vn.trader/gateway/xspeedGateway/__init__.py", line 4, in <module>
    from xspeedGateway import XspeedGateway as gateway
  File "/home/Vnpy/vnpy/vn.trader/gateway/xspeedGateway/xspeedGateway.py", line 12, in <module>
    from vnxspeedmd import MdApi
ImportError: No module named vnxspeedmd
Traceback (most recent call last):
  File "/home/Vnpy/vnpy/vn.trader/gateway/__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/Vnpy/vnpy/vn.trader/gateway/femasGateway/__init__.py", line 4, in <module>
    from femasGateway import FemasGateway as gateway
  File "/home/Vnpy/vnpy/vn.trader/gateway/femasGateway/femasGateway.py", line 13, in <module>
    from vnfemasmd import MdApi
ImportError: No module named vnfemasmd
请先安装WindPy接口
Traceback (most recent call last):
  File "/home/Vnpy/vnpy/vn.trader/gateway/__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/Vnpy/vnpy/vn.trader/gateway/shzdGateway/__init__.py", line 4, in <module>
    from shzdGateway import ShzdGateway as gateway
  File "/home/Vnpy/vnpy/vn.trader/gateway/shzdGateway/shzdGateway.py", line 18, in <module>
    from vnshzd import ShzdApi
ImportError: No module named vnshzd
Traceback (most recent call last):
  File "/home/Vnpy/vnpy/vn.trader/gateway/__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/Vnpy/vnpy/vn.trader/gateway/ksotpGateway/__init__.py", line 4, in <module>
    from ksotpGateway import KsotpGateway as gateway
  File "/home/Vnpy/vnpy/vn.trader/gateway/ksotpGateway/ksotpGateway.py", line 11, in <module>
    from vnksotpmd import MdApi
ImportError: No module named vnksotpmd
Traceback (most recent call last):
  File "/home/Vnpy/vnpy/vn.trader/gateway/__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/Vnpy/vnpy/vn.trader/gateway/ibGateway/__init__.py", line 4, in <module>
    from ibGateway import IbGateway as gateway
  File "/home/Vnpy/vnpy/vn.trader/gateway/ibGateway/ibGateway.py", line 20, in <module>
    from vnib import *
ImportError: twsapi.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/Vnpy/vnpy/vn.trader/gateway/__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/Vnpy/vnpy/vn.trader/gateway/sgitGateway/__init__.py", line 4, in <module>
    from sgitGateway import SgitGateway as gateway
  File "/home/Vnpy/vnpy/vn.trader/gateway/sgitGateway/sgitGateway.py", line 16, in <module>
    from vnsgitmd import MdApi
ImportError: No module named vnsgitmd
Traceback (most recent call last):
  File "/home/Vnpy/vnpy/vn.trader/gateway/__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/Vnpy/vnpy/vn.trader/gateway/ksgoldGateway/__init__.py", line 4, in <module>
    from ksgoldGateway import KsgoldGateway as gateway
  File "/home/Vnpy/vnpy/vn.trader/gateway/ksgoldGateway/ksgoldGateway.py", line 14, in <module>
    from vnksgoldtd import TdApi
ImportError: No module named vnksgoldtd
Traceback (most recent call last):
  File "vtMain.py", line 9, in <module>
    from vtEngine import MainEngine
  File "/home/Vnpy/vnpy/vn.trader/vtEngine.py", line 17, in <module>
    from dataRecorder.drEngine import DrEngine
  File "/home/Vnpy/vnpy/vn.trader/dataRecorder/drEngine.py", line 21, in <module>
    from language import text
  File "/home/Vnpy/vnpy/vn.trader/dataRecorder/language/__init__.py", line 8, in <module>
    from chinese import text
ImportError: No module named chinese

**Comment by jieyujing** [comment]
把init.py里面的chinese改成Chinese

**Comment by vnpy** [comment]
v1.61已经修复了这个问题

**Comment by FallacyWalker** [comment]
Ubuntu 16.04  LTS
Python 2.7.12
重新clone了1.61,但是在 vnpy/vn.api/vn.ctp/下编译ctp接口的时候，提示Command Not Found;

**Comment by vnpy** [comment]
除了Command Not Found，还有什么其他的信息？你在编译时运行的是

`bash build.sh`

么？

**Comment by FallacyWalker** [comment]
编译ctp接口运行的命令是：
sudo ./build.sh
提示
sudo: ./build.sh : command not found,没别的了；
不加sudo会提示 permission denied;

**Comment by vnpy** [comment]
奇怪，你的vnpy目录放在什么地方了？这个编译操作应该不涉及到需要sudo权限的操作

**Comment by FallacyWalker** [comment]
～/Desktop/VnpyNew/vnpy

**Comment by vnpy** [comment]
你试试bash build.sh运行，看看是哪个操作需要sudo权限？

**Comment by bill816** [comment]
应该是build.sh文件没有可以执行(x)权限问题,使用bash是可以运行，但使用./build.sh必须要有x权限，不然会提示Permission denied
