### ISSUE TITLE
从GitHub Checkout最新的版本,运行vn.trader->vtMain.py 报错

### ISSUE THREAD

**Issue by zhangshuiyong** [vnpy/vnpy#302]
D:\Anaconda2\python.exe E:/vnpy/vn.trader/vtMain.py
Traceback (most recent call last):
  File "E:\vnpy\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "E:\vnpy\vn.trader\gateway\ctpGateway\__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway as gateway
  File "E:\vnpy\vn.trader\gateway\ctpGateway\ctpGateway.py", line 20, in <module>
    from language import text
  File "E:\vnpy\vn.trader\gateway\ctpGateway\language\__init__.py", line 8, in <module>
    from chinese import text
ImportError: No module named chinese
E:\vnpy\vn.trader\gateway\ibGateway\ibGateway.py:20: RuntimeWarning: to-Python converter for class std::vector<class ibapi::shared_ptr<class OrderCondition>,class std::allocator<class ibapi::shared_ptr<class OrderCondition> > > already registered; second conversion method ignored.
  from vnib import *
Traceback (most recent call last):
  File "E:\vnpy\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "E:\vnpy\vn.trader\gateway\ibGateway\__init__.py", line 4, in <module>
    from ibGateway import IbGateway as gateway
  File "E:\vnpy\vn.trader\gateway\ibGateway\ibGateway.py", line 22, in <module>
    from language import text
  File "E:\vnpy\vn.trader\gateway\ibGateway\language\__init__.py", line 8, in <module>
    from chinese import text
ImportError: No module named chinese
Traceback (most recent call last):
  File "E:\vnpy\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "E:\vnpy\vn.trader\gateway\okcoinGateway\__init__.py", line 4, in <module>
    from okcoinGateway import OkcoinGateway as gateway
  File "E:\vnpy\vn.trader\gateway\okcoinGateway\okcoinGateway.py", line 19, in <module>
    import vnokcoin
  File "E:\vnpy\vn.trader\gateway\okcoinGateway\vnokcoin.py", line 9, in <module>
    import websocket
ImportError: No module named websocket
请先安装WindPy接口
Traceback (most recent call last):
  File "E:/vnpy/vn.trader/vtMain.py", line 9, in <module>
    from vtEngine import MainEngine
  File "E:\vnpy\vn.trader\vtEngine.py", line 16, in <module>
    from ctaStrategy.ctaEngine import CtaEngine
  File "E:\vnpy\vn.trader\ctaStrategy\ctaEngine.py", line 28, in <module>
    from strategy import STRATEGY_CLASS
  File "E:\vnpy\vn.trader\ctaStrategy\strategy\__init__.py", line 26, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "E:\vnpy\vn.trader\ctaStrategy\strategy\strategyAtrRsi.py", line 13, in <module>
    import talib
ImportError: No module named talib

**Comment by ideaplat** [comment]
报什么错，就按照要求装一下就可以了

**Comment by zhangshuiyong** [comment]
@ideaplat 报错就是以上阿。是这样的，我能运行没有重构文件夹之前的vn.trader->vtMain.py。但是最新版本就报以上错误。从gitHub中用这个地址https://github.com/vnpy/vnpy.git，checkout下来，运行就报错，以前的不会

**Comment by FallacyWalker** [comment]
我在Ubuntu上也是报错，原来装好的也报，重新clone一个也报，有一条错误是一样的：ImportError: No module named chinese，talib和websocket可以装，这个chinese该怎么装啊？

**Comment by xdemonhx** [comment]
chinese和english都是bug,改为Chinese和English~!
其它那些是一些c++写好的接口没有编译放到gateway文件里面,要编译才可以(其实不管那些也可以打开)

新版本真的好多bug

**Comment by vnpy** [comment]
请直接下载v1.6.1的压缩包，不要采用GIT拉取的模式：https://github.com/vnpy/vnpy/releases/tag/v1.6.1

这次的情况是因为GIT本身的一个BUG：对纯粹文件夹大小写的修改会忽略，修复的版本里，所有的语言文件夹都采用首字母小写的形式chinese和english
