### ISSUE TITLE
数据删除出错，psycopg2.errors.UndefinedTable: 错误:  对于表"t1",丢失FROM子句项

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3027]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.3.0

## Issue类型
三选一：Bug

## 实际程序行为
群主，您好，
删除数据时报错，确定是bug的，请帮忙查看，谢谢！
数据库是：PostgreSQL

信息如下：
Traceback (most recent call last):
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 3143, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.errors.UndefinedTable: 错误:  对于表"t1",丢失FROM子句项
LINE 1: DELETE FROM "dbbardata" WHERE ((("t1"."symbol" = 'cu2107') A...
                                         ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\app\data_manager\ui\widget.py", line 347, in delete_data
    interval
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\app\data_manager\engine.py", line 172, in delete_bar_data
    interval
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\database\postgresql\postgresql_database.py", line 296, in delete_bar_data
    count = d.execute()
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 1906, in inner
    return method(self, database, *args, **kwargs)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 1977, in execute
    return self._execute(database)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 2473, in _execute
    cursor = database.execute(self)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 3156, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 3150, in execute_sql
    self.commit()
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 2916, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\peewee.py", line 3143, in execute_sql
    cursor.execute(sql, params or ())
peewee.ProgrammingError: 错误:  对于表"t1",丢失FROM子句项
LINE 1: DELETE FROM "dbbardata" WHERE ((("t1"."symbol" = 'cu2107') A...
                                         ^

截图如下：
![删除出错](https://user-images.githubusercontent.com/31505150/122496972-3e235a80-d01f-11eb-9d66-b51dfae2a272.png)

**Comment by stone3536** [comment]
用vnpy-2.1.9再次进行了测试，一样的错误的
![2 1 9](https://user-images.githubusercontent.com/31505150/122499585-be4bbf00-d023-11eb-9101-5743f201979a.png)

**Comment by stone3536** [comment]
2.3.0版本，还有错误
1、对于“下载数据”，选择了正确的数据也是无法下载的；
![下载数据出错](https://user-images.githubusercontent.com/31505150/122509367-3de28980-d036-11eb-8665-e00c17b14df3.png)

2、导入数据，按照课程讲的，应该是根据关键字覆盖才对的，但是实际上并不是的（图2），如果换个标的（实际上是没有输入标的名称误操作导入的）导入，实际上都可以导入的，也就说明了前边的根据关键字不是覆盖的错误。（图3）
图 2：
![导入数据出错---1](https://user-images.githubusercontent.com/31505150/122509389-48048800-d036-11eb-9c81-a52701de729c.png)

图 3：
![导入数据出错---2](https://user-images.githubusercontent.com/31505150/122509431-5a7ec180-d036-11eb-81ce-464e9a6d93bc.png)

**Comment by vnpy** [comment]
已修复
