### ISSUE TITLE
K线图打开偶尔报错：does not have a signal with the signature signal_tick(PyQt_PyObject)

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3057]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.3.0

## Issue类型
三选一：Bug

## 重现步骤

群主，您好

盘前打开K线图，有时候报错，盘中打开K线图，碰到报错概率更多，具体报错信息如下，请群主帮忙看下如何对这类错误进行处理，谢谢！

错误一：
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\01_VNPY\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\01_VNPY\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 60, in _run
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 73, in _process
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 73, in <listcomp>
AttributeError: 'ChartWizardWidget' does not have a signal with the signature signal_spread(PyQt_PyObject)

错误二、
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\01_VNPY\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\01_VNPY\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 60, in _run
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 73, in _process
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 73, in <listcomp>
AttributeError: 'ChartWizardWidget' does not have a signal with the signature signal_tick(PyQt_PyObject)

有时候也会报 signal_history 的错误的（这种情况是数据量大的时候出现的），这个错误，我通过在 engine.py 中查询到历史数据后，sleep 5秒后再处理 self.event_engine.put(event) ，目前没再碰到这个错误信息，但是对于 signal_spread 和  signal_tick 却不好处理的，因为盘中是可能重启的，10次大概会有2~3次碰到这类错误的。

对于 signal_spread 和 signal_tick ，我已经将 self.register_event() 调整到 self.init_ui() 之前，但是还是会出错的，目前想不到该如何解决的了。

恳请群主看下vnpy原始版本的该如何优化，谢谢！

**Comment by stone3536** [comment]
尝试在价差窗口打开多个ChartWizardWidget窗口后，在窗口关闭位置最早加了destroy()导致窗口destroy时和event事件又还有的时候paint冲突了。

但是我一直想不通的是打开窗口获取数据初始画图的时候会报错 does not have a signal with the signature signal_history 的错误的，用了sleep（9）解决，但是偶尔还会出来，后来没办法把 self.chart_engine.query_history( 不放在 def new_chart 中放在__init__的最后，目前没再碰到 signal_history  的错误。


目前不知道是不是上边我写的情况导致的“ signal_spread 和 signal_tick ”这个问题。先将问题关闭了。
