### ISSUE TITLE
关掉vnpy时报错：OSError: [WinError 10038] 在一个非套接字上尝试了一个操作

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3059]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.3.0

## Issue类型
三选一：Bug/Question

## 重现步骤

群主，您好

关掉vnpy时报错，这个错误之前提出过，之前的答复是：
这个问题来源于IB的Python API底层，在vn.py中无法处理，因为在退出时才会出现，所以忽略即可

1、请问目前是否有更好的解决方法了？
2、另外请问是否可以在IB的接口中根据message号 10038 屏蔽掉这个错误信息不在cmd窗口中显示出来？ 
3、这个错误，有时候感觉关掉所有程序后，会导致cmd直接卡死的了呢，就是关掉后，这个报错信息出来了，，，然后cmd窗口就卡住了，，，不论怎么敲回车都没任何反应的，，，等10几分钟都是如此的

恳请百忙中帮忙确认下这个问题是否有好的规避掉的方法，谢谢！

错误信息如下：
unhandled exception in EReader thread
Traceback (most recent call last):
  File "D:\01_VNPY\Anaconda3\lib\site-packages\ibapi\reader.py", line 34, in run
    data = self.conn.recvMsg()
  File "D:\01_VNPY\Anaconda3\lib\site-packages\ibapi\connection.py", line 99, in recvMsg
    buf = self._recvAllMsg()
  File "D:\01_VNPY\Anaconda3\lib\site-packages\ibapi\connection.py", line 119, in _recvAllMsg
    buf = self.socket.recv(4096)
OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。

**Comment by vnpy** [comment]
这个我们排查过时IB官方API底层实现的问题，无法在vn.py层修复了，可以升级到最新版试试：

`pip install ibapi --upgrade`

**Comment by stone3536** [comment]
@vnpy 
群主，您好
升级完后报错

2021-08-05 09:42:06,151  INFO: IB TWS连接成功
Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\00_VNPY_2.x\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\00_VNPY_2.x\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\gateway\ib\ib_gateway.py", line 908, in run
    while not self.done and self.isConnected():
AttributeError: 'IbClient' object has no attribute 'done'
