### ISSUE TITLE
2.4.0 行情录制 AttributeError: type object 'DbTickData' has no attribute 'localtime'

### ISSUE THREAD

**Issue by forhonourlx** [vnpy/vnpy#3065]
## 环境
* 操作系统: 如Windows 10
* Python版本: 如VNStudio-2.4.0

## Issue类型
三选一：Bug

## 预期程序行为
行情录制正常

## 实际程序行为
`Traceback (most recent call last):
  File "c:\vnstudio\lib\site-packages\vnpy\app\data_recorder\ui\widget.py", line 155, in process_exception_event
    raise exc_info[1].with_traceback(exc_info[2])
  File "c:\vnstudio\lib\site-packages\vnpy\app\data_recorder\engine.py", line 80, in run
    database_manager.save_tick_data(data)
  File "c:\vnstudio\lib\site-packages\vnpy\database\sqlite\sqlite_database.py", line 203, in save_tick_data
    DbTickData.insert_many(c).on_conflict_replace().execute()
  File "c:\vnstudio\lib\site-packages\peewee.py", line 1907, in inner
    return method(self, database, *args, **kwargs)
  File "c:\vnstudio\lib\site-packages\peewee.py", line 1978, in execute
    return self._execute(database)
  File "c:\vnstudio\lib\site-packages\peewee.py", line 2745, in _execute
    return super(Insert, self)._execute(database)
  File "c:\vnstudio\lib\site-packages\peewee.py", line 2474, in _execute
    cursor = database.execute(self)
  File "c:\vnstudio\lib\site-packages\peewee.py", line 3156, in execute
    sql, params = ctx.sql(query).query()
  File "c:\vnstudio\lib\site-packages\peewee.py", line 613, in sql
    return obj.__sql__(self)
  File "c:\vnstudio\lib\site-packages\peewee.py", line 2730, in __sql__
    self._generate_insert(self._insert, ctx)
  File "c:\vnstudio\lib\site-packages\peewee.py", line 2610, in _generate_insert
    column = getattr(self.table, column)
AttributeError: type object 'DbTickData' has no attribute 'localtime'`

## 重现步骤
 请团队看看怎么修复，感谢！
@vnpy

**Comment by vnpy** [comment]
2.5.0版本已修复
