### ISSUE TITLE
K线图更新报错'MsgCell' does not have a signal with the signature

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3071]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.3.0

## Issue类型
三选一：Bug

## 实际程序行为

群主，您好

使用价差的K线图更新过程中，在盘中报错，价差标的是内外盘的价差，以前报错是 ChartWizardWidget 上没有 signal_spread 或者是 signal_tick的，但是这一次报错是
'MsgCell'的，搜索过 'MsgCell'，没找到对应有用的信息，恳请您百忙中帮忙看下，谢谢！

我觉得这个K线图要测试出来这类错误，需要单价标的（内盘、外盘），价差标的（内盘、内外盘【这个内外盘的一定要有，因为情况特殊的】、外盘）的同时一直挂着图刷的，并且是按照交易时间段一直挂着的，否则仅仅是偶尔测试下根本测试不出来这种错误的。
谢谢！

详细错误信息如下：

2021-07-18 00:59:58,113  INFO: 信息通知，代码：502，内容: Couldn't connect to TWS. Confirm that "Enable ActiveX and Socket EClients"
is enabled and connection port is the same as "Socket Port" on the
TWS "Edit->Global Configuration...->API->Settings" menu. Live Trading ports:
TWS: 7496; IB Gateway: 4001. Simulated Trading ports for new installations
of version 954.1 or newer:  TWS: 7497; IB Gateway: 4002
2021-07-18 00:59:58,114  INFO: IB TWS连接断开
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\01_VNPY\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\01_VNPY\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 60, in _run
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 73, in _process
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 73, in <listcomp>

AttributeError: 'MsgCell' does not have a signal with the signature signal_spread(PyQt_PyObject)

**Comment by stone3536** [comment]
与已经关闭的'BaseCell'的问题类似，目前想不通也找不出来为啥 MsgCell 会和signal_spread相关的，类和对象又不会错乱的......

遍历过 signal_spread 和 MsgCell 的了，没任何关联。

因为之间群主回复了 'BaseCell' 的message了，这个问题也先关闭。
