### ISSUE TITLE
K线图更新报错：AttributeError: 'QMenu' does not have a signal with the signature signal_tick(PyQt_PyObject)

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3075]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.3.0

## Issue类型
三选一：Bug

## 重现步骤

群主，您好

K线图更新过程中（不是退出程序的时候报错，是图正常更新的时候出的错误导致整个程序就停掉了）报错，此种错误，恳请您指导下该如何跟踪？

'QMenu'报这个错误还是第一次。

谢谢！

错误信息如下：

Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\01_VNPY\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\01_VNPY\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 60, in _run
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 73, in _process
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 73, in <listcomp>
AttributeError: 'QMenu' does not have a signal with the signature signal_tick(PyQt_PyObject)

**Comment by stone3536** [comment]
与已经关闭的'BaseCell'的问题类似

我就想不通怎么会和  'QMenu'  扯上关联的了，唉。

这个问题也先关闭。
