### ISSUE TITLE
最新的https://github.com/vnpy/vnpy/releases/tag/v1.6.1还是有如下报错，导致vn.Trader->vtMain.py不能首次运行

### ISSUE THREAD

**Issue by zhangshuiyong** [vnpy/vnpy#308]
最新的https://github.com/vnpy/vnpy/releases/tag/v1.6.1还是有如下报错，导致vn.Trader->vtMain.py不能运行

D:\Anaconda2\python.exe E:/vnpy-1.6.1/vn.trader/vtMain.py
E:\vnpy-1.6.1\vn.trader\gateway\ibGateway\ibGateway.py:20: RuntimeWarning: to-Python converter for class std::vector<class ibapi::shared_ptr<class OrderCondition>,class std::allocator<class ibapi::shared_ptr<class OrderCondition> > > already registered; second conversion method ignored.
  from vnib import *
Traceback (most recent call last):
  File "E:\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "E:\vnpy-1.6.1\vn.trader\gateway\okcoinGateway\__init__.py", line 4, in <module>
    from okcoinGateway import OkcoinGateway as gateway
  File "E:\vnpy-1.6.1\vn.trader\gateway\okcoinGateway\okcoinGateway.py", line 19, in <module>
    import vnokcoin
  File "E:\vnpy-1.6.1\vn.trader\gateway\okcoinGateway\vnokcoin.py", line 9, in <module>
    import websocket
ImportError: No module named websocket
请先安装WindPy接口
Traceback (most recent call last):
  File "E:/vnpy-1.6.1/vn.trader/vtMain.py", line 9, in <module>
    from vtEngine import MainEngine
  File "E:\vnpy-1.6.1\vn.trader\vtEngine.py", line 16, in <module>
    from ctaStrategy.ctaEngine import CtaEngine
  File "E:\vnpy-1.6.1\vn.trader\ctaStrategy\ctaEngine.py", line 28, in <module>
    from strategy import STRATEGY_CLASS
  File "E:\vnpy-1.6.1\vn.trader\ctaStrategy\strategy\__init__.py", line 27, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "E:\vnpy-1.6.1\vn.trader\ctaStrategy\strategy\strategyAtrRsi.py", line 13, in <module>
    import talib
ImportError: No module named talib

解决办法是注释掉，vn.trader->ctaStrategy->strategy->_init_.py。

这里面有个Bug，用户首次使用，就运行出错。
这个Bug的原因是，新版本增加了策略示例，这一点是好的。但是不要将策略实例默认加载到vn.trader。
这会使得vn.trader与策略耦合。
以上bug是因为strategyAtrRsi.py需要安装 talib包，但是用户的python库没有安装talib包，vnpy的最新版本Readme文档也没有对应说明首次运行要安装talib包，这样会导致疑惑！！！
策略是各种各样的，需要的python包也是各种这样。导致vn.trader与各种各样的包耦合！！！

如果想让用户通过默认加载的策略示例了解vnpy的策略运行机制，可以不改变最新版本的代码，但是请更新一下Readme文档。

**Comment by vnpy** [comment]
非常不好意思，这里确实是一个修改时没注意导致的耦合bug，会增加新的异常捕捉来处理这个问题，谢谢

**Comment by vnpy** [comment]
已解决
