### ISSUE TITLE
使用pip install ibapi --upgrade升级ib接口后报错AttributeError: 'IbClient' object has no attribute 'done'

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3086]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.3.0

## Issue类型
三选一：Bug

## 重现步骤

群主，您好

升级ib接口后报错，错误信息如下：

2021-08-05 09:49:28,881  INFO: IB TWS连接成功
<class 'vnpy.gateway.ib.ib_gateway.IbClient'>
Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\00_VNPY_2.x\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\00_VNPY_2.x\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\gateway\ib\ib_gateway.py", line 911, in run
    while not self.done and self.isConnected():
AttributeError: 'IbClient' object has no attribute 'done'

请问此种情况，是否是ib_gateway中属性不对了呢？
恳请指导下该如何处理，谢谢！

**Comment by stone3536** [comment]
含在新的问题中了，关闭此问题。
