### ISSUE TITLE
图形启动报错'BaseCell' does not have a signal with the signature signal_history

### ISSUE THREAD

**Issue by stone3536** [vnpy/vnpy#3089]
## 环境

* 操作系统: 如Windows 10
* vn.py版本: 如v2.3.0

## Issue类型
三选一：Question

## 重现步骤

群主，您好

启动图形的时候报类似这种错误，恳请您指导下这类错误该如何跟踪处理？
实际上BaseCell根本没用到的，但是为啥会报这类错误？【是不是对象错乱了导致的？想不通的呢】
就算ChartWizardWidget用到的三个 signal_tick、signal_spread、signal_history 也是在类中定义的，不应该丢失的呀，

请问如果是单独创建了的 ChartWizardWidget 的对象，那什么情况下会丢失？

另外就是这个对象，是保存在哪个python的缓存对象中？如何判断event到了这个对象或者类（比如我提前记录对象或者类到指定的event字典中，每次都判断这个对象或者类是否有signal_tick属性）的位置判断属性是否存在，通过try... except方式规避掉这种错误发生，否则程序直接异常了的？

恳请百忙中指导下该如何屏蔽掉这种错误或者该如何查询这类错误，谢谢！

错误信息如下：
PS D:\00_VNPY_2.x\trader2.x> python '.\run_current(2.3.0).py'
2021-08-06 09:33:08,420  INFO: IB TWS连接成功
2021-08-06 09:35:04,837  INFO: 当前使用的交易账号为
2021-08-06 09:35:04,839  INFO: 行情服务器连接成功
2021-08-06 09:35:04,840  INFO: 交易服务器连接成功
2021-08-06 09:35:04,840  INFO: 行情服务器登录成功
2021-08-06 09:35:04,841  INFO: 交易服务器授权验证成功
2021-08-06 09:35:04,841  INFO: 交易服务器登录成功
2021-08-06 09:35:04,841  INFO: 结算信息确认成功
2021-08-06 09:35:06,017  INFO: 合约信息查询成功
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\00_VNPY_2.x\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\00_VNPY_2.x\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 64, in _run
    self._process(event)
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 77, in _process
    [handler(event) for handler in self._handlers[event.type]]
  File "D:\00_VNPY_2.x\Anaconda3\lib\site-packages\vnpy\event\engine.py", line 77, in <listcomp>
    [handler(event) for handler in self._handlers[event.type]]
AttributeError: 'BaseCell' does not have a signal with the signature signal_history(PyQt_PyObject)

**Comment by vnpy** [comment]
这个报错是因为错误的将某个单元格对象，用作了想要绑定signal的图表对象，请自行排查代码了。

**Comment by stone3536** [comment]
这个，真的是没有用到 BaseCell 和 signal_history的，包括继承的。遍历搜索过的了，每一个都仔细看过的了。

**Comment by stone3536** [comment]
遍历搜索过了BaseCell ，也同时遍历搜索过了signal_history。
这个错误，是2个月来第一次出现的，也是醉了怎么会报这个错误的。
