### ISSUE TITLE
rqdata升级导致下载数据报错

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy#3105]
rqdatac版本大于2.9.35下载数据会报错，报错信息如下：

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\envs\py37_vnpy\lib\site-packages\vnpy_ctabacktester\engine.py", line 401, in run_downloading
data = rqdata_client.query_history(req)
File "D:\myproject\vnpy\vnpy-master\vnpy\trader\rqdata.py", line 182, in query_history
dt = row.name.to_pydatetime() - adjustment
AttributeError: 'tuple' object has no attribute 'to_pydatetime'

2.4.0的rqdatac版本是2.9.33，get_price函数返回的df如下图所示：
![9720c9852d3b8b0a5e2c566eaa0134d](https://user-images.githubusercontent.com/63988546/129310234-45195cad-96bc-4f14-ad09-02fc49c8dc19.png)
最新的rqdatac的get_price函数返回的df如下图所示:
![fdcf5541e1065aad2ff9847a5ca15d9](https://user-images.githubusercontent.com/63988546/129310266-42b01be9-84a2-4a57-9a1a-ec4110ef34d8.png)

**Comment by vnpy** [comment]
已添加开发计划
