### ISSUE TITLE
vnpy2.5.0版本 binance不能用了

### ISSUE THREAD

**Issue by fulaoban** [vnpy/vnpy#3130]
vnpy2.5.0版本 binance不能用了

**Comment by vnpy** [comment]
具体报错是？

**Comment by Nimloth1** [comment]
同样不能用，报错如下：
环境
vn.py版本: v2.5.0
Issue类型
三选一：Bug

重现步骤
说明：我在\Anaconda3\Lib\site-packages\vnpy_rest\rest_client.py add_request中增加了print(request.__dict__)，打印了下request

命令行窗口：
{'method': 'GET', 'path': '/api/v3/time', 'callback': <bound method BinanceSpotRestAPi.on_query_time of <vnpy_binance.binance_spot_gateway.BinanceSpotRestAPi object at 0x000001B4DA182460>>, 'params': None, 'data': {'security': <Security.NONE: 0>}, 'headers': None, 'on_failed': None, 'on_error': None, 'extra': None, 'response': None}
2021-09-04 22:28:06,880  INFO: REST API启动成功
RestClient on error----------
[2021-09-04T22:28:06.912093]: Unhandled RestClient Error:<class 'aiohttp.client_exceptions.ClientConnectorError'>
request:request : GET /api/v3/time because terminated: 
headers: None
params: None
data: None
response:

Exception trace: 
Traceback (most recent call last):
  File "D:\Programming\Anaconda3\lib\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "D:\Programming\Anaconda3\lib\asyncio\base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "D:\Programming\Anaconda3\lib\asyncio\base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "D:\Programming\Anaconda3\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "D:\Programming\Anaconda3\lib\asyncio\windows_events.py", line 525, in send
    self._register_with_iocp(conn)
  File "D:\Programming\Anaconda3\lib\asyncio\windows_events.py", line 714, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] 参数错误。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Programming\Anaconda3\lib\site-packages\vnpy_rest\rest_client.py", line 257, in _process_request
    response: Response = await self._get_response(request)
  File "D:\Programming\Anaconda3\lib\site-packages\vnpy_rest\rest_client.py", line 239, in _get_response
    cr: ClientResponse = await self.session.request(
  File "D:\Programming\Anaconda3\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "D:\Programming\Anaconda3\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\Programming\Anaconda3\lib\site-packages\aiohttp\connector.py", line 890, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "D:\Programming\Anaconda3\lib\site-packages\aiohttp\connector.py", line 1139, in _create_proxy_connection
    transport, proto = await self._wrap_create_connection(
  File "D:\Programming\Anaconda3\lib\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.binance.com:443 ssl:default [参数错误。]

代理：127.0.0.1: 7890，用的是clash for windows，安装了Tap网卡。
是不是aiohttp不支持https proxy? [https://github.com/aio-libs/aiohttp/issues/2245]

**Comment by noranhe** [comment]
如果是https proxy支持的问题，可以把trust_env=True传入ClientSession试试

**Comment by vnpy** [comment]
我们官方支持的是Shadowsocks和Trojan两款，Clash没有测试过，不推荐了。
