### ISSUE TITLE
ImportError: No module named chinese

### ISSUE THREAD

**Issue by wangzhe3224** [vnpy/vnpy#314]
请加一下大家，这是为啥？Ubuntu似乎没这个问题呢？谢谢大家

环境：win7 64, 32 bit python

Traceback (most recent call last):
  File "D:\vnpy\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\vnpy\vn.trader\gateway\ctpGateway\__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway as gateway
  File "D:\vnpy\vn.trader\gateway\ctpGateway\ctpGateway.py", line 20, in <module>
    from language import text
  File "D:\vnpy\vn.trader\gateway\ctpGateway\language\__init__.py", line 8, in <module>
    from chinese import text
ImportError: No module named chinese

**Comment by wangzhe3224** [comment]
放在C盘没事儿了。。。

**Comment by linshilogin** [comment]
请问下，这问题，只能是放c盘么。我刚刚也是用spyder运行自带的示例cta，结果也出现这个类似问题。难道是他的程序下下来自己的示例都无法运行么
