### ISSUE TITLE
最新的1.6.1包，菜单没有Ctp选项，DLL load failed，global name 'w' is not defined

### ISSUE THREAD

**Issue by nickChenyx** [vnpy/vnpy#317]
部署环境：
- window7 
- Anaconda2 4.0.0 32bit
- python 2.7.11

菜单内 **没有ctp选项**，下面是CTP_connect的设置  
```javascript
{
    "brokerID": "9999", 
    "tdAddress": "tcp://180.168.146.187:10030", 
    "password": "*******", 
    "mdAddress": "tcp://180.168.146.187:10031", 
    "userID": "*****"
}
```

执行 vtMain之后的错误信息
```
λ  python .\vtMain.py
Traceback (most recent call last):
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\ctpGateway\__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway as gateway
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\ctpGateway\ctpGateway.py", line 16, in <module>
    from vnctpmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。
Traceback (most recent call last):
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\femasGateway\__init__.py", line 4, in <module>
    from femasGateway import FemasGateway as gateway
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\femasGateway\femasGateway.py", line 13, in <module>
    from vnfemasmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。
Traceback (most recent call last):
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\ibGateway\__init__.py", line 4, in <module>
    from ibGateway import IbGateway as gateway
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\ibGateway\ibGateway.py", line 20, in <module>
    from vnib import *
ImportError: DLL load failed: 找不到指定的模块。
Traceback (most recent call last):
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\ksgoldGateway\__init__.py", line 4, in <module>
    from ksgoldGateway import KsgoldGateway as gateway
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\ksgoldGateway\ksgoldGateway.py", line 14, in <module>
    from vnksgoldtd import TdApi
ImportError: DLL load failed: 找不到指定的模块。
Traceback (most recent call last):
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\ksotpGateway\__init__.py", line 4, in <module>
    from ksotpGateway import KsotpGateway as gateway
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\ksotpGateway\ksotpGateway.py", line 11, in <module>
    from vnksotpmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。
Traceback (most recent call last):
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\ltsGateway\__init__.py", line 4, in <module>
    from ltsGateway import LtsGateway as gateway
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\ltsGateway\ltsGateway.py", line 10, in <module>
    from vnltsmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。
Traceback (most recent call last):
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\okcoinGateway\__init__.py", line 4, in <module>
    from okcoinGateway import OkcoinGateway as gateway
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\okcoinGateway\okcoinGateway.py", line 19, in <module>
    import vnokcoin
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\okcoinGateway\vnokcoin.py", line 9, in <module>
    import websocket
ImportError: No module named websocket
Traceback (most recent call last):
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\qdpGateway\__init__.py", line 4, in <module>
    from qdpGateway import QdpGateway as gateway
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\qdpGateway\qdpGateway.py", line 16, in <module>
    from vnqdpmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。
Traceback (most recent call last):
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\sgitGateway\__init__.py", line 4, in <module>
    from sgitGateway import SgitGateway as gateway
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\sgitGateway\sgitGateway.py", line 16, in <module>
    from vnsgitmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。
Traceback (most recent call last):
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\shzdGateway\__init__.py", line 4, in <module>
    from shzdGateway import ShzdGateway as gateway
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\shzdGateway\shzdGateway.py", line 18, in <module>
    from vnshzd import ShzdApi
ImportError: DLL load failed: 找不到指定的模块。
请先安装WindPy接口
Traceback (most recent call last):
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\__init__.py", line 30, in <module>
    module = importlib.import_module(moduleName)
  File "D:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\xspeedGateway\__init__.py", line 4, in <module>
    from xspeedGateway import XspeedGateway as gateway
  File "C:\vnpy\vnpy-1.6.1\vnpy-1.6.1\vn.trader\gateway\xspeedGateway\xspeedGateway.py", line 12, in <module>
    from vnxspeedmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。
global name 'w' is not defined
```

**Comment by nickChenyx** [comment]
**请求回复( ⊙ o ⊙ )啊！ 这个问题不知道该怎么解决，环境重新弄过两三次了，一样的问题**

**Comment by vnpy** [comment]
vcredist x86 x64装了么

**Comment by nickChenyx** [comment]
参照 [wiki 里的 windows 安装流程都装了](https://github.com/vnpy/vnpy/wiki/Windows%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85)  版本也都和wiki里一致。还有可能是什么别的问题吗？

**Comment by vnpy** [comment]
你电脑上装了多个Python环境吗？在cmd里输入python运行，然后看看进入Python后的头内容输出是什么

**Comment by nickChenyx** [comment]
多个是多个 2.7.13 | 2.7.10 | 3.5 | 3.6 ，但是我改过环境变量了。现在的输出是
```
Python 2.7.13 |Anaconda custom (32-bit)| (default, Dec 19 2016, 13:36:02)
```

**Comment by vnpy** [comment]
我猜是这个问题。。。试试全部删了只留一个2.7.13

**Comment by nickChenyx** [comment]
@vnpy  找到问题了... 虽然有新的问题  

我找资料发现有人提到了 **depends22** 这个工具，可以查看dll的相关引用是否完整，然后... 我找到了！！！

> msvcr120.dll 和 msvcp120.dll 

少了这两个dll，然后去下载了，放到 vnctpmd.pyd 被引用的地方！！！ 成功了！！！ 现在接口已经连上了。

新的问题，为什么连上之后，行情并没有出现？ 日志显示行情和交易服务器都连接且登录完成，结算信息确认完成，交易合约信息获取完成。并且账户一栏也显示了我的可用金额，在simnow上注册申请的100W。  

连接的信息是（[simnbow上](http://simnow.sfit.com.cn/product.action) 其他几组也试了...没有行情信息，现在时间是2017年4月28日17:44:29）：
```
{
    "brokerID": "9999", 
    "tdAddress": "tcp://180.168.146.187:10030", 
    "password": "*******", 
    "mdAddress": "tcp://180.168.146.187:10031", 
    "userID": "*****"
}
```

**Comment by sty0719** [comment]
跟楼主一样的问题，4月28日下载的1.6.1包，目前有两个import error：
from vnsgitmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。
from vnshzd import ShzdApi
ImportError: DLL load failed: 找不到指定的模块。

在新电脑上装的，没有多个python环境的问题。期待解决方案。

**Comment by kingmo888** [comment]
@nickChenyx  w实际上是wind终端的一个python接口模块，你用不到可以忽略这个。
