### ISSUE TITLE
vnpy-3.0.0无法启动

### ISSUE THREAD

**Issue by ZzAllenZz** [vnpy/vnpy#3247]
## 环境

* 操作系统: macos
* Python版本: 3.7
* VeighNa版本: v3.0.0发行版

## Issue类型
Bug

## 预期程序行为
样例启动成功
```
python run.py
```

## 实际程序行为
装包脚本运行成功 `bash install_osx.sh`
```
Successfully built vnpy
Installing collected packages: vnpy
Successfully installed vnpy-3.0.0
```
**样例启动失败**
```
python run.py
```
```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from vnpy.trader.ui import MainWindow, create_qapp
  File "/Users/xxx/PycharmProjects/vnpy/vnpy-master-github/vnpy/trader/ui/__init__.py", line 1, in <module>
    from .qt import QtCore, QtWidgets, QtGui, Qt, create_qapp
  File "/Users/xxx/PycharmProjects/vnpy/vnpy-master-github/vnpy/trader/ui/qt.py", line 9, in <module>
    from PySide6 import QtGui, QtWidgets, QtCore
ImportError: could not import module 'PySide6.QtCore'

```
PySide6.QtCore模块无法导入，执行`pip install PySide6 --upgrade` 仍然无效

**Comment by vnpy** [comment]
@Edanflame

**Comment by Edanflame** [comment]
在MacOS下尝试了多个版本的python和PySide6之间的兼容性。在python3.7下运行安装PySide6 6.23或者6.22.1，都会产生异常symbol not found in flat namespace '_PyIndex_Check'。原因可能和MacOS最近较大内容升级以及PySide6的.so文件的编译有关。在python3.8以及之后的版本则不会出现此问题，建议升级python版本。

**Comment by ZzAllenZz** [comment]
使用python3.8 并运行install_osx.sh成功
```
Successfully installed vnpy-3.0.0

```
```
Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
但运行run.py仍报错
```
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from vnpy_ctastrategy import CtaStrategyApp
ModuleNotFoundError: No module named 'vnpy_ctastrategy'

```
请求帮助

**Comment by ZzAllenZz** [comment]
是否需要修改 `Preferences | Project: vnpy-master-github | Project Structure`中的source之类？

**Comment by Edanflame** [comment]
可以查看一下vnpy_ctastrategy的版本，1.0.8版本的是适配vnpy-3.0.0的
