### ISSUE TITLE
python run.py无法启动

### ISSUE THREAD

**Issue by xinmans** [vnpy/vnpy#3291]
## 环境

* 操作系统: 如Windows 10
* Python版本: 如VeighNa Studio-2.9.0
* VeighNa版本: 
veighna_studio-3.0.0.exe
python3.10.0
vnpy-3.0.0
## Issue类型
三选一：Bug

## 实际程序行为

C:\Users\xinmans\Desktop\vnpy-3.0.0\examples\vn_trader>python run.py
Traceback (most recent call last):
  File "C:\Users\xinmans\Desktop\vnpy-3.0.0\examples\vn_trader\run.py", line 31, in <module>
    from vnpy_optionmaster import OptionMasterApp
  File "C:\Users\xinmans\AppData\Local\Programs\Python\Python310\lib\site-packages\vnpy_optionmaster\__init__.py", line 26, in <module>
    from .engine import OptionEngine, APP_NAME
  File "C:\Users\xinmans\AppData\Local\Programs\Python\Python310\lib\site-packages\vnpy_optionmaster\engine.py", line 34, in <module>
    from .pricing import binomial_tree_cython as binomial_tree
  File "binomial_tree_cython.pyx", line 1, in init binomial_tree_cython
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
numpy版本太低了，升级下吧：

`pip install numpy --upgrade`
