### ISSUE TITLE
run.py 启动不成功

### ISSUE THREAD

**Issue by zhicai2049** [vnpy/vnpy#3311]
## 环境

* 操作系统: 如Windows 10
* Python版本: Python3.9
* VeighNa版本: 如v3.1.0

## Issue类型
三选一：Bug

## 预期程序行为
运行veighna_trader包里的run.py，启动成功

## 实际程序行为
报错如下：
D:\datascience\anaconda3\python.exe E:/AAAAAQuant/vnpy/examples/veighna_trader/run.py
Traceback (most recent call last):
  File "E:\AAAAAQuant\vnpy\examples\veighna_trader\run.py", line 31, in <module>
    from vnpy_optionmaster import OptionMasterApp
  File "D:\datascience\anaconda3\lib\site-packages\vnpy_optionmaster\__init__.py", line 26, in <module>
    from .engine import OptionEngine, APP_NAME
  File "D:\datascience\anaconda3\lib\site-packages\vnpy_optionmaster\engine.py", line 22, in <module>
    from .base import (
  File "D:\datascience\anaconda3\lib\site-packages\vnpy_optionmaster\base.py", line 13, in <module>
    from .time import calculate_days_to_expiry, ANNUAL_DAYS
  File "D:\datascience\anaconda3\lib\site-packages\vnpy_optionmaster\time.py", line 9, in <module>
    holidays: list = [x.to_pydatetime() for x in cn_calendar.precomputed_holidays]
TypeError: 'method' object is not iterable

Process finished with exit code 1

## 重现步骤

运行python run.py就出现

**Comment by vnpy** [comment]
pip install exchange_calendars==3.6.3
