### ISSUE TITLE
cannot import name 'ZoneInfo'

### ISSUE THREAD

**Issue by jingcheng407** [vnpy/vnpy#3322]
## 环境

* 操作系统: macOS m1 
* Python版本: 3.10

## Issue类型
Question

## 预期程序行为
用的这个示例代码
```
from vnpy.event import EventEngine
from vnpy.trader.engine import MainEngine
from vnpy.trader.ui import MainWindow, create_qapp

from vnpy_ctp import CtpGateway
from vnpy_ctastrategy import CtaStrategyApp
from vnpy_ctabacktester import CtaBacktesterApp


def main():
    """Start VeighNa Trader"""
    qapp = create_qapp()

    event_engine = EventEngine()
    main_engine = MainEngine(event_engine)
    
    main_engine.add_gateway(CtpGateway)
    main_engine.add_app(CtaStrategyApp)
    main_engine.add_app(CtaBacktesterApp)

    main_window = MainWindow(main_engine, event_engine)
    main_window.showMaximized()

    qapp.exec()


if __name__ == "__main__":
    main()
```
## 实际程序行为
```
Traceback (most recent call last):
  File "/Users/jingcheng407/git/vnpy/run_ui.py", line 5, in <module>
    from vnpy_ctp import CtpGateway
  File "/Users/jingcheng407/miniconda3/envs/vnpy/lib/python3.10/site-packages/vnpy_ctp/__init__.py", line 26, in <module>
    from .gateway import CtpGateway
  File "/Users/jingcheng407/miniconda3/envs/vnpy/lib/python3.10/site-packages/vnpy_ctp/gateway/__init__.py", line 1, in <module>
    from .ctp_gateway import CtpGateway
  File "/Users/jingcheng407/miniconda3/envs/vnpy/lib/python3.10/site-packages/vnpy_ctp/gateway/ctp_gateway.py", line 29, in <module>
    from vnpy.trader.utility import get_folder_path, ZoneInfo
ImportError: cannot import name 'ZoneInfo' from 'vnpy.trader.utility' (/Users/jingcheng407/git/vnpy/vnpy/trader/utility.py)

```
请问这是怎么回事,我看utility.py里面也没有定义ZoneInfo呢

**Comment by vnpy** [comment]
1. MAC用不了CTP接口
2. 最新版本6.6.7.0的vnpy_ctp需要依赖接下来发布的3.3.0的VeighNa核心
