### ISSUE TITLE
engine.run_ga_optimization 中出现 randrange() (1,1,0) 的错误

### ISSUE THREAD

**Issue by laowalter** [vnpy/vnpy#3370]
## 环境

* 操作系统: Linux
* Python版本: python 3.10.8
* vnpy
```
git log 
commit 73121f8c23a3c61e17ee04788cd0b5c37c09af86 (HEAD -> master, origin/master, origin/HEAD)
Author: vn.py <xiaoyou.chen@foxmail.com>
Date:   Tue Nov 1 11:33:43 2022 +0800
```
## Issue类型
Bug

## 预期程序行为
正常回测

## 实际程序行为
回测过程中断

## 重现步骤

只在遗传回测过程中反复出现，在：

 回测代买段:

```
setting = OptimizationSetting()
setting.set_target("sharpe_ratio")
setting.add_parameter('cci_A_low_edge', -150.0, -170.0, 10)
results = engine.run_ga_optimization(setting)
```

针对Bug类型Issue，请提供具体重现步骤以及报错截图

```
2022-11-28 21:31:31.268285      逐日盯市盈亏计算完成
2022-11-28 21:31:31.268858      开始计算策略统计指标
2022-11-28 21:31:31.288883      逐日盯市盈亏计算完成
2022-11-28 21:31:31.289548      开始计算策略统计指标
2022-11-28 21:31:31.294132      策略统计指标计算完成
2022-11-28 21:31:31.320316      策略统计指标计算完成
2022-11-28 21:31:31.322705      策略统计指标计算完成
2022-11-28 21:31:31.334032      策略统计指标计算完成
Traceback (most recent call last):
  File "/home/quant/work/backtest/./cci_walter_backtest.py", line 65, in <module>
    main()
  File "/home/quant/work/backtest/./cci_walter_backtest.py", line 50, in main
    results = engine.run_ga_optimization(setting)
  File "/home/quant/.virtualenvs/quant/lib/python3.10/site-packages/vnpy_ctastrategy/backtesting.py", line 564, in run_ga_optimization
    results: list = run_ga_optimization(
  File "/home/quant/.virtualenvs/quant/lib/python3.10/site-packages/vnpy/trader/optimize.py", line 194, in run_ga_optimization
    algorithms.eaMuPlusLambda(
  File "/home/quant/.virtualenvs/quant/lib/python3.10/site-packages/deap/algorithms.py", line 316, in eaMuPlusLambda
    offspring = varOr(population, toolbox, lambda_, cxpb, mutpb)
  File "/home/quant/.virtualenvs/quant/lib/python3.10/site-packages/deap/algorithms.py", line 234, in varOr
    ind1, ind2 = toolbox.mate(ind1, ind2)
  File "/home/quant/.virtualenvs/quant/lib/python3.10/site-packages/deap/tools/crossover.py", line 49, in cxTwoPoint
    cxpoint1 = random.randint(1, size)
  File "/usr/lib/python3.10/random.py", line 370, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.10/random.py", line 353, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1, 1, 0)
```

**Comment by noranhe** [comment]
遗传算法要最少两个参数才能生成样本空间的
