### ISSUE TITLE
窗口大部分功能不可用

### ISSUE THREAD

**Issue by haisheng666** [vnpy/vnpy#3391]
## 环境

* 操作系统: Ubuntu 22.04
* Python版本: python3.9
* VeighNa版本: 如v3.5

## Issue类型
三选一：Bug,点击CTP 策略就这样报错了,还有窗口的其他很多功能都报错

## 预期程序行为

Traceback (most recent call last):
  File "/home/lhs/PycharmProjects/quantitative_transaction/vnpy_project/vnpy/trader/ui/mainwindow.py", line 276, in open_widget
    widget = widget_class(self.main_engine, self.event_engine)
  File "/home/lhs/PycharmProjects/quantitative_transaction/vnpy_project/vnpy_ctastrategy/ui/widget.py", line 41, in __init__
    self.cta_engine.init_engine()
  File "/home/lhs/PycharmProjects/quantitative_transaction/vnpy_project/vnpy_ctastrategy/engine.py", line 102, in init_engine
    self.init_datafeed()
  File "/home/lhs/PycharmProjects/quantitative_transaction/vnpy_project/vnpy_ctastrategy/engine.py", line 123, in init_datafeed
    result: bool = self.datafeed.init(self.write_log)
TypeError: init() takes 1 positional argument but 2 were given

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
Github上的仓库属于开发中代码，请通过pip进行安装最近的发行版本即可。

**Comment by haisheng666** [comment]
我就是pip安装的啊!不要关闭问题,还没有回答完呢!

**Comment by vnpy** [comment]
`result: bool = self.datafeed.init(self.write_log)`

该修改尚未发布Release版本到PyPI上，请检查下pip下载来源。

**Comment by haisheng666** [comment]
好吧！安装一下以前的版本即可吧？
