### ISSUE TITLE
Mac系统运行vnpy3.6，接入CTP，报错

### ISSUE THREAD

**Issue by gscool** [vnpy/vnpy#3402]
## 环境

* 操作系统: MacOS 13.2.1 
* Python版本:3.10.9
* VeighNa版本: 3.6.0

noui方式启动，会报如下错误
Traceback (most recent call last):
  File "/Users/gsc/mywork/vnpy-office/noui_run.py", line 11, in <module>
    from vnpy_ctp import CtpGateway
  File "/Users/gsc/miniconda3/envs/vnpy/lib/python3.10/site-packages/vnpy_ctp/__init__.py", line 26, in <module>
    from .gateway import CtpGateway
  File "/Users/gsc/miniconda3/envs/vnpy/lib/python3.10/site-packages/vnpy_ctp/gateway/__init__.py", line 1, in <module>
    from .ctp_gateway import CtpGateway
  File "/Users/gsc/miniconda3/envs/vnpy/lib/python3.10/site-packages/vnpy_ctp/gateway/ctp_gateway.py", line 32, in <module>
    from ..api import (
  File "/Users/gsc/miniconda3/envs/vnpy/lib/python3.10/site-packages/vnpy_ctp/api/__init__.py", line 1, in <module>
    from .vnctpmd import MdApi
ImportError: dlopen(/Users/gsc/miniconda3/envs/vnpy/lib/python3.10/site-packages/vnpy_ctp/api/vnctpmd.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_iconv'

带ui启动，则正常，能登录ctp交易

**Comment by jieyujing** [comment]
同样遇到这样的问题：
`Traceback (most recent call last):
  File "/Users/link/Documents/quantopy/run_Gui.py", line 7, in <module>
    from vnpy_ctp import CtpGateway
  File "/Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/__init__.py", line 26, in <module>
    from .gateway import CtpGateway
  File "/Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/gateway/__init__.py", line 1, in <module>
    from .ctp_gateway import CtpGateway
  File "/Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/gateway/ctp_gateway.py", line 32, in <module>
    from ..api import (
  File "/Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/api/__init__.py", line 1, in <module>
    from .vnctpmd import MdApi
ImportError: dlopen(/Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/api/vnctpmd.cpython-39-darwin.so, 2): Symbol not found: _libiconv
  Referenced from: /Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/api/vnctpmd.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/api/vnctpmd.cpython-39-darwin.so
`

**Comment by vnpy** [comment]
目前看遇到报错的用户反馈，都和Anaconda环境（或者Minicodna）有关，由于Anaconda本身带有比较复杂的环境激活机制，所以这块很难定位具体问题。

建议在下述环境中进行安装尝试：
1. 卸载Anaconda（或者从Path环境变量中移除）
2. 安装Python官方提供的【3.10版本】解释器（注意根据芯片选择Arm/Intel）
3. 安装XCode编译器的最新版本
4. 再参考之前的公众号文章教程，跟随步骤安装VeighNa

**Comment by vnpy** [comment]
找到网上两个相关资料：

1. 由于系统中存在多个libiconv库，导致编译链接的版本和实际加载的版本不一致，解决方法是删掉其中的某个：https://www.jianshu.com/p/4af8f64e208f
2. 由于setup.py运行C++编译时，没有指定加载iconv库，需要在libraries参数中指定：https://stackoverflow.com/questions/5467612/pyspatialite-symbol-not-found-for-iconv

**Comment by gscool** [comment]
不用miniconda，换了virtualenv来管理虚拟环境，可以了。

**Comment by hc1985313** [comment]
> 同样遇到这样的问题： `Traceback (most recent call last): File "/Users/link/Documents/quantopy/run_Gui.py", line 7, in <module> from vnpy_ctp import CtpGateway File "/Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/__init__.py", line 26, in <module> from .gateway import CtpGateway File "/Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/gateway/__init__.py", line 1, in <module> from .ctp_gateway import CtpGateway File "/Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/gateway/ctp_gateway.py", line 32, in <module> from ..api import ( File "/Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/api/__init__.py", line 1, in <module> from .vnctpmd import MdApi ImportError: dlopen(/Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/api/vnctpmd.cpython-39-darwin.so, 2): Symbol not found: _libiconv Referenced from: /Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/api/vnctpmd.cpython-39-darwin.so Expected in: flat namespace in /Users/link/anaconda3/lib/python3.9/site-packages/vnpy_ctp/api/vnctpmd.cpython-39-darwin.so `

请问大神解决了吗》？
