### ISSUE TITLE
vntrader app:  'PySide6.QtWidgets.QDockWidget' object has no attribute 'DockWidgetFloatable'.

### ISSUE THREAD

**Issue by cloudseasail** [vnpy/vnpy#3405]
## 环境

* 操作系统: Deepin Linux (Debian)
* Python版本: Python 3.10.6
* VeighNa版本: vnpy 3.6.0
* pyside6 6.4.2
* 

## Issue类型
Bug

## 预期程序行为
```
def main():
    """"""
    qapp = create_qapp()

    event_engine = EventEngine()

    main_engine = MainEngine(event_engine)

    main_engine.add_gateway(CtpGateway)

    main_window = MainWindow(main_engine, event_engine)
    main_window.showMaximized()

    qapp.exec()

```

## 实际程序行为
```
Traceback (most recent call last):
  File "/home/william/Workspace/Quant/fquant_vnpy/tool/vntrader_app.py", line 110, in <module>
    main()
  File "/home/william/Workspace/Quant/fquant_vnpy/tool/vntrader_app.py", line 103, in main
    main_window = MainWindow(main_engine, event_engine)
  File "/home/william/miniconda3/lib/python3.10/site-packages/vnpy/trader/ui/mainwindow.py", line 51, in __init__
    self.init_ui()
  File "/home/william/miniconda3/lib/python3.10/site-packages/vnpy/trader/ui/mainwindow.py", line 56, in init_ui
    self.init_dock()
  File "/home/william/miniconda3/lib/python3.10/site-packages/vnpy/trader/ui/mainwindow.py", line 63, in init_dock
    self.trading_widget, trading_dock = self.create_dock(
  File "/home/william/miniconda3/lib/python3.10/site-packages/vnpy/trader/ui/mainwindow.py", line 232, in create_dock
    dock.setFeatures(dock.DockWidgetFloatable | dock.DockWidgetMovable)
AttributeError: 'PySide6.QtWidgets.QDockWidget' object has no attribute 'DockWidgetFloatable'. Did you mean: 'DockWidgetFeature'?
```

**Comment by vnpy** [comment]
请安装指定版本的PySide6：

`pip install PySide6==6.3.0`
