### ISSUE TITLE
绘制K线的时候对Decimal类型的volume的支持问题

### ISSUE THREAD

**Issue by mundaneone** [vnpy/vnpy#3415]
## 环境

* 操作系统: Windows 11
* Python版本: 3.10.9
* VeighNa版本: VeighNa Studio-3.6.0

## Issue类型
Enhancement

ibapi 10.20.1版本，用Decimal来表示例如volume,position。在绘制K线的时候会发生问题。例如decoder.py中的某个方法：
```
def processHistoricalDataMsg(self, fields):
        next(fields)

        if self.serverVersion < MIN_SERVER_VER_SYNT_REALTIME_BARS:
            decode(int, fields)

        reqId = decode(int, fields)
        startDateStr = decode(str, fields) # ver 2 field
        endDateStr = decode(str, fields) # ver 2 field

        itemCount = decode(int, fields)

        for _ in range(itemCount):
            bar = BarData()
            bar.date = decode(str, fields)
            bar.open = decode(float, fields)
            bar.high = decode(float, fields)
            bar.low = decode(float, fields)
            bar.close = decode(float, fields)
            bar.volume = decode(Decimal, fields)
            bar.wap = decode(Decimal, fields)

            if self.serverVersion < MIN_SERVER_VER_SYNT_REALTIME_BARS:
                decode(str, fields)

            bar.barCount = decode(int, fields) # ver 3 field

            self.wrapper.historicalData(reqId, bar)

        # send end of dataset marker
        self.wrapper.historicalDataEnd(reqId, startDateStr, endDateStr)
```

## 预期程序行为
正常运行

## 实际程序行为
绘制K线的时候的问题。
```
Traceback (most recent call last):
  File "C:\veighna_studio\lib\site-packages\vnpy\chart\widget.py", line 220, in _update_y_range
    plot.setRange(yRange=y_range)
  File "C:\veighna_studio\lib\site-packages\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 284, in method
    return getattr(self.vb, name)(*args, **kwargs)
  File "C:\veighna_studio\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 585, in setRange
    quantization_limit = (mn+mx) * 1.5e-15 # +/-10 discrete steps of double resolution
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
```

## 重现步骤

使用ib官方的10.20.1版本的api替换掉自带的9.81版本的api之后，就会出现这个问题, 希望加上Decimal的支持

**Comment by vnpy** [comment]
https://pypi.org/project/ibapi/#history

查了目前PyPI上的版本，还是9.81.1.post1，找不到这个10.20.1。

另外可以在historicalData回调函数中，将volume字段转为int即可。
