### ISSUE TITLE
Linux运行run.py报错: 需要提交datafeed信息

### ISSUE THREAD

**Issue by stucash** [vnpy/vnpy#3493]
## 环境

* 操作系统: Debian 11 based Linux
* Python版本: 3.10.5
* VeighNa版本: 3.9.0发行版
## Issue类型
三选一：Question/Enhancement

## 预期程序行为

运行run.py可以成功打开GUI.

## 实际程序行为
运行run.py直接弹出错误消息

```
没有配置要使用的数据服务，请修改全局配置中的datafeed相关内容
Traceback (most recent call last):
  File "/home/demo/Live-usb-storage/projects/python/alpha/run.py", line 30, in <module>
    main()
  File "/home/demo/Live-usb-storage/projects/python/alpha/run.py", line 23, in main
    main_window = MainWindow(main_engine, event_engine)
  File "/home/demo/Live-usb-storage/projects/python/alpha/lib/python3.10/site-packages/vnpy/trader/ui/mainwindow.py", line 51, in __init__
    self.init_ui()
  File "/home/demo/Live-usb-storage/projects/python/alpha/lib/python3.10/site-packages/vnpy/trader/ui/mainwindow.py", line 58, in init_ui
    self.init_menu()
  File "/home/demo/Live-usb-storage/projects/python/alpha/lib/python3.10/site-packages/vnpy/trader/ui/mainwindow.py", line 127, in init_menu
    ui_module: ModuleType = import_module(app.app_module + ".ui")
  File "/home/demo/.pyenv/versions/3.10.5/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/demo/Live-usb-storage/projects/python/alpha/lib/python3.10/site-packages/vnpy_ctabacktester/ui/__init__.py", line 1, in <module>
    from .widget import BacktesterManager
  File "/home/demo/Live-usb-storage/projects/python/alpha/lib/python3.10/site-packages/vnpy_ctabacktester/ui/widget.py", line 8, in <module>
    import pyqtgraph as pg
  File "/home/demo/Live-usb-storage/projects/python/alpha/lib/python3.10/site-packages/pyqtgraph/__init__.py", line 18, in <module>
    from .colors import palette
  File "/home/demo/Live-usb-storage/projects/python/alpha/lib/python3.10/site-packages/pyqtgraph/colors/palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "/home/demo/Live-usb-storage/projects/python/alpha/lib/python3.10/site-packages/pyqtgraph/Qt/__init__.py", line 287, in <module>
    isQObjectAlive = shiboken.isValid
AttributeError: module 'shiboken6' has no attribute 'isValid'

```

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图
按照github上的安装步骤进行安装. 

一些小的建议:

希望团队能考虑编辑下使用文档, 使用文档可以提及需要额外安装vnpy_ctp及其他的包, 安装步骤当中只是包含了vnpy的安装, 但其他的包需要单独安装. 使用文档中很多地方感觉已经outdated, 比如ubuntu安装指南中说某些接口是不支持ubuntu的(我理解为不支持Linux), 让我到交易接口篇详查. 但是交易接口篇没有相关信息, 或者说, 交易接口篇在哪? 

在Linux下, `.vntrader`会默认在$HOME/下生成, 我看到一个vt_setting.json的空文件, 我理解这个就是全局配置文件;但他可能也不是. 他到底是吗? 希望团队可以提及一下`.vntrader`的默认生成位置, 和全局配置文件的名字. 
如果是全局配置文件, 那按照提示我应该在这里写入datafeed的相关信息. 

另外一个问题是, 我必须要有datafeed才能打开GUI界面吗?在安装步骤中我没有看到这个步骤. 另外我个人其实并不需要GUI, 请问有介绍关于直接在jupyter/ipython中运行vnpy框架的示例文件吗? `.vntrader`是不是只会在第一次运行GUI之后才会产生?如果是从jupyter进行编程, 我是否需要手动创建`.vntrader`和`vt_settings.json`呢?

我的主要场景是在海外市场, IB提供一些基础的数据, 但是我看IB并不能作为数据接口填写到datafeed下面(我还没有找到相关文档在哪, 但我感觉是需要打开GUI才能配置IB的账号信息); 按我的场景, 我其实就无法提供datafeed的信息了, 因为目前支持的datafeed, 都是国内数据商. 所以是不是没有datafeed就无法使用vnpy呢?

`install.sh`中的`locale-gen`是需要root权限的, 但一般情况下我是用虚拟环境在运行包测试, 所以一般不会是root. 在Linux安装脚本可以调整一下吗(我目前还不知道可以绕过root增加locale的合理的办法)?

现在vnpy已经非常成熟, 感觉团队可以润湿一下使用文档, 让文档更面向用户一点.

**Comment by laiNingQ** [comment]
我也遇到了这个问题，首先我拉取了github上的vnpy的源码，然后使用了anaconda创建了python3.10的环境，并且install.bat。随后我根据官网的文档进行run.py提示没有vnpy_ctp，然后一路报错DataManagerApp一路pip，最后遇到了module 'shiboken6' has no attribute 'isValid'，目前仍未解决

**Comment by vnpy** [comment]
requirements.txt中有依赖库的具体版本信息，请尝试安装指定版本的PySdie6试试

**Comment by YerayL** [comment]
> requirements.txt中有依赖库的具体版本信息，请尝试安装指定版本的PySdie6试试

按照requirements.txt安装了PySide6==6.3.0，仍然会报这个错误（AttributeError: module 'shiboken6' has no attribute 'isValid'）

`Traceback (most recent call last):
  File "C:\mywork\vnpy-3.9.0\vnpy-3.9.0\examples\veighna_trader\run.py", line 99, in <module>
    main()
  File "C:\mywork\vnpy-3.9.0\vnpy-3.9.0\examples\veighna_trader\run.py", line 92, in main
    main_window = MainWindow(main_engine, event_engine)
  File "C:\Users\17670\.conda\envs\vnpy310\lib\site-packages\vnpy\trader\ui\mainwindow.py", line 51, in __init__
    self.init_ui()
  File "C:\Users\17670\.conda\envs\vnpy310\lib\site-packages\vnpy\trader\ui\mainwindow.py", line 58, in init_ui
    self.init_menu()
  File "C:\Users\17670\.conda\envs\vnpy310\lib\site-packages\vnpy\trader\ui\mainwindow.py", line 127, in init_menu
    ui_module: ModuleType = import_module(app.app_module + ".ui")
  File "C:\Users\17670\.conda\envs\vnpy310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\17670\.conda\envs\vnpy310\lib\site-packages\vnpy_ctabacktester\ui\__init__.py", line 1, in <module>
    from .widget import BacktesterManager
  File "C:\Users\17670\.conda\envs\vnpy310\lib\site-packages\vnpy_ctabacktester\ui\widget.py", line 8, in <module>
    import pyqtgraph as pg
  File "C:\Users\17670\.conda\envs\vnpy310\lib\site-packages\pyqtgraph\__init__.py", line 18, in <module>
    from .colors import palette
  File "C:\Users\17670\.conda\envs\vnpy310\lib\site-packages\pyqtgraph\colors\palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "C:\Users\17670\.conda\envs\vnpy310\lib\site-packages\pyqtgraph\Qt\__init__.py", line 287, in <module>
    isQObjectAlive = shiboken.isValid
AttributeError: module 'shiboken6' has no attribute 'isValid'`

**Comment by vnpy** [comment]
请使用pip安装，不要使用Conda（不推荐使用conda环境），已有用户反馈相关兼容性问题

**Comment by mbshqqb** [comment]
> 请使用pip安装，不要使用Conda（不推荐使用conda环境），已有用户反馈相关兼容性问题

用pip安装的，还是会有这个问题，很神奇。

**Comment by vnpy** [comment]
![image](https://github.com/vnpy/vnpy/assets/11263900/646aa8c4-0e53-4d8b-a0be-58f1de8a3cc2)

![image](https://github.com/vnpy/vnpy/assets/11263900/9f4369d6-4a38-41b5-a525-d21e66d68bb9)

请使用图中命令检查shiboken6和pyqtgraph是否为对应版本
