### ISSUE TITLE
求助，报错：bsddb.db.DBNoSuchFileError

### ISSUE THREAD

**Issue by hillerliao** [vnpy/vnpy#358]
`Traceback (most recent call last):
  File "run.py", line 46, in <module>
    main()
  File "run.py", line 28, in main
    me = MainEngine(ee)
  File "C:\Users\liaozhihai\Envs\vnpy\lib\site-packages\vnpy\trader\vtEngine.py", line 33, in __init__
    self.dataEngine = DataEngine(self.eventEngine)
  File "C:\Users\liaozhihai\Envs\vnpy\lib\site-packages\vnpy\trader\vtEngine.py", line 299, in __init__
    self.loadContracts()
  File "C:\Users\liaozhihai\Envs\vnpy\lib\site-packages\vnpy\trader\vtEngine.py", line 334, in loadContracts
    f = shelve.open(self.contractFileName)
  File "c:\Python27\Lib\shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "c:\Python27\Lib\shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "c:\Python27\Lib\anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "c:\Python27\Lib\dbhash.py", line 18, in open
    return bsddb.hashopen(file, flag, mode)
  File "c:\Python27\Lib\bsddb\__init__.py", line 364, in hashopen
    d.open(file, db.DB_HASH, flags, mode)
bsddb.db.DBNoSuchFileError: (2, 'No such file or directory')`

**Comment by vnpy** [comment]
说明下你的运行环境？

**Comment by hillerliao** [comment]
@vnpy 

操作系统：
Windows 7 ，64位系统

Python环境：
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32

vnpy版本：
vnpy (1.6.2)

MongoDB:
3.4

**Comment by nigelliyang** [comment]
我也有同样的问题
Traceback (most recent call last):
  File "E:/AutoTrade/tradelink/TradeLink/PythonPlex/CTA/run.py", line 48, in <module>
    main()
  File "E:/AutoTrade/tradelink/TradeLink/PythonPlex/CTA/run.py", line 29, in main
    me = MainEngine(ee)
  File "D:\Anaconda2_32\lib\site-packages\vnpy\trader\vtEngine.py", line 33, in __init__
    self.dataEngine = DataEngine(self.eventEngine)
  File "D:\Anaconda2_32\lib\site-packages\vnpy\trader\vtEngine.py", line 299, in __init__
    self.loadContracts()
  File "D:\Anaconda2_32\lib\site-packages\vnpy\trader\vtEngine.py", line 334, in loadContracts
    f = shelve.open(self.contractFileName)
  File "D:\Anaconda2_32\lib\shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "D:\Anaconda2_32\lib\shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "D:\Anaconda2_32\lib\anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "D:\Anaconda2_32\lib\dbhash.py", line 18, in open
    return bsddb.hashopen(file, flag, mode)
  File "D:\Anaconda2_32\lib\bsddb\__init__.py", line 364, in hashopen
    d.open(file, db.DB_HASH, flags, mode)
bsddb.db.DBNoSuchFileError: (2, 'No such file or directory')

**Comment by ipqhjjybj** [comment]
C:\ProgramData\Anaconda2\Lib\site-packages\vnpy\trader\temp
在 vnpy/trader下面创建一个 temp文件夹，  这样会自动生成 ContractData.vt 文件。  。 有些windows机器不能自动产生temp文件夹，导致错误。。。

**Comment by ipqhjjybj** [comment]
@hillerliao @vnpy @nigelliyang

**Comment by vnpy** [comment]
遇到这个问题的用户，请检查是否以管理员身份在运行程序，否则可能出现Python无权创建temp文件夹的情况，导致后续的shelve创建文件也失败

**Comment by nigelliyang** [comment]
非常感谢，问题解决

**Comment by icjl** [comment]
创建了文件夹 还是报这个错误····
