### ISSUE TITLE
发送邮件失败不应该影响主程序

### ISSUE THREAD

**Issue by tongjun741** [vnpy/vnpy#3580]
## 环境

* 操作系统: Amazon Linux
* Python版本: 3.10
* VeighNa版本: 2022.02.28

## Issue类型
Bug

## 预期程序行为
发送邮件失败不应该影响主程序

## 实际程序行为
发送邮件失败后主程序崩溃

## 重现步骤
我是用脚本启动的，没有图形界面。
在on_order事件中发现下单失败时会调用main_engine.send_email给自己发邮件通知。
此时SMTP出现了一个异常，导致主进程崩溃了，一直报：公共频道触发异常，类型：<class 'RuntimeError'>，信息：cannot schedule new futures after shutdown

## SMT异常的具体日志如下：

Exception in thread Thread-3 (run):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/vnpy/trader/engine.py", line 598, in run
    with smtplib.SMTP_SSL(
  File "/usr/lib/python3.10/smtplib.py", line 284, in __exit__
    raise SMTPResponseException(code, message)
smtplib.SMTPResponseException: (-1, b'\x00\x00\x00')
2024-10-16 18:04:52,753  INFO: Websocket Public API连接断开
2024-10-16 18:04:53,756  INFO: 公共频道触发异常，类型：<class 'RuntimeError'>，信息：cannot schedule new futures after shutdown
[2024-10-16T18:04:53.756234]: Unhandled WebSocket Error:<class 'RuntimeError'>

## 可能的问题点：
https://github.com/vnpy/vnpy/blob/master/vnpy/trader/engine.py#L647
EmailEngine的run方法中为什么不捕捉所有异常呢？

**Comment by tongjun741** [comment]
跟踪了几天，还没找到问题，目前只能确认不是发邮件的问题。
具体表现：
1、在本地使用aws服务器上的代理连接币安就一切正常；
2、在aws服务器上直连币安就有问题：

`Exception trace:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/vnpy_rest/rest_client.py", line 285, in _process_request
    response: Response = await self._get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/vnpy_rest/rest_client.py", line 266, in _get_response
    cr: ClientResponse = await self.session.request(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 821, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown`

尝试升级vnpy到最新版本、去掉docker直接在裸机上运行都不行。
我放弃了，在aws服务上用Privoxy搭了一个代理服务，目前可以跑。

**Comment by vnpy** [comment]
已经增加异常捕捉机制
