### ISSUE TITLE
数据管理下载数据报错

### ISSUE THREAD

**Issue by linst95** [vnpy/vnpy#3581]
## 环境

* 操作系统: Windows 11
* Python版本: veighna_studio-3.9.3
* VeighNa版本: veighna_studio-3.9.3

## Issue类型
Bug

## 预期程序行为
下载数据成功，正确储存到postgres数据库

## 实际程序行为
下载失败，报错如下：
Traceback (most recent call last):
  File "C:\veighna_studio\lib\site-packages\vnpy_datamanager\ui\widget.py", line 610, in download
    count: int = self.engine.download_bar_data(symbol, exchange, interval, start, self.output)
  File "C:\veighna_studio\lib\site-packages\vnpy_datamanager\engine.py", line 215, in download_bar_data
    self.database.save_bar_data(data)
  File "C:\veighna_studio\lib\site-packages\vnpy_postgresql\postgresql_database.py", line 198, in save_bar_data
    ).execute()
  File "C:\veighna_studio\lib\site-packages\peewee.py", line 1971, in inner
    return method(self, database, *args, **kwargs)
  File "C:\veighna_studio\lib\site-packages\peewee.py", line 2042, in execute
    return self._execute(database)
  File "C:\veighna_studio\lib\site-packages\peewee.py", line 2847, in _execute
    return super(Insert, self)._execute(database)
  File "C:\veighna_studio\lib\site-packages\peewee.py", line 2558, in _execute
    cursor = self.execute_returning(database)
  File "C:\veighna_studio\lib\site-packages\peewee.py", line 2565, in execute_returning
    cursor = database.execute(self)
  File "C:\veighna_studio\lib\site-packages\peewee.py", line 3258, in execute
    sql, params = ctx.sql(query).query()
  File "C:\veighna_studio\lib\site-packages\peewee.py", line 628, in sql
    return obj.__sql__(self)
  File "C:\veighna_studio\lib\site-packages\peewee.py", line 2832, in __sql__
    self._generate_insert(self._insert, ctx)
  File "C:\veighna_studio\lib\site-packages\peewee.py", line 2708, in _generate_insert
    column = getattr(self.table, column)
AttributeError: type object 'DbBarData' has no attribute 'extra'

## 重现步骤
使用数据管理下载数据

**Comment by vnpy** [comment]
目前vnpy_postgresql并未支持extra字段，因此写入数据时请确保BarData没有提供extra字段
