### ISSUE TITLE
vnpy_xtp运行报错！

### ISSUE THREAD

**Issue by eshao731** [vnpy/vnpy#3592]
## 环境

* 操作系统: macOS
* Python版本: python3.11

## Issue类型
三选一：Question

## 预期程序行为
已经正常安装vnpy vnpy_xtp vnpy_ctastrategy vnpy_ctabacktester vnpy_datamanager  rqdatac ta-lib numpy==1.26.4

执行vnpy_xtp仓库的实例代码报错
```python
from vnpy.event import EventEngine
from vnpy.trader.engine import MainEngine
from vnpy.trader.ui import MainWindow, create_qapp

from vnpy_xtp import XtpGateway


def main():
    """主入口函数"""
    qapp = create_qapp()

    event_engine = EventEngine()
    main_engine = MainEngine(event_engine)
    main_engine.add_gateway(XtpGateway)
    
    main_window = MainWindow(main_engine, event_engine)
    main_window.showMaximized()

    qapp.exec()


if __name__ == "__main__":
    main()
```

## 实际程序行为

运行报错：
```bash
Traceback (most recent call last):
  File "/Users/eshao/PycharmProjects/my-vnpy/demo_vnpy.py", line 5, in <module>
    from vnpy_xtp import XtpGateway
  File "/Users/eshao/PycharmProjects/my-vnpy/.venv/lib/python3.11/site-packages/vnpy_xtp/__init__.py", line 25, in <module>
    from .gateway import XtpGateway
  File "/Users/eshao/PycharmProjects/my-vnpy/.venv/lib/python3.11/site-packages/vnpy_xtp/gateway/__init__.py", line 1, in <module>
    from .xtp_gateway import XtpGateway
  File "/Users/eshao/PycharmProjects/my-vnpy/.venv/lib/python3.11/site-packages/vnpy_xtp/gateway/xtp_gateway.py", line 29, in <module>
    from ..api import MdApi, TdApi
  File "/Users/eshao/PycharmProjects/my-vnpy/.venv/lib/python3.11/site-packages/vnpy_xtp/api/__init__.py", line 1, in <module>
    from .vnxtpmd import MdApi
ModuleNotFoundError: No module named 'vnpy_xtp.api.vnxtpmd'
```

## 重现步骤

按照上述提供代码运行可重现

## 问题
是否vnpy_xtp不支持macOS?
如果不支持，什么时候可以支持，谢谢！

**Comment by vnpy** [comment]
因为股票量化交易所需的托管环境内，只有Windows/Linux的服务器，所以我们没有支持Mac。
