### ISSUE TITLE
Ubuntu 碰到 ImportError: No module named vnctpmd

### ISSUE THREAD

**Issue by hillerliao** [vnpy/vnpy#360]
Windows 没成功，尝试 Ubuntu 虚拟机，也没成功

```
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    from vnpy.trader.gateway import (ctpGateway, femasGateway, xspeedGateway,
  File "/home/lxf/.virtualenvs/vnpy/local/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway
  File "/home/lxf/.virtualenvs/vnpy/local/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "/home/lxf/.virtualenvs/vnpy/local/lib/python2.7/site-packages/vnpy/api/ctp/__init__.py", line 3, in <module>
    from vnctpmd import MdApi
ImportError: No module named vnctpmd 
```

配置如下：
Ubuntu 16.04.1 ，32位

Python 版本：2.7.12  32位

安装的模块：
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.5.0.1)
decorator (4.0.11)
enum34 (1.1.6)
ipython (5.4.1)
ipython-genutils (0.2.0)
msgpack-python (0.4.8)
numpy (1.13.0)
pathlib2 (2.2.1)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.14)
psutil (5.2.2)
ptyprocess (0.5.1)
Pygments (2.2.0)
pymongo (3.4.0)
PySide (1.2.4)
QDarkStyle (2.3.1)
QtPy (1.2.1)
scandir (1.5)
setuptools (36.0.1)
simplegeneric (0.8.1)
six (1.10.0)
TA-Lib (0.4.10)
traitlets (4.3.2)
vnpy (1.6.2)
wcwidth (0.1.7)
websocket-client (0.40.0)
wheel (0.29.0)

**Comment by vnpy** [comment]
1.6.2版本里的架构更新，还没有完成Ubuntu版本，1.7会完成。

Ubuntu的请先用1.5吧。
