### ISSUE TITLE
记录okcoin时崩溃

### ISSUE THREAD

**Issue by find-happiness** [vnpy/vnpy#385]
No handlers could be found for logger "websocket"
Exception in thread Thread-6:
Traceback (most recent call last):
  File "D:\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "F:\Project\quant\vnpy\vnpy\trader\gateway\okcoinGateway\okcoinGateway.py", line 302, in reconnect
    sleep(10)
NameError: global name 'sleep' is not defined

**Comment by vnpy** [comment]
在okcoinGateway.py最上方，加入一句from time import sleep

应该是之前修改项目结构的时候不小心删除了这一句，在Dev中会修复。
