### ISSUE TITLE
run.py 运行出错

### ISSUE THREAD

**Issue by find-happiness** [vnpy/vnpy#387]
Traceback (most recent call last):
  File "E:/Project/python/vnpy/examples/VnTrader/run.py", line 22, in <module>
    from vnpy.trader.app import (riskManager, ctaStrategy, spreadTrading)
  File "E:\Project\python\vnpy\vnpy\trader\app\spreadTrading\__init__.py", line 4, in <module>
    from .uiStWidget import StManager
  File "E:\Project\python\vnpy\vnpy\trader\app\spreadTrading\uiStWidget.py", line 73, in <module>
    class StLogMonitor(QtWidgets.QTextEdit):
  File "E:\Project\python\vnpy\vnpy\trader\app\spreadTrading\uiStWidget.py", line 75, in StLogMonitor
    signal = QtCore.pyqtSignal(type(Event()))
AttributeError: 'module' object has no attribute 'pyqtSignal'

**Comment by zsluedem** [comment]
我觉得是你的环境有问题,pyqt是不是5

**Comment by find-happiness** [comment]
@zsluedem  我不知道  怎么看是不是pyqt版本

**Comment by vnpy** [comment]
试试import PyQt4和import PyQt5两句命令，哪个能运行就是哪个

**Comment by ipqhjjybj** [comment]
这个问题是  Anaconda2 版本不对导致的。
