### ISSUE TITLE
thread not start when join 

### ISSUE THREAD

**Issue by coolmax2000** [vnpy/vnpy#39]
Traceback (most recent call last):
  File "D:\py\vnpy-master\vn.trader\uiMainWindow.py", line 260, in closeEvent
    self.mainEngine.exit()
  File "D:\py\vnpy-master\vn.trader\vtEngine.py", line 162, in exit
    gateway.close()
  File "D:\py\vnpy-master\vn.trader\oandaGateway\oandaGateway.py", line 128, in
close
    self.api.exit()
  File "D:\py\vnpy-master\vn.trader\oandaGateway\vnoanda.py", line 182, in exit
    self.reqThread.join()
  File "C:\Anaconda2\lib\threading.py", line 929, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started

Resolution:
vn.trader\oandaGateway\vnoanda.py
Add code at line 180 to check if API is active.
    #----------------------------------------------------------------------
    def exit(self):
        """退出接口"""
       ** if self.active:**
            self.active = False
            self.reqThread.join()

**Comment by vnpy** [comment]
已修复。
