### ISSUE TITLE
运行 run.py 出现以下问题：

### ISSUE THREAD

**Issue by qinyuLT** [vnpy/vnpy#398]
D:\python>python run.py
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    main()
  File "run.py", line 28, in main
    me = MainEngine(ee)
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\vtEngine.py", line 33, in __init__
    self.dataEngine = DataEngine(self.eventEngine)
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\vtEngine.py", line 299, in __init__
    self.loadContracts()
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\vtEngine.py", line 334, in 
     loadContractsf = shelve.open(self.contractFileName)
  File "C:\ProgramData\Anaconda2\lib\shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "C:\ProgramData\Anaconda2\lib\shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "C:\ProgramData\Anaconda2\lib\anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "C:\ProgramData\Anaconda2\lib\dbhash.py", line 18, in open
    return bsddb.hashopen(file, flag, mode)
  File "C:\ProgramData\Anaconda2\lib\bsddb\__init__.py", line 364, in 
hashopend.open(file, db.DB_HASH, flags, mode)
bsddb.db.DBNoSuchFileError: (2, 'No such file or directory')

**Comment by qinyuLT** [comment]
[](https://raw.githubusercontent.com/qinyuLT/Images/master/vnpy_error.png)

**Comment by qinyuLT** [comment]
[https://raw.githubusercontent.com/qinyuLT/Images/master/vnpy_error.png](url)

**Comment by qinyuLT** [comment]
截图 [https://github.com/qinyuLT/Images/blob/master/vnpy_error.png](url)

**Comment by qinyuLT** [comment]
已解决。
第一次用命令下载的vnpy，出现以上问题
后来下载zip文件，运行成功

**Comment by vnpy** [comment]
以上问题用管理员身份来运行Python即可解决。
