### ISSUE TITLE
jupyter notebook运行回测样例问题

### ISSUE THREAD

**Issue by wisfern** [vnpy/vnpy#418]
vnpy的dev分支，最新版本
用jupyter note运行了vnpy\examples\CtaBacktesting\backtesting.ipynb，第一行代码就运行不下去
windows系统已经设置了PYTHONPATH到vnpy的根目录。

Traceback (most recent call last):
  File "vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\finance\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyEngine
Traceback (most recent call last):
  File "vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\finance\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyEngine
Traceback (most recent call last):
  File "vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\finance\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyAtrRsi
Traceback (most recent call last):
  File "vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\finance\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyDualThrust
Traceback (most recent call last):
  File "vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\finance\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyEmaDemo
Traceback (most recent call last):
  File "vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\finance\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyKingKeltner
Traceback (most recent call last):
  File "vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\finance\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyBreakOut
Traceback (most recent call last):
  File "vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\finance\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyAtrRsi
Traceback (most recent call last):
  File "vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\finance\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyBreakOut
Traceback (most recent call last):
  File "vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\finance\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyAtrRsi
Traceback (most recent call last):
  File "vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "D:\finance\anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyDualThrust
Traceback (most recent call last):

**Comment by zsluedem** [comment]
路径应该还是没有设置好，试一试print出来debug

**Comment by wisfern** [comment]
问题是发生在importlib.import_module，这个问题，不管我设置怎样的PYTHONPATH都没用，而其他代码都正常。

**Comment by wisfern** [comment]
问题找到了，下面这一段代码，传给importlib的字符串只是类名，并没有带上路径，因此找不到了。
# 遍历工作目录下的文件
workingPath = os.getcwd()
print 'workingPath', workingPath
for root, subdirs, files in os.walk(workingPath):
    packet_path = root.replace(workingPath, '').replace(os.pathsep, '.')
    for name in files:
        # 只有文件名中包含strategy且非.pyc的文件，才是策略文件
        if 'strategy' in name and '.pyc' not in name:
            # 模块名称无需前缀
            moduleName = packet_path + name.replace('.py', '')
            loadStrategyModule(moduleName)

**Comment by zsluedem** [comment]
什么版本的。

**Comment by wisfern** [comment]
dev分支的最新版本。

**Comment by vnpy** [comment]
已修复
