### ISSUE TITLE
运行run.py时遇到DBNoSuchFileError错误

### ISSUE THREAD

**Issue by likenji** [vnpy/vnpy#449]
系统Win 8.1 64位，
环境是anaconda 2.7 32bit，配置方式如链接所示
https://stackoverflow.com/questions/33709391/using-multiple-python-engines-32bit-64bit-and-2-7-3-5

VS插件已安装。
SIMNOW的账户、密码、BrokerID已填写，但行情和服务器地址未更改。
然后在运行run.py出现题目的错误。
详细错误代码如下：
(py27x86) C:\Users\User\Desktop\Python\quant\vnpy>python run.py
Traceback (most recent call last):
  File "run.py", line 53, in <module>
    main()
  File "run.py", line 35, in main
    me = MainEngine(ee)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\site-packages\vnpy\trader\vtEng
ine.py", line 33, in __init__
    self.dataEngine = DataEngine(self.eventEngine)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\site-packages\vnpy\trader\vtEng
ine.py", line 299, in __init__
    self.loadContracts()
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\site-packages\vnpy\trader\vtEng
ine.py", line 334, in loadContracts
    f = shelve.open(self.contractFileName)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\shelve.py", line 227, in __init
__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\dbhash.py", line 18, in open
    return bsddb.hashopen(file, flag, mode)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\bsddb\__init__.py", line 364, i
n hashopen
    d.open(file, db.DB_HASH, flags, mode)
bsddb.db.DBNoSuchFileError: (2, 'No such file or directory')

**Comment by likenji** [comment]
https://github.com/vnpy/vnpy/issues/398
按照指示，使用管理员身份运行cmd，再运行run.py，问题仍然未解决（相同报错信息）。

全部代码如下：
Microsoft Windows [版本 6.3.9600]
(c) 2013 Microsoft Corporation。保留所有权利。

C:\Windows\system32>set CONDA_FORCE_32BIT=1

C:\Windows\system32>activate py27x86

(py27x86) C:\Windows\system32>python C:\Users\User\Desktop\Python\quant\vnpy\run
.py
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Python\quant\vnpy\run.py", line 53, in <module>
    main()
  File "C:\Users\User\Desktop\Python\quant\vnpy\run.py", line 35, in main
    me = MainEngine(ee)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\site-packages\vnpy\trader\vtEng
ine.py", line 33, in __init__
    self.dataEngine = DataEngine(self.eventEngine)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\site-packages\vnpy\trader\vtEng
ine.py", line 299, in __init__
    self.loadContracts()
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\site-packages\vnpy\trader\vtEng
ine.py", line 334, in loadContracts
    f = shelve.open(self.contractFileName)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\shelve.py", line 227, in __init
__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\dbhash.py", line 18, in open
    return bsddb.hashopen(file, flag, mode)
  File "C:\Users\User\Anaconda3\envs\py27x86\lib\bsddb\__init__.py", line 364, i
n hashopen
    d.open(file, db.DB_HASH, flags, mode)
bsddb.db.DBNoSuchFileError: (2, 'No such file or directory')

**Comment by likenji** [comment]
https://github.com/vnpy/vnpy/issues/358
问题已解决，原因是 程序要在C盘创建文件夹，然后没有管理员权限的话是不行的（虽然我即使赋予了管理员权限也失败了！！）。不过解决方法很简单，手动在你的site-packages\vnpy\trade下创建一个temp文件夹即可。
PS：我这里是采用了conda环境来管理vnpy，所以对应的目录是C:\Users\User\Anaconda3\envs\py27x86\Lib\site-packages\vnpy\trader，应该有不少人都是采取了环境管理，注意一下这点即可，帮大家排个坑！

**Comment by asustnt3** [comment]
thanks so much it's really helpful

**Comment by yhangang** [comment]
It is really helpful. Thank you so much.
