### ISSUE TITLE
Mac系统安装不了

### ISSUE THREAD

**Issue by KrisLee** [vnpy/vnpy#478]
Mac系统安装不了，感觉是boost库编译失败了。
python vnpy/examples/VnTrader/run.py 
Traceback (most recent call last):
  File "vnpy/examples/VnTrader/run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway, ibGateway, 
  File "/Users/jing/anaconda2/lib/python2.7/site-packages/vnpy-1.7.0-py2.7.egg/vnpy/trader/gateway/ctpGateway/__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway
  File "/Users/jing/anaconda2/lib/python2.7/site-packages/vnpy-1.7.0-py2.7.egg/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "/Users/jing/anaconda2/lib/python2.7/site-packages/vnpy-1.7.0-py2.7.egg/vnpy/api/ctp/__init__.py", line 3, in <module>
    from vnctpmd import MdApi
ImportError: No module named vnctpmd

**Comment by vnpy** [comment]
MAC系统用不了

**Comment by KrisLee** [comment]
python是跨平台的，是不是和GUI使用的boost有关？

**Comment by KrisLee** [comment]
python是跨平台的，和cpt的接口有关？

**Comment by KrisLee** [comment]
python是跨平台的，和接口有关？

**Comment by vnpy** [comment]
是的，国内柜台API都没有提供MAC的版本

**Comment by wsygzn** [comment]
如果可以提供一个版本，方便Mac安装，不用那些不支持Mac的接口，这样还能连很多Mac能支持的接口
