### ISSUE TITLE
1.7安装报错

### ISSUE THREAD

**Issue by timinGo** [vnpy/vnpy#495]
双击 example/VnTrader.bat

```
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway, ibGateway,
  File "D:\Program Files\Anaconda\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\gateway\ctpGateway\__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway
  File "D:\Program Files\Anaconda\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\gateway\ctpGateway\ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "D:\Program Files\Anaconda\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\api\ctp\__init__.py", line 3, in <module>
    from vnctpmd import MdApi
ImportError: DLL load failed: 找不到指定的模块。
```

**Comment by xldistance** [comment]
安装是双击install.bat......

**Comment by timinGo** [comment]
@xldistance 
已经安装完了，运行时报错

**Comment by aslinwang** [comment]
好像是因为sgitGateway和shzdGateway接口在1.7不好使，去掉run.py里面关于这两块的内容重试下

**Comment by vnpy** [comment]
CTP接口报错的话，检查你的Anaconda是否是32位Python 2.7，以及vcredist x86 2013是否安装了

**Comment by timinGo** [comment]
@vnpy 确定是32位python2.7 vcredist x86是按照教程中的链接安装的

**Comment by KimChow** [comment]
在windows2012上面应该装多一个visual studio code才可以的。

 下载地址：https://code.visualstudio.com/
