### ISSUE TITLE
Ubuntu环境安装1.7版本不成功ImportError: No module named vnctpmd

### ISSUE THREAD

**Issue by rongli1101** [vnpy/vnpy#500]
按照https://github.com/vnpy/vnpy/wiki/Ubuntu%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85#%E5%AE%89%E8%A3%85vn.py 这里的步骤安装，最后一步遇到下面错误：
```
/vnpy-1.7/examples/VnTrader$ python run.py
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway, ibGateway, 
  File "/home/rh/anaconda2/lib/python2.7/site-packages/vnpy-1.7.0-py2.7.egg/vnpy/trader/gateway/ctpGateway/__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway
  File "/home/rh/anaconda2/lib/python2.7/site-packages/vnpy-1.7.0-py2.7.egg/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "/home/rh/anaconda2/lib/python2.7/site-packages/vnpy-1.7.0-py2.7.egg/vnpy/api/ctp/__init__.py", line 3, in <module>
    from vnctpmd import MdApi
ImportError: No module named vnctpmd

```

**Comment by vnpy** [comment]
看来应该是编译失败了，检查运行install.sh的时候，在编译CTP API时是否有报错

**Comment by likenji** [comment]
https://github.com/vnpy/vnpy/issues/483
You can take a look at this issue. I had the same problem as you did. The course of the problem is the failure during compling and I solved it by resetting the size of the swap area.

**Comment by cn3c3p** [comment]
我也遇到类似问题 ，不过，我是在noVNC DOCKER里，按照楼上说法，我怎么 resetting the size of the swap area？

**Comment by cn3c3p** [comment]
我重新编译install.sh之后，可以启动examples里vtMain.py, 但是，无法启动uiQt.py

**Comment by vnpy** [comment]
@cn3c3p 你的报错是啥？

**Comment by cn3c3p** [comment]
开始报错No module named vnctpmd，后来把各种依赖都安装好之后再重新编译，就可以启动samples的RUN.PY了，这样就OK了？很多情况是cmake编译器版本问题

**Comment by pxlong** [comment]
你好，我也遇到了这个问题：
`Traceback (most recent call last):
  File "examples/VnTrader/run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway, ibGateway, 
  File "/usr/local/lib/python2.7/dist-packages/vnpy-1.7.0-py2.7.egg/vnpy/trader/gateway/ctpGateway/__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway
  File "/usr/local/lib/python2.7/dist-packages/vnpy-1.7.0-py2.7.egg/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "/usr/local/lib/python2.7/dist-packages/vnpy-1.7.0-py2.7.egg/vnpy/api/ctp/__init__.py", line 3, in <module>
    from vnctpmd import MdApi
ImportError: No module named vnctpmd`
编译通过了，没报错。
环境: Ubuntu 14.04, python 2.7.6, vnpy-1.7 release, 没用anaconda, 自己用pip装的依赖。谢谢

**Comment by pxlong** [comment]
搞定了，原来是ubuntu 14.04自带的boost太老了（1.54），我手动升级到最新的了。
重新编译再解决ta-lib的问题，就无报错地启动了。
谢谢！

**Comment by vnpy** [comment]
@rongli1101 请参考 @pxlong 的方法试试吧。

**Comment by tongjun741** [comment]
同样的问题，ubuntu 16.0.4, boost是1.58.0。
vnpy的版本是1.7.0，
`~/vnpy-1.7$ python examples/CtaTrading/runCtaTrading.py
Traceback (most recent call last):
  File "examples/CtaTrading/runCtaTrading.py", line 10, in <module>
    from vnpy.trader.gateway import ctpGateway
  File "/home/tongjun/anaconda2/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway
  File "/home/tongjun/anaconda2/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
ImportError: cannot import name MdApi`

`sudo apt search libboost-dev
Sorting... Done
Full Text Search... Done
libboost-dev/xenial,now 1.58.0.1ubuntu1 amd64 [installed,automatic]
  Boost C++ Libraries development files (default version)`

**Comment by tongjun741** [comment]
手动拷贝后解决了这个问题，但又出现了新问题

`~/vnpy-1.7/vnpy/api/ctp$ cp *.so ~/anaconda2/lib/python2.7/site-packages`

`~/vnpy-1.7/examples/CtaTrading$ python runCtaTrading.py
--------------------
2017-11-10 18:56:04	启动CTA策略运行子进程
2017-11-10 18:56:04	事件引擎创建成功
Traceback (most recent call last):
  File "runCtaTrading.py", line 116, in <module>
    runChildProcess()
  File "runCtaTrading.py", line 46, in runChildProcess
    me = MainEngine(ee)
  File "/home/tongjun/anaconda2/lib/python2.7/site-packages/vnpy/trader/vtEngine.py", line 34, in __init__
    self.dataEngine = DataEngine(self.eventEngine)
  File "/home/tongjun/anaconda2/lib/python2.7/site-packages/vnpy/trader/vtEngine.py", line 304, in __init__
    self.loadContracts()
  File "/home/tongjun/anaconda2/lib/python2.7/site-packages/vnpy/trader/vtEngine.py", line 339, in loadContracts
    f = shelve.open(self.contractFilePath)
  File "/home/tongjun/anaconda2/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/home/tongjun/anaconda2/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/home/tongjun/anaconda2/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/home/tongjun/anaconda2/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/home/tongjun/anaconda2/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb`

**Comment by vnpy** [comment]
把examples/VnTrader/temp目录下的东西全部删掉再重启
