### ISSUE TITLE
策略运行后发单报错

### ISSUE THREAD

**Issue by mieshiyuyu** [vnpy/vnpy#522]
> Traceback (most recent call last):
  File "C:\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\event\eventEngine.py", line 82, in __run
    self.__process(event)
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\event\eventEngine.py", line 92, in __process
    [handler(event) for handler in self.__handlers[event.type_]]
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 240, in processTickEvent
    self.processStopOrder(tick)
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 226, in processStopOrder
    self.sendOrder(so.vtSymbol, so.orderType, price, so.volume, so.strategy)
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 130, in sendOrder
    vtOrderID = self.mainEngine.sendOrder(convertedReq, contract.gatewayName)    # 发单
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\vtEngine.py", line 137, in sendOrder
    self.dataEngine.updateOrderReq(orderReq, vtOrderID)     # 更新发出的委托请求到数据引擎中
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\vtEngine.py", line 490, in updateOrderReq
    detail.updateOrderReq(req, vtOrderID)
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\vtEngine.py", line 720, in updateOrderReq
    self.calculateFrozen()
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\vtEngine.py", line 744, in calculateFrozen
    frozenVolume = order.totalVolume - order.tradedVolume
AttributeError: 'VtOrderReq' object has no attribute 'totalVolume'

**Comment by mieshiyuyu** [comment]
dev版本

最新开锁仓信息一次返回4条 是不是可以缩减？ 有点刷屏

ag1712 ------------------------------
long, total:0, td:0, yd:0
long frozen, total:0, td:0, yd:0
short, total:1, td:1, yd:0
short frozen, total:0, td:0, yd:0
ag1712 ------------------------------
long, total:0, td:0, yd:0
long frozen, total:0, td:0, yd:0
short, total:1, td:1, yd:0
short frozen, total:0, td:0, yd:0
ag1712 ------------------------------
long, total:0, td:0, yd:0
long frozen, total:0, td:0, yd:0
short, total:1, td:1, yd:0
short frozen, total:0, td:0, yd:0
ag1712 ------------------------------
long, total:0, td:0, yd:0
long frozen, total:0, td:0, yd:0
short, total:2, td:2, yd:0
short frozen, total:0, td:0, yd:0

**Comment by mieshiyuyu** [comment]
> 增加主引擎中注册日志模块对事件监听类型的函数

没有把代码放进去 报错什么的

把最新更新的代码更改后。。 报错

  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 85, in __init__
    self.mainEngine.registerLogEvent(EVENT_CTA_LOG)
  File "C:\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\vtEngine.py", line 334, in registerLogEvent
    self.eventEngine.register(eventType, self.logEngine.processLogEvent)
AttributeError: 'NoneType' object has no attribute 'processLogEvent'

**Comment by vnpy** [comment]
收到，我来修改

**Comment by vnpy** [comment]
已解决！
