### ISSUE TITLE
手动开平仓会触发异常

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#524]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\uiBasicWidget.py", line 1058, in sendOrder
    self.mainEngine.sendOrder(req, gatewayName)
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\vtEngine.py", line 137, in sendOrder
    self.dataEngine.updateOrderReq(orderReq, vtOrderID)     # 更新发出的委托请求到数据引擎中
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\vtEngine.py", line 494, in updateOrderReq
    detail = self.getPositionDetail(req.vtSymbol)
AttributeError: 'VtOrderReq' object has no attribute 'vtSymbol'

**Comment by vnpy** [comment]
已解决！

**Comment by xldistance** [comment]
大佬，这个问题还在的

**Comment by vnpy** [comment]
不好意思漏了一行，重新修改了

**Comment by xldistance** [comment]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\uiBasicWidget.py", line 1057, in sendOrder
    self.mainEngine.sendOrder(req, gatewayName)
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\vtEngine.py", line 137, in sendOrder
    self.dataEngine.updateOrderReq(orderReq, vtOrderID)     # 更新发出的委托请求到数据引擎中
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\vtEngine.py", line 500, in updateOrderReq
    detail.updateOrderReq(req, vtOrderID)
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.0-py2.7.egg\vnpy\trader\vtEngine.py", line 719, in updateOrderReq
    order.vtSymbol = req.vtSymbol
AttributeError: 'VtOrderReq' object has no attribute 'vtSymbol'

**Comment by xldistance** [comment]
把719行改为order.vtSymbol = req.symbol，能用了

**Comment by vnpy** [comment]
已经修改，非常感谢！

**Comment by followdao** [comment]
1.7.2版本也是有这个问题，我自己倒是按照上面的提示修改正确了
