### ISSUE TITLE
key error：‘ctp.11’ simnow 7X24小时的接口

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#543]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\event\eventEngine.py", line 82, in __run
    self.__process(event)
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\event\eventEngine.py", line 92, in __process
    [handler(event) for handler in self.__handlers[event.type_]]
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 293, in processOrderEvent
    self.strategyOrderDict[strategy.name].remove(order.vtOrderID)
KeyError: 'CTP.11'

**Comment by xldistance** [comment]
可能是simnow 7X24小时的接口乱发单吧

**Comment by xldistance** [comment]
手动开平仓试了下，真的是simnow 7X24接口问题，有时平仓平不掉......
