### ISSUE TITLE
在windows server 上运行vnpy-dev1.71，报错如下RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by winner1986** [vnpy/vnpy#545]
2017-10-14 12:16:51,872  INFO: CTP	行情服务器连接成功
2017-10-14 12:16:51,877  INFO: CTP	交易服务器连接成功
2017-10-14 12:16:51,914  INFO: CTP	行情服务器登录完成
2017-10-14 12:16:51,917  INFO: CTP	交易服务器登录完成
2017-10-14 12:16:52,575  INFO: CTP	结算信息确认完成
2017-10-14 12:16:52,996  INFO: CTP	交易合约信息获取完成
2017-10-14 12:17:02,664  INFO: CTA_STRATEGY	CTA引擎启动成功
2017-10-14 12:17:03,913  INFO: CTA_STRATEGY	策略加载成功
2017-10-14 12:17:08,648  INFO: CTA_STRATEGY	strategyBollChannel_al1801:strategyBollChannel_al1801策略初始化
2017-10-14 12:17:09,042  INFO: CTA_STRATEGY	strategyEmaDemo_MA801:双EMA演示策略初始化
2017-10-14 12:17:09,414  INFO: CTA_STRATEGY	strategyAtrRsi_rb1801:strategyAtrRsi_rb1801策略初始化
2017-10-14 12:17:09,424  INFO: CTA_STRATEGY	kingkeltner_m1801:kingkeltner_m1801策略初始化
2017-10-14 12:17:11,483  INFO: CTA_STRATEGY	strategyBollChannel_al1801:strategyBollChannel_al1801策略启动
2017-10-14 12:17:11,486  INFO: CTA_STRATEGY	strategyEmaDemo_MA801:双EMA演示策略启动
2017-10-14 12:17:11,489  INFO: CTA_STRATEGY	strategyAtrRsi_rb1801:strategyAtrRsi_rb1801策略启动
2017-10-14 12:17:11,490  INFO: CTA_STRATEGY	kingkeltner_m1801:kingkeltner_m1801策略启动
2017-10-14 12:17:11,576  INFO: CTA_STRATEGY	策略strategyEmaDemo_MA801发送委托，MA801，空，2@2554.0
2017-10-14 12:17:11,582  INFO: CTA_STRATEGY	策略strategyEmaDemo_MA801发送委托，MA801，空，2@2554.0
2017-10-14 12:17:12,066  INFO: CTA_STRATEGY	策略strategyAtrRsi_rb1801发送委托，rb1801，空，1@3317.0
2017-10-14 12:17:12,134  INFO: CTA_STRATEGY	策略strategyAtrRsi_rb1801持仓保存成功，当前持仓0
2017-10-14 12:17:48,240  INFO: CTA_STRATEGY	策略strategyEmaDemo_MA801持仓保存成功，当前持仓0
2017-10-14 12:17:48,243  INFO: CTA_STRATEGY	策略strategyEmaDemo_MA801持仓保存成功，当前持仓-2
2017-10-14 12:18:11,601  INFO: CTA_STRATEGY	策略strategyAtrRsi_rb1801发送委托，rb1801，空，1@3556.0
2017-10-14 12:18:11,670  INFO: CTA_STRATEGY	策略strategyAtrRsi_rb1801持仓保存成功，当前持仓-1
2017-10-14 12:18:13,091  INFO: CTA_STRATEGY	策略kingkeltner_m1801发送委托，m1801，空，1@2636.0
2017-10-14 12:18:13,164  INFO: CTA_STRATEGY	策略kingkeltner_m1801持仓保存成功，当前持仓-1
2017-10-14 12:20:11,595  INFO: CTA_STRATEGY	策略strategyAtrRsi_rb1801触发异常已停止
Traceback (most recent call last):
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 557, in callStrategyFunc
    func(params)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\strategyAtrRsi.py", line 110, in onTick
    self.bm.updateTick(tick)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 353, in updateTick
    self.onBar(self.bar)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\strategyAtrRsi.py", line 115, in onBar
    self.cancelAll()
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 151, in cancelAll
    self.ctaEngine.cancelAll(self.name)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 617, in cancelAll
    for orderID in s:
RuntimeError: Set changed size during iteration

2017-10-14 12:43:12,158  INFO: CTA_STRATEGY	策略strategyBollChannel_al1801触发异常已停止
Traceback (most recent call last):
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 557, in callStrategyFunc
    func(params)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\strategyBollChannel.py", line 115, in onTick
    self.bm.updateTick(tick)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 353, in updateTick
    self.onBar(self.bar)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\strategyBollChannel.py", line 120, in onBar
    self.bm.updateBar(bar)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 417, in updateBar
    self.onXminBar(self.xminBar)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\strategyBollChannel.py", line 126, in onXminBar
    self.cancelAll()
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 151, in cancelAll
    self.ctaEngine.cancelAll(self.name)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 617, in cancelAll
    for orderID in s:
RuntimeError: Set changed size during iteration

**Comment by winner1986** [comment]
按照@合肥-上弦之月的帮助方法，将策略文件里的onbar函数里的self.cancelAll()函数注释掉，此错误消失了。但是又出现新的错误，如下：
2017-10-15 14:45:30,082  INFO: CTA_STRATEGY	策略strategyBollingerBot_m1801触发异常已停止
Traceback (most recent call last):
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 557, in callStrategyFunc
    func(params)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\strategyBollingerBot.py", line 123, in onTick
    self.onBar(self.bar)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\strategyBollingerBot.py", line 163, in onBar
    self.onFiveBar(fiveBar)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\strategyBollingerBot.py", line 198, in onFiveBar
    self.cancelOrder(orderID)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 146, in cancelOrder
    self.ctaEngine.cancelOrder(vtOrderID)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 152, in cancelOrder
    order = self.mainEngine.getOrder(vtOrderID)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\vtEngine.py", line 278, in getOrder
    return self.dataEngine.getOrder(vtOrderID)
  File "E:\vnpy_install\Anaconda2\lib\site-packages\vnpy-1.7.1-py2.7.egg\vnpy\trader\vtEngine.py", line 458, in getOrder
    return self.orderDict[vtOrderID]
TypeError: unhashable type: 'list'

**Comment by xldistance** [comment]
py2.7.egg\vnpy\trader\app\ctaStrategy\strategy\strategyBollingerBot.py", line 198, in onFiveBar
self.cancelOrder(orderID)也注释掉

**Comment by vnpy** [comment]
BollingerBot是个老策略，当时委托返回的还是单一委托号，现在为了实现自动开平仓，返回的已经是委托号列表了，所以需要修改下。

**Comment by vnpy** [comment]
另外cancelAll的bug已经修复了，建议还是用cancelAll
