### ISSUE TITLE
禁用LogEngine后CtaEngine注册日志事件异常

### ISSUE THREAD

**Issue by lamter** [vnpy/vnpy#569]
## 环境

* 操作系统: Docker.Ubuntu 16.04
* Anaconda版本: Anaconda 
* vn.py版本: v1.7.1发行版

## Issue类型
Bug

## 预期程序行为
在`VT_setting.json`中通过`"activeLog":false`禁用日志模块后，可以正常注册日志事件，但是不会输出日志。

## 实际程序行为
禁用后，注册日志事件出现异常。

## 重现步骤
1. 在`VT_setting.json`中设置`"activeLog":false`。
2. 启动服务。
3. 出现异常，内容如下
```python
Traceback (most recent call last):
  File "runCtaTrading.py", line 139, in <module>
    runChildProcess()
  File "runCtaTrading.py", line 67, in runChildProcess
    me.addApp(ctaStrategy)
  File "/srv/vnpy/vnpy/trader/vtEngine.py", line 93, in addApp
    self.appDict[appName] = appModule.appEngine(self, self.eventEngine)
  File "/srv/vnpy/vnpy/trader/app/ctaStrategy/svtCtaEngine.py", line 49, in __init__
    super(CtaEngine, self).__init__(mainEngine, eventEngine)
  File "/srv/vnpy/vnpy/trader/app/ctaStrategy/ctaEngine.py", line 90, in __init__
    self.mainEngine.registerLogEvent(EVENT_CTA_LOG)
  File "/srv/vnpy/vnpy/trader/vtEngine.py", line 348, in registerLogEvent
    self.eventEngine.register(eventType, self.logEngine.processLogEvent)
AttributeError: 'NoneType' object has no attribute 'processLogEvent'
```

**Comment by vnpy** [comment]
OK，我来加上个过滤

**Comment by vnpy** [comment]
已完成
