### ISSUE TITLE
ImportError: No module named vnxtpquote

### ISSUE THREAD

**Issue by reaIws** [vnpy/vnpy#613]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 64位
* vn.py版本: 如vnpy-master 20171120（下载日期）

## Issue类型
三选一：Question

## 预期程序行为
程序启动

## 实际程序行为
为启动成功

## 重现步骤
ssh://cmbc@192.168.137.1:22/home/cmbc/anaconda2/bin/python -u /home/cmbc/ipython/ipython2/workspace/vnpy-master/examples/VnTrader/run.py
Traceback (most recent call last):
  File "/home/cmbc/ipython/ipython2/workspace/vnpy-master/examples/VnTrader/run.py", line 26, in <module>
    from vnpy.trader.gateway import xtpGateway
  File "/home/cmbc/ipython/ipython2/workspace/vnpy-master/vnpy/trader/gateway/xtpGateway/__init__.py", line 4, in <module>
    from xtpGateway import XtpGateway
  File "/home/cmbc/ipython/ipython2/workspace/vnpy-master/vnpy/trader/gateway/xtpGateway/xtpGateway.py", line 11, in <module>
    from vnpy.api.xtp import *
  File "/home/cmbc/ipython/ipython2/workspace/vnpy-master/vnpy/api/xtp/__init__.py", line 3, in <module>
    from vnxtpquote import QuoteApi
ImportError: No module named vnxtpquote

#程序代码如下

# encoding: UTF-8

from vnxtpquote import QuoteApi
from vnxtptrader import TraderApi
from xtp_data_type import *

/home/cmbc/ipython/ipython2/workspace/vnpy-master/vnpy/api/xtp/__init__.py

程序没改动，这个为啥了

**Comment by reaIws** [comment]
cmbc@u1:~/ipython/ipython2/workspace/vnpy-master/examples/VnTrader$ python run.py 
Traceback (most recent call last):
  File "run.py", line 26, in <module>
    from vnpy.trader.gateway import xtpGateway
  File "/home/cmbc/anaconda2/lib/python2.7/site-packages/vnpy-1.7.1-py2.7.egg/vnpy/trader/gateway/xtpGateway/__init__.py", line 4, in <module>
    from xtpGateway import XtpGateway
  File "/home/cmbc/anaconda2/lib/python2.7/site-packages/vnpy-1.7.1-py2.7.egg/vnpy/trader/gateway/xtpGateway/xtpGateway.py", line 11, in <module>
    from vnpy.api.xtp import *
  File "/home/cmbc/anaconda2/lib/python2.7/site-packages/vnpy-1.7.1-py2.7.egg/vnpy/api/xtp/__init__.py", line 3, in <module>
    from vnxtpquote import QuoteApi
ImportError: No module named vnxtpquote
我在这个下载的目录下运行，程序运行的是安装目录下的，我想运行，下载目录下的程序，该怎么办了

**Comment by xldistance** [comment]
pip list里面有vnpy吗

**Comment by vnpy** [comment]
在vnpy/api/xtp目录下运行bash build.sh，然后再回到vnpy目录下运行bash install.sh安装

**Comment by reaIws** [comment]
我试试

**Comment by reaIws** [comment]
pip list 里面有vnpy

**Comment by reaIws** [comment]
@vnpy 有效
