### ISSUE TITLE
vtMain.py运行不成功

### ISSUE THREAD

**Issue by zwblst007** [vnpy/vnpy#64]
按照指导设置好后，运行vtMain.py，之前已经运行成功，不过现在会出现如下提示：
Traceback (most recent call last):

  File "<ipython-input-1-d02f0460dc5f>", line 44, in <module>
    main()

  File "<ipython-input-1-d02f0460dc5f>", line 36, in main
    mainWindow = MainWindow(mainEngine, mainEngine.eventEngine)

  File "uiMainWindow.py", line 25, in __init__
    self.loadWindowSettings()

  File "uiMainWindow.py", line 306, in loadWindowSettings
    self.restoreState(settings.value('state').toByteArray())

AttributeError: 'NoneType' object has no attribute 'toByteArray'
请问如何解决？

**Comment by vnpy** [comment]
把self.loadWindowSettings()这行注释掉，看来似乎是PyQt版本的问题。
