### ISSUE TITLE
dataRecorder盘中纪录数据经常出现 duplicate key error collection

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#650]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 5.0.1 Python 3 64位
* vn.py版本: 1.7.2dev

## Issue类型
三选一：Bug

## 预期程序行为
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\vnpy-1.7.2-py3.6.egg\vnpy\trader\app\dataRecorder\drEngine.py", line 244, in run
    self.mainEngine.dbInsert(dbName, collectionName, d)
  File "C:\ProgramData\Anaconda3\lib\site-packages\vnpy-1.7.2-py3.6.egg\vnpy\trader\vtEngine.py", line 219, in dbInsert
    collection.insert_one(d)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\collection.py", line 670, in insert_one
    bypass_doc_val=bypass_document_validation),
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\collection.py", line 575, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\collection.py", line 557, in _insert_one
    _check_write_command_response([(0, result)])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\helpers.py", line 314, in _check_write_command_response
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: VnTrader_1Min_Db.i1805 index: datetime_1 dup key: { : new Date(1513804560000) }

## 实际程序行为
大概三四天就会出现一次，这个现在有解决办法吗？

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
可能弄个try...catch来捕获会比较好，但是要小心可能数据会出现瑕疵

**Comment by KobeZhao** [comment]
我今天也遇到了，这个现在怎么修复呢

**Comment by vnpy** [comment]
已修复

**Comment by KobeZhao** [comment]
用try...catch捕捉，会忽略真正的bug，可能是个临时方案，id重复的这个bug是什么导致的呢，有没有办法从bug这里解决呢

**Comment by vnpy** [comment]
CTP行情服务器正常是不会重复推送行情的，但是由于CTP使用的是TCP协议，当用户收到某个Tick的瞬间，网络出现闪断导致时服务器没有收到用户端的数据接收回应，就可能再次发起数据推送，导致出现重复，最简单的处理方法就是过滤掉

**Comment by vnpy** [comment]
改成update并不建议，一般第一次推送的数据可靠性是最高的，第二次推送的就有可能是有问题的
