### ISSUE TITLE
ubuntu-install-failure

### ISSUE THREAD

**Issue by tomtsang** [vnpy/vnpy#707]
## 环境

* 操作系统: Ubuntu desktop 16.04
* Anaconda版本: 如Anaconda 5.0.1 Python 2.7 32位
* vn.py版本: 1.7.3

## Issue类型

Question

## 预期程序行为

python run.py OK

## 实际程序行为

```
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/examples/VnTrader$ python run.py
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway,
  File "/home/tom/.ana/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway
  File "/home/tom/.ana/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "/home/tom/.ana/lib/python2.7/site-packages/vnpy/api/ctp/__init__.py", line 3, in <module>
    from vnctpmd import MdApi
ImportError: No module named vnctpmd
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/examples/VnTrader$
```

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

我也遇到了同样的问题....按 @vnpy 的方法, 也未解决...

```
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3$ cd examples/VnTrader/
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/examples/VnTrader$ pip show vnpy
Name: vnpy
Version: 1.7.3
Summary: A framework for developing Quantitative Trading programmes
Home-page: http://www.vnpy.org
Author: Xiaoyou Chen
Author-email: vn.py@foxmail.com
License: MIT
Location: /home/tom/.ana/lib/python2.7/site-packages
Requires:
```
说明安装了...
```
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/examples/VnTrader$ ls
CTA_setting.json  CTP_connect_带客户端认证.json  FEMAS_connect.json  OANDA_connect.json  run.py         SEC_connect.json  temp                VnTrader.bat     XSPEED_connect.json
CTP_connect.json  DR_setting.json                IB_connect.json     RM_setting.json     run_simple.py  ST_setting.json   TKPRO_connect.json  VT_setting.json  XTP_connect.json
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/examples/VnTrader$ python run.py
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway,
  File "/home/tom/.ana/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/__init__.py", line 4, in <module>
    from ctpGateway import CtpGateway
  File "/home/tom/.ana/lib/python2.7/site-packages/vnpy/trader/gateway/ctpGateway/ctpGateway.py", line 16, in <module>
    from vnpy.api.ctp import MdApi, TdApi, defineDict
  File "/home/tom/.ana/lib/python2.7/site-packages/vnpy/api/ctp/__init__.py", line 3, in <module>
    from vnctpmd import MdApi
ImportError: No module named vnctpmd
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/examples/VnTrader$ 
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/examples/VnTrader$ pip list | grep vnctpmd
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/examples/VnTrader$ 
```

说明没有安装成功
```
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/examples/VnTrader$ pip install vnctpmd
Collecting vnctpmd
  Could not find a version that satisfies the requirement vnctpmd (from versions: )
No matching distribution found for vnctpmd
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/examples/VnTrader$
```
看来这么安装vnctpmd是没有成功的.

---

安装过程中的一些可怀疑点

```
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3$ bash ./install.sh
.......省略
Scanning dependencies of target vnib
make[2]: Leaving directory '/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/build'
make -f CMakeFiles/vnib.dir/build.make CMakeFiles/vnib.dir/build
make[2]: Entering directory '/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/build'
[ 50%] Building CXX object CMakeFiles/vnib.dir/vnib/vnib/vnib.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dvnib_EXPORTS -I/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/./ibapi/linux/client -I/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/IB_PATH -I/usr/include/python2.7  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/vnib.dir/vnib/vnib/vnib.cpp.o -c /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/vnib/vnib/vnib.cpp
In file included from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/./ibapi/linux/client/EClientSocket.h:8:0,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/vnib/vnib/vnib.h:25,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/vnib/vnib/vnib.cpp:5:
/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/./ibapi/linux/client/EClient.h:350:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ETransport> m_transport;
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/include/boost/function/function_base.hpp:16,
                 from /usr/include/boost/function/detail/prologue.hpp:17,
                 from /usr/include/boost/function/function_template.hpp:13,
                 from /usr/include/boost/function/detail/maybe_include.hpp:13,
                 from /usr/include/boost/function/function0.hpp:11,
                 from /usr/include/boost/python/errors.hpp:13,
                 from /usr/include/boost/python/handle.hpp:11,
                 from /usr/include/boost/python/to_python_value.hpp:12,
                 from /usr/include/boost/python/default_call_policies.hpp:10,
                 from /usr/include/boost/python/make_function.hpp:10,
                 from /usr/include/boost/python/def.hpp:11,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/vnib/vnib/vnib.h:10,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/vnib/vnib/vnib.cpp:5:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
[100%] Linking CXX shared library lib/vnib.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/vnib.dir/link.txt --verbose=1
/usr/bin/c++  -fPIC  -fPIC -std=c++11 -O3 -DNDEBUG  -shared -Wl,-soname,vnib.so -o lib/vnib.so CMakeFiles/vnib.dir/vnib/vnib/vnib.cpp.o ../ibapi/linux/build/lib/twsapi.so -lboost_python -lboost_thread -lboost_date_time -lboost_system -lboost_chrono -lboost_atomic -lpthread /home/tom/.ana/lib/libpython2.7.so -Wl,-rpath,/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/build/lib:/home/tom/.ana/lib
make[2]: Leaving directory '/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/build'
[100%] Built target vnib
make[1]: Leaving directory '/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/build'
/usr/bin/cmake -E cmake_progress_start /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/build/CMakeFiles 0
~/vnpy/vnpy-1.7.3/vnpy/api/ib
~/vnpy/vnpy-1.7.3
Requirement already satisfied: pymongo in /home/tom/.ana/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied:
```

过了一会儿

```
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/EClientSocket.cpp.o -c /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClientSocket.cpp
In file included from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClientSocket.h:8:0,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClientSocket.cpp:8:
/home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClient.h:350:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ETransport> m_transport;
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClient.h:9,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClientSocket.h:8,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClientSocket.cpp:8:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
[ 13%] Building CXX object CMakeFiles/twsapi.dir/client/EMutex.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/EMutex.cpp.o -c /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EMutex.cpp
[ 18%] Building CXX object CMakeFiles/twsapi.dir/client/OperatorCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/OperatorCondition.cpp.o -c /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/OperatorCondition.cpp
In file included from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/OperatorCondition.cpp:4:0:
/home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClient.h:350:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ETransport> m_transport;
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClient.h:9,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/OperatorCondition.cpp:4:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
[ 22%] Building CXX object CMakeFiles/twsapi.dir/client/PriceCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/PriceCondition.cpp.o -c /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/PriceCondition.cpp
In file included from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/PriceCondition.cpp:5:0:
/home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClient.h:350:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ETransport> m_transport;
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClient.h:9,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/PriceCondition.cpp:5:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
[ 27%] Building CXX object CMakeFiles/twsapi.dir/client/EReader.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/EReader.cpp.o -c /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EReader.cpp
In file included from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClientSocket.h:8:0,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EReader.cpp:10:
/home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClient.h:350:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ETransport> m_transport;
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClient.h:9,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClientSocket.h:8,
                 from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EReader.cpp:10:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
[ 31%] Building CXX object CMakeFiles/twsapi.dir/client/EClient.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/EClient.cpp.o -c /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClient.cpp
In file included from /home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClient.cpp:8:0:
/home/tom/vnpy/vnpy-1.7/vnpy/api/ib/ibapi/linux/client/EClient.h:350:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ETransport> m_transport;
          ^
```

最后输出是下面这样的
```
vnpy.trader.gateway.xspeedGateway.xspeedGateway: module references __file__
vnpy.trader.gateway.xtpGateway.xtpGateway: module references __file__
vnpy.trader.gateway.zbGateway.zbGateway: module references __file__
creating 'dist/vnpy-1.7.2-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing vnpy-1.7.2-py2.7.egg
removing '/home/tom/.ana/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg' (and everything under it)
creating /home/tom/.ana/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg
Extracting vnpy-1.7.2-py2.7.egg to /home/tom/.ana/lib/python2.7/site-packages
  File "/home/tom/.ana/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/trader/gateway/okexGateway/okexGateway.py", line 576
    for symbol in :
                  ^
SyntaxError: invalid syntax

Removing vnpy 1.7.0 from easy-install.pth file
Adding vnpy 1.7.2 to easy-install.pth file

Installed /home/tom/.ana/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg
Processing dependencies for vnpy==1.7.2
Finished processing dependencies for vnpy==1.7.2
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3$
```

那...怎么破呢?

**Comment by vnpy** [comment]
要命了。。。okexGateway里有bug导致安装失败，我的错。。。

这样解决：
1. pip uninstall vnpy
2. 进入下载的vnpy/trader/gateway，把okexGateway整个文件夹给删了
3. 回到vnpy目录再运行build.sh安装

**Comment by tomtsang** [comment]
我依然, 没有成功, 能否把 第2,3步, 写详细一点...谢谢...

**Comment by vnpy** [comment]
不好意思说错了，3就是运行install.sh

**Comment by tomtsang** [comment]
好的...第2步中的删除, 也应该是.tar.gz 压缩包中文件, 而不是 site-packages/ 下的 文件夹, 对吗?

然后, 按上面的思路, 重新安装, 依然是有很多的报错哟
```
Scanning dependencies of target twsapi
make[2]: Leaving directory '/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/build'
make -f CMakeFiles/twsapi.dir/build.make CMakeFiles/twsapi.dir/build
make[2]: Entering directory '/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/build'
[  4%] Building CXX object CMakeFiles/twsapi.dir/client/StdAfx.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/StdAfx.cpp.o -c /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/StdAfx.cpp
[  9%] Building CXX object CMakeFiles/twsapi.dir/client/EClientSocket.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/EClientSocket.cpp.o -c /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClientSocket.cpp
In file included from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClientSocket.h:8:0,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClientSocket.cpp:8:
/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClient.h:350:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ETransport> m_transport;
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClient.h:9,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClientSocket.h:8,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClientSocket.cpp:8:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
[ 13%] Building CXX object CMakeFiles/twsapi.dir/client/EMutex.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/EMutex.cpp.o -c /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EMutex.cpp
[ 18%] Building CXX object CMakeFiles/twsapi.dir/client/OperatorCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/OperatorCondition.cpp.o -c /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/OperatorCondition.cpp
In file included from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/OperatorCondition.cpp:4:0:
/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClient.h:350:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ETransport> m_transport;
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClient.h:9,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/OperatorCondition.cpp:4:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
[ 22%] Building CXX object CMakeFiles/twsapi.dir/client/PriceCondition.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/PriceCondition.cpp.o -c /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/PriceCondition.cpp
In file included from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/PriceCondition.cpp:5:0:
/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClient.h:350:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ETransport> m_transport;
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClient.h:9,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/PriceCondition.cpp:5:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
[ 27%] Building CXX object CMakeFiles/twsapi.dir/client/EReader.cpp.o
/usr/bin/c++   -DBUILD_IB -DUSE_64BITS -Dtwsapi_EXPORTS -I/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/IB_PATH  -fPIC -std=c++11 -O3 -DNDEBUG -fPIC   -o CMakeFiles/twsapi.dir/client/EReader.cpp.o -c /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EReader.cpp
In file included from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClientSocket.h:8:0,
                 from /home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EReader.cpp:10:
/home/tom/vnpy/vnpy-1.7.3/vnpy/api/ib/ibapi/linux/client/EClient.h:350:10: warning: ‘templ
```
这些, 看起来感觉 , 也是错误...

**Comment by tomtsang** [comment]
另附一问: 第2步中的删除, 也应该是`v1.7.3.tar.gz` 压缩包, 解压后 `vnpy-1.7.3` 中文件, 而不是 包路径 `/home/tom/.ana/lib/python2.7/site-packages/` 下的 文件夹, 对吗? 
我的操作如下:
```
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3$ cd vnpy/trader/gateway/ # okexGateway
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/vnpy/trader/gateway$ ls
coincheckGateway  ctpGateway    futuGateway  __init__.py    ksgoldGateway  lbankGateway  oandaGateway  secGateway   shzdGateway   windGateway    xtpGateway
cshshlpGateway    femasGateway  ibGateway    korbitGateway  ksotpGateway   ltsGateway    qdpGateway    sgitGateway  tkproGateway  xspeedGateway  zbGateway
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/vnpy/trader/gateway$ rm -rf okexGateway
tom@udvbud-vnpy-py2-a:~/vnpy/vnpy-1.7.3/vnpy/trader/gateway$
```

**Comment by vnpy** [comment]
1. 对的，删除解压后文件夹中的东西，而不是site-packages下的
2. XTP编译那段的输出是正确的，输出内容是提示有语法警告，不是错误

**Comment by Bin13** [comment]
请问你的这个问题解决了么，我重新安装1.7.3 也报了和你同样的问题。具体如下：
Traceback (most recent call last):
  File "examples/VnTrader/run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway,
  File "/home/jing/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/trader/gateway/xtpGateway/__init__.py", line 4, in <module>
    from xtpGateway import XtpGateway
  File "/home/jing/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/trader/gateway/xtpGateway/xtpGateway.py", line 11, in <module>
    from vnpy.api.xtp import *
  File "/home/jing/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/api/xtp/__init__.py", line 3, in <module>
    from vnxtpquote import QuoteApi
ImportError: No module named vnxtpquote

@vnpy 这个问题是什么原因导致，我是按照你上面说的，删除了okexGateway 这个文件夹搞定的。最后还是不行。请帮忙解答下。

**Comment by BillyZhangGuoping** [comment]
@Bin13 
删除 xtpGateway from line 19 of run.py, 这个接口只是为了 Linux system； 后面有if system = ‘’

**Comment by Bin13** [comment]
@BillyZhangGuoping   我是在linux system下面用的，我用的是ubuntu 16.04.

**Comment by Bin13** [comment]
Extracting vnpy-1.7.2-py2.7.egg to /home/jing/anaconda2/lib/python2.7/site-packages
  File "/home/jing/anaconda2/lib/python2.7/site-packages/vnpy-1.7.2-py2.7.egg/vnpy/trader/gateway/okexGateway/okexGateway.py", line 576
    for symbol in :
                  ^
SyntaxError: invalid syntax

Adding vnpy 1.7.2 to easy-install.pth file     
出现这个问题是说代码里面有格式错误么？会是这个导致无法安装成功么。

**Comment by tomtsang** [comment]
@BillyZhangGuoping 您说的这个`xtpGateway from line 19 of run.py` , 未生效...

**Comment by tomtsang** [comment]
@Bin13 如果您和我一样, 在v1.7.3下, @vnpy 没有修复完成的情况下, 没有安装成功的话, 可以尝试使用 v1.7 , 这个版本我测试了, 到目前为止安装有效! (后续使用是否会有问题, 未知)

**Comment by vnpy** [comment]
已经确定是部分接口的问题，v1.8.0会将这些尚未经过官方测试的接口转到一个单独的目录中，避免影响主环境的安装

**Comment by nehcuh** [comment]
在1.8中，出现了同样问题，有人解决了么？
