### ISSUE TITLE
ServerClient模式不能正常退出

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#750]
## 环境

* 操作系统: WINDOWS/CENTOS7.0
* Anaconda版本: Anaconda 4.2.0
* vn.py版本: 1.8

## Issue类型
三选一：Bug

## 预期程序行为
Client 点退出时正常退出。并且下次可以重新打开。

## 实际程序行为
1，无法正常退出
2，下次无法打开，需要将 server.py 重启，才能再次打开 client.py

## 重现步骤

新版本跑一下就重现。

---------------------------------------------------------------------------------------
报错如下：
D:\WorkSpace\APPS\vnpy-master\examples\ServerClient>python client.py
Traceback (most recent call last):
  File "C:\Users\ShellMount\Anaconda2\lib\site-packages\vnpy\trader\uiMainWindow.py", line 251, in closeEvent
    self.mainEngine.exit()
  File "C:\Users\ShellMount\Anaconda2\lib\site-packages\vnpy\trader\app\rpcService\rsClient.py", line 41, in __call__
    return self.client.call(d)
  File "C:\Users\ShellMount\Anaconda2\lib\site-packages\vnpy\rpc\vnrpc.py", line 241, in dorpc
    raise RemoteException(rep[1])
vnpy.rpc.vnrpc.RemoteException: Traceback (most recent call last):
  File "/var/local/VNPY/vnpy/rpc/vnrpc.py", line 168, in run
    r = func(*args, **kwargs)
  File "/var/local/VNPY/vnpy/trader/app/rpcService/rsEngine.py", line 80, in call
    result = obj(*args, **kwargs)
  File "/var/local/VNPY/vnpy/trader/vtEngine.py", line 180, in exit
    appEngine.stop()
  File "/var/local/VNPY/vnpy/trader/app/rpcService/rsEngine.py", line 91, in stop
    self.server.stop()
  File "/var/local/VNPY/vnpy/rpc/vnrpc.py", line 146, in stop
    self.__thread.join()
  File "/usr/local/anaconda2/lib/python2.7/threading.py", line 931, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

D:\WorkSpace\APPS\vnpy-master\examples\ServerClient>python client.py

**Comment by wanghc02** [comment]
遇到同样问题，试了一下，把关闭主窗口时的mainEnginge.exit()注释掉，好像就OK了

**Comment by vnpy** [comment]
已修复
