### ISSUE TITLE
安装完成后运行run.py报错，1.7版本和1.8版本都是

### ISSUE THREAD

**Issue by JohnHush** [vnpy/vnpy#756]
## 环境

* 操作系统: Ubuntu 16.04
* vn.py版本: v1.7 && v1.8

## Issue类型
三选一：Question

## 重现步骤
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway, ibGateway, 
  File "/home/future_test/anaconda2/lib/python2.7/site-packages/vnpy-1.7.0-py2.7.egg/vnpy/trader/gateway/oandaGateway/__init__.py", line 4, in <module>
    from oandaGateway import OandaGateway
  File "/home/future_test/anaconda2/lib/python2.7/site-packages/vnpy-1.7.0-py2.7.egg/vnpy/trader/gateway/oandaGateway/oandaGateway.py", line 27, in <module>
    from vnpy.api.oanda import OandaApi
  File "/home/future_test/anaconda2/lib/python2.7/site-packages/vnpy-1.7.0-py2.7.egg/vnpy/api/oanda/__init__.py", line 3, in <module>
    from vnoanda import OandaApi
  File "/home/future_test/anaconda2/lib/python2.7/site-packages/vnpy-1.7.0-py2.7.egg/vnpy/api/oanda/vnoanda.py", line 4, in <module>
    import requests
  File "/home/future_test/anaconda2/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/future_test/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/home/future_test/anaconda2/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/future_test/anaconda2/lib/python2.7/site-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "/home/future_test/anaconda2/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "/home/future_test/anaconda2/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
zlib.error: Error -2 while decompressing data: inconsistent stream state

**Comment by vnpy** [comment]
出错的是这个库：cryptography
然后错误信息为：zlib.error: Error -2 while decompressing data: inconsistent stream state

vn.py中导致这段出错的代码是你加载了OANDA的接口，如果不用的话从run.py中移除就好
如果一定要用就得自己查找错误信息的原因了，建议可以直接弄个新的Ubuntu 16.04重装Anaconda 4.0.0

**Comment by JohnHush** [comment]
好的，多谢了！！
