### ISSUE TITLE
ctaStrategy模块无法加载当前目录下子目录的策略文件

### ISSUE THREAD

**Issue by yesheng1984** [vnpy/vnpy#762]
## 环境

* 操作系统: Windows10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.73

## Issue类型
三选一：Bug

## 预期程序行为
在当前工作目录中，策略文件放置在当前工作目录中的子目录。
## 实际程序行为
app\ctaStratgy\strategy\__init__.py的loadStrategyModule会报错，无法动态加载子目录中的策略模块。

## 重现步骤
1.  当前目录结构：project\strategy\strategyAtrRsi.py
2.  运行project根目录下的run.py
3. 会无法加载strategyAtrRsi.py

个人解决方案是，请指正：
workingPath = os.getcwd()
for root, subdirs, files in os.walk(workingPath,False):
    for name in files:
        # 只有文件名中包含strategy且非.pyc的文件，才是策略文件
        if 'strategy' in name and '.pyc' not in name:
            # 模块名称无需前缀
            moduleName = name.replace('.py', '')
            import sys
            sys.path.append(root)
            loadStrategyModule(moduleName)

**Comment by vnpy** [comment]
设计上就不支持工作目录下子目录中的策略文件加载。

修改方法：
1. strategy目录中添加__init__.py
2. moduleName = 'strategy.' + moduleName

请试试看吧

**Comment by justinchou** [comment]
我在 MacOS下引入 `vnpy.trader.app.ctaStrategy` 报错提示：
```
--------------------
Failed to import strategy file strategyAtrRsi:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyAtrRsi
--------------------
Failed to import strategy file strategyBollChannel:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyBollChannel
--------------------
Failed to import strategy file strategyDoubleMa:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/anaconda3/envs/Python27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategyDoubleMa
--------------------
Failed to import strategy file strategyMultiTimeframe:
Traceback (most recent call last):
  File "/anaconda3/envs/Python27/lib/python2.7/site-packages/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 20, in loadStrategyModule
    module = importlib.import_module(moduleName)
........
```
