### ISSUE TITLE
ImportError: twsapi.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by swiftzhen** [vnpy/vnpy#766]
第一次安装VNPY，运行时碰到下面错误，我搜索了一下没看到相关内容，哪位大神帮我指点一下：

hzhen@ubuntu:~/vnpy-1.8/examples/VnTrader$ python run.py
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from vnpy.trader.gateway import (ctpGateway, oandaGateway, 
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/gateway/ibGateway/__init__.py", line 4, in <module>
    from ibGateway import IbGateway
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/gateway/ibGateway/ibGateway.py", line 20, in <module>
    from vnpy.api.ib import *
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/api/ib/__init__.py", line 3, in <module>
    from vnib import *
ImportError: twsapi.so: cannot open shared object file: No such file or directory

## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32
* vn.py版本: v1.8

## Issue类型
三选一：Question

## 预期程序行为
希望看到启动界面

## 实际程序行为
显示如上错误信息

## 重现步骤
N/A

**Comment by vnpy** [comment]
进入vnpy/api/ib目录下，运行build.sh，然后再回到vnpy目录运行install.bat安装

**Comment by swiftzhen** [comment]
Build.sh时碰到以下输出

/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
virtual memory exhausted: Cannot allocate memory
CMakeFiles/vnib.dir/build.make:62: recipe for target 'CMakeFiles/vnib.dir/vnib/vnib/vnib.cpp.o' failed
make[2]: *** [CMakeFiles/vnib.dir/vnib/vnib/vnib.cpp.o] Error 1
make[2]: Leaving directory '/home/hzhen/vnpy-1.8/vnpy/api/ib/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/vnib.dir/all' failed
make[1]: *** [CMakeFiles/vnib.dir/all] Error 2
make[1]: Leaving directory '/home/hzhen/vnpy-1.8/vnpy/api/ib/build'
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
hzhen@ubuntu:~/vnpy-1.8/vnpy/api/ib$ 

在运行pyrhon sun.py碰到开始的同样问题，是否我的安装方法有问题？

**Comment by swiftzhen** [comment]
我给虚拟机增加了内存，上面的build.sh的错误消失了，我重新尝试了安装，发现以下错误信息:

hzhen@ubuntu:~/vnpy-1.8/examples/VnTrader$ python run.py
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyMultiTimeframe:
Traceback (most recent call last):
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/home/hzhen/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/strategyMultiTimeframe.py", line 9, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (CtaTemplate,
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyKingKeltner:
Traceback (most recent call last):
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/home/hzhen/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/strategyKingKeltner.py", line 14, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (CtaTemplate,
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyBollChannel:
Traceback (most recent call last):
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/home/hzhen/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/strategyBollChannel.py", line 23, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (CtaTemplate,
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyAtrRsi:
Traceback (most recent call last):
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/home/hzhen/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/strategyAtrRsi.py", line 14, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (CtaTemplate,
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyDoubleMa:
Traceback (most recent call last):
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/home/hzhen/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/strategyDoubleMa.py", line 10, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (CtaTemplate,
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyDualThrust:
Traceback (most recent call last):
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/home/hzhen/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/strategyDualThrust.py", line 11, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import CtaTemplate, BarGenerator
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyMultiSignal:
Traceback (most recent call last):
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "/home/hzhen/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/strategy/strategyMultiSignal.py", line 12, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (TargetPosTemplate,
  File "/home/hzhen/anaconda2/lib/python2.7/site-packages/vnpy-1.8.0-py2.7.egg/vnpy/trader/app/ctaStrategy/ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
Traceback (most recent call last):
  File "run.py", line 70, in <module>
    main()
  File "run.py", line 54, in main
    me.addGateway(xtpGateway)
NameError: global name 'xtpGateway' is not defined

**Comment by swiftzhen** [comment]
从头重新安装，所以关掉此问题。
