### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by chenge191** [vnpy/vnpy#788]
## 环境

* 操作系统: 如mac
* Anaconda版本: 如anaconda3 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：安装报错

## 预期程序行为
成功启动

## 实际程序行为
python run.py
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from vnpy.event import EventEngine
  File "/anaconda3/envs/python27/lib/python2.7/site-packages/vnpy/event/__init__.py", line 3, in <module>
    from .eventEngine import EventEngine, EventEngine2, Event, EVENT_TIMER
  File "/anaconda3/envs/python27/lib/python2.7/site-packages/vnpy/event/eventEngine.py", line 4, in <module>
    from queue import Queue, Empty
ImportError: No module named queue

**Comment by vnpy** [comment]
pip install future
