### ISSUE TITLE
关于策略模板的使用 比如CTA的布林通道测BollChannelStrategy(CtaTemplate):

### ISSUE THREAD

**Issue by GGZNZ** [vnpy/vnpy#799]
## 环境

* 操作系统: 如Windows 2012R2
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8

## Issue类型
三选一：Bug/Enhancement/Question

## 预期程序行为
计划把原有CTA策略，BollChanneltrategy(CtaTemplate)修改成自己的 BollChannelHuigeStrategy(CtaTemplate):
并且按自己的需求，增加一些参数和变量等。

比如在变量列表里：增加了一个“zzzoutput”
varList = ['inited',
               'trading',
               'pos',
               'bollUp',
               'bollDown',
               'cciValue',
               'atrValue',
               'intraTradeHigh',
               'intraTradeLow',
               'longStop',
               'shortStop',
               'zzzoutput']  

并且把CTA_setting修改，只保留加载修改后的BollChannelHuigeStrategy

## 实际程序行为
使用web界面，点击加载策略：报错
策略HUIGE'BULIN触发异常已停止 Traceback (most recent call last): File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 576, in callStrategyFunc func() File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\strategyBollChannel-huige .py", line 110, in onInit self.putEvent() File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 185, in putEvent self.ctaEngine.putStrategyEvent(self.name) File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 557, in putStrategyEvent d = {k:strategy.__getattribute__(k) for k in strategy.varList} File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaEngine.py", line 557, in <dictcomp> d = {k:strategy.__getattribute__(k) for k in strategy.varList} AttributeError: 'BollChannelHuigeStrategy' object has no attribute 'zzzoutput'

截图不知道怎么弄进来，^_^
![Uploading aaaa.jpg…]()

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by GGZNZ** [comment]
找到问题了。
