### ISSUE TITLE
runOptimization运行到resultList时报错ZeroDivisionError，不显示优化结果

### ISSUE THREAD

**Issue by unlimitnight0** [vnpy/vnpy#817]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.2 Python 2.7 32位
* vn.py版本: v1.7.2

## Issue类型：Bug

##错误描述：
跑优化，优化第一组参数时，会报警：
vnpy-1.7.2-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaBacktesting.py:975: RuntimeWarning: invalid value encountered in log
  df['return'] = (np.log(df['balance']) - np.log(df['balance'].shift(1))).fillna(0)

优化结束后未出resultList，报错：
Traceback (most recent call last):
  File "C:/wu/vnpy-1.7.2/examples/CtaBacktesting/runOptimization.py", line 56, in <module>
    engine.runParallelOptimization(CamarillaStrategy, setting)
  File "C:\wu\Anaconda2\lib\site-packages\vnpy-1.7.2-py2.7.egg\vnpy\trader\app\ctaStrategy\ctaBacktesting.py", line 919, in runParallelOptimization
    resultList = [res.get() for res in l]
  File "C:\wu\Anaconda2\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
ZeroDivisionError: float division by zero

**Comment by vnpy** [comment]
ZeroDivisionError: float division by zero    这个报错是说有除法运算的分母是0，请检查代码看看吧

**Comment by vnpy** [comment]
ZeroDivisionError: float division by zero    这个报错是说有除法运算的分母是0，请检查代码看看吧
