### ISSUE TITLE
初次安装运行run.py时出现错误

### ISSUE THREAD

**Issue by unicorn910121** [vnpy/vnpy#830]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8

## Issue类型
三选一：Bug

## 预期程序行为
运行run.py时出现错误

## 重现步骤
runfile('D:/Anaconda2/Lib/site-packages/vnpy/trader/run.py', wdir='D:/Anaconda2/Lib/site-packages/vnpy/trader')
Traceback (most recent call last):

  File "<ipython-input-5-955f0e2ce047>", line 1, in <module>
    runfile('D:/Anaconda2/Lib/site-packages/vnpy/trader/run.py', wdir='D:/Anaconda2/Lib/site-packages/vnpy/trader')

  File "D:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/Anaconda2/Lib/site-packages/vnpy/trader/run.py", line 11, in <module>
    from vnpy.trader.uiQt import qApp

ImportError: cannot import name qApp

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by vnpy** [comment]
qApp这个对象已经废弃，请使用新版本的examples目录

**Comment by silent494529371** [comment]
windows下面按照标准流程来测试还是会出现这个错误

**Comment by silent494529371** [comment]
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    from vnpy.trader.uiQt import createQApp
ImportError: cannot import name createQApp
