### ISSUE TITLE
1.8vnpy天勤终端数据解决方案代码执行问题

### ISSUE THREAD

**Issue by chris-ccc** [vnpy/vnpy#873]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8
## Issue类型
Question

## 预期程序行为
文档：天勤终端数据解决方案

## 实际程序行为
在“vnpy-1.7.1\examples\TqDataService “运行downloadData.py
C:\dev\vnpy-1.8\vnpy-1.8\examples\TqDataService>python downloadData.py
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyAtrRsi:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "C:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\strategyAtrRsi.py", line 14, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (CtaTemplate,
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyBollChannel:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "C:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\strategyBollChannel.py", line 23, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (CtaTemplate,
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyDoubleMa:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "C:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\strategyDoubleMa.py", line 10, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (CtaTemplate,
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyDualThrust:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "C:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\strategyDualThrust.py", line 11, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import CtaTemplate, BarGenerator
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyKingKeltner:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "C:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\strategyKingKeltner.py", line 14, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (CtaTemplate,
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyMultiSignal:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "C:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\strategyMultiSignal.py", line 12, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (TargetPosTemplate,
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------
Failed to import strategy file vnpy.trader.app.ctaStrategy.strategy.strategyMultiTimeframe:
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "C:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\strategyMultiTimeframe.py", line 9, in <module>
    from vnpy.trader.app.ctaStrategy.ctaTemplate import (CtaTemplate,
  File "C:\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\ctaTemplate.py", line 8, in <module>
    import talib
ImportError: No module named talib
--------------------------------------------------
开始下载合约分钟线数据
--------------------------------------------------

**Comment by cooooo** [comment]
install talib first

**Comment by chris-ccc** [comment]
感谢楼上，装了ta-lib后好了
不过请问 天勤这个只要开着历史数据 就可以了吗？

https://github.com/vnpy/vnpy/wiki/%E5%A4%A9%E5%8B%A4%E7%BB%88%E7%AB%AF%E6%95%B0%E6%8D%AE%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88
“手动下载数据

配置文件填好后用python IDE打开同目录下的“downloadData.py”文件 ，如下图所示（建议用PyCharm编辑）。在黄线处填入需要下载的分钟K线个数，一般第一次下载历史行情数据尽可能追溯更多的分钟K线数据，便于历史回测。天勤数据历史行情可回溯到2016年1月，执行文件即开始下载。”
-------------------------------------------------------------------------------------------------

  文档说明里写的有点不明白，下载的是多少分钟的K线？

**Comment by vnpy** [comment]
默认的是1分钟K线
