### ISSUE TITLE
WebTrader运行异常

### ISSUE THREAD

**Issue by ShellMount** [vnpy/vnpy#881]
## 环境

* 操作系统: 如Windows 7/LINUX7.5
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 如v1.8 beta 

## Issue类型
三选一：Bug/Enhancement/Question
BUG

## 预期程序行为
正常运行

## 实际程序行为
报错如下。

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

[root@iZ11zciwg8gZ WebTrader]# python run.py 
/var/local/VNPY/vnpy-dev-20180520/examples/WebTrader/webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  from flask.ext.restful import Api, Resource, reqparse
/var/local/VNPY/vnpy-dev-20180520/examples/WebTrader/webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful.reqparse is deprecated, use flask_restful.reqparse instead.
  from flask.ext.restful import Api, Resource, reqparse
/var/local/VNPY/vnpy-dev-20180520/examples/WebTrader/webServer.py:57: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  from flask.ext.socketio import SocketIO
2018-05-21 10:38:16,893  INFO: ------------------------------
2018-05-21 10:38:16,893  INFO: 当前时间：2018-05-21 10:38:16.893672
2018-05-21 10:38:16,894  INFO: 当前处于交易时间段
2018-05-21 10:38:16,897  INFO: 启动交易服务器进程
2018-05-21 10:38:16,900  INFO: 启动WEB服务器进程
2018-05-21 10:38:16,904  INFO: 服务器进程启动
2018-05-21 10:38:16,906  INFO: 事件引擎创建成功
2018-05-21 10:38:16,932  INFO: 主引擎创建成功
2018-05-21 10:38:16,932  INFO: 服务器启动成功
2018-05-21 10:38:17,036  INFO:  * Restarting with stat
/var/local/VNPY/vnpy-dev-20180520/examples/WebTrader/webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  from flask.ext.restful import Api, Resource, reqparse
/var/local/VNPY/vnpy-dev-20180520/examples/WebTrader/webServer.py:56: ExtDeprecationWarning: Importing flask.ext.restful.reqparse is deprecated, use flask_restful.reqparse instead.
  from flask.ext.restful import Api, Resource, reqparse
/var/local/VNPY/vnpy-dev-20180520/examples/WebTrader/webServer.py:57: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  from flask.ext.socketio import SocketIO
2018-05-21 10:38:17,793  INFO: ------------------------------
2018-05-21 10:38:17,793  INFO: 当前时间：2018-05-21 10:38:17.793530
2018-05-21 10:38:17,793  INFO: 当前处于交易时间段
2018-05-21 10:38:17,797  INFO: 启动交易服务器进程
2018-05-21 10:38:17,799  INFO: 启动WEB服务器进程
2018-05-21 10:38:17,805  INFO: 服务器进程启动
2018-05-21 10:38:17,805  INFO: 事件引擎创建成功
2018-05-21 10:38:17,807  WARNING:  * Debugger is active!
2018-05-21 10:38:17,808  INFO:  * Debugger PIN: 190-081-709
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/var/local/VNPY/vnpy-dev-20180520/examples/WebTrader/tradingServer.py", line 59, in main
    me.addApp(rpcService)
  File "/var/local/VNPY/current/vnpy/trader/vtEngine.py", line 86, in addApp
    self.appDict[appName] = appModule.appEngine(self, self.eventEngine)
  File "/var/local/VNPY/current/vnpy/trader/app/rpcService/rsEngine.py", line 32, in __init__
    self.loadSetting()
  File "/var/local/VNPY/current/vnpy/trader/app/rpcService/rsEngine.py", line 44, in loadSetting
    self.server = RpcServer(self.repAddress, self.pubAddress)
  File "/var/local/VNPY/current/vnpy/rpc/vnrpc.py", line 119, in __init__
    self.__socketREP.bind(repAddress)
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
ZMQError: Address already in use

------------------------
此外：这个时间范围好像也有问题。永远不是交易时间。?
if currentTime >= START_TIME and currentTime <= CLOSE_TIME:

**Comment by vnpy** [comment]
确实是bug，已经修复！

**Comment by ShellMount** [comment]
以上 Restarting with stat 引起的
ZMQError: Address already in use

还没有解决？

**Comment by asxzy** [comment]
该问题还存在，启动flask服务的时候关闭debug模式，问题解决

examples/WebTrader/WebServer.py:675
```debug=False```
即可


另
examples/WebTrader/WebServer.py:53,54
应为
```from flask_restful import Api, Resource, reqparse
from flask_socketio import SocketIO```


ref:
https://www.cnblogs.com/shengulong/p/8207179.html
