### ISSUE TITLE
ImportError: No module named queue

### ISSUE THREAD

**Issue by qiumy001** [vnpy/vnpy#890]
## 环境

* 操作系统: Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v 1.8.1

## Issue类型
三选一：Question

PS D:\VNPY研究\vnpy-1.8.1\examples\VnTrader> python run.py
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    from vnpy.event import EventEngine
  File "C:\Python27\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\event\__init__.py", line 3, in <module>
    from .eventEngine import EventEngine, EventEngine2, Event, EVENT_TIMER
  File "C:\Python27\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\event\eventEngine.py", line 4, in <module>
    from queue import Queue, Empty
ImportError: No module named queue

完全按照建议步骤安装，请教大侠如何解决？

**Comment by qiumy001** [comment]
已经安装 future，snappy，但还是没解决问题
PS C:\WINDOWS\system32> pip install future
Requirement already satisfied: future in c:\programdata\anaconda2\lib\site-packages
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\WINDOWS\system32> pip install snappy
Requirement already satisfied: snappy in c:\programdata\anaconda2\lib\site-packages
Requirement already satisfied: pyreadline>=2.0 in c:\programdata\anaconda2\lib\site-packages (from snappy)
Requirement already satisfied: FXrays>=1.3 in c:\programdata\anaconda2\lib\site-packages (from snappy)
Requirement already satisfied: decorator in c:\programdata\anaconda2\lib\site-packages (from snappy)
Requirement already satisfied: ipython>=0.13 in c:\programdata\anaconda2\lib\site-packages (from snappy)
Requirement already satisfied: future in c:\programdata\anaconda2\lib\site-packages (from snappy)
Requirement already satisfied: cypari>=2.2 in c:\programdata\anaconda2\lib\site-packages (from snappy)
Requirement already satisfied: spherogram>=1.8 in c:\programdata\anaconda2\lib\site-packages (from snappy)
Requirement already satisfied: plink>=2.2 in c:\programdata\anaconda2\lib\site-packages (from snappy)
Requirement already satisfied: snappy-manifolds>=1.0 in c:\programdata\anaconda2\lib\site-packages (from snappy)
Requirement already satisfied: pypng in c:\programdata\anaconda2\lib\site-packages (from snappy)
Requirement already satisfied: setuptools>=18.5 in c:\programdata\anaconda2\lib\site-packages (from ipython>=0.13->snappy)
Requirement already satisfied: pickleshare in c:\programdata\anaconda2\lib\site-packages (from ipython>=0.13->snappy)
Requirement already satisfied: simplegeneric>0.8 in c:\programdata\anaconda2\lib\site-packages (from ipython>=0.13->snappy)
Requirement already satisfied: traitlets>=4.2 in c:\programdata\anaconda2\lib\site-packages (from ipython>=0.13->snappy)
Requirement already satisfied: prompt_toolkit<2.0.0,>=1.0.4 in c:\programdata\anaconda2\lib\site-packages (from ipython>=0.13->snappy)
Requirement already satisfied: pygments in c:\programdata\anaconda2\lib\site-packages (from ipython>=0.13->snappy)
Requirement already satisfied: backports.shutil_get_terminal_size in c:\programdata\anaconda2\lib\site-packages (from ipython>=0.13->snappy)
Requirement already satisfied: pathlib2 in c:\programdata\anaconda2\lib\site-packages (from ipython>=0.13->snappy)
Requirement already satisfied: colorama in c:\programdata\anaconda2\lib\site-packages (from ipython>=0.13->snappy)
Requirement already satisfied: win_unicode_console>=0.5 in c:\programdata\anaconda2\lib\site-packages (from ipython>=0.13->snappy)
Requirement already satisfied: six in c:\users\qiumy\appdata\roaming\python\python27\site-packages (from cypari>=2.2->snappy)
Requirement already satisfied: networkx>=1.3 in c:\programdata\anaconda2\lib\site-packages (from spherogram>=1.8->snappy)
Requirement already satisfied: ipython_genutils in c:\programdata\anaconda2\lib\site-packages (from traitlets>=4.2->ipython>=0.13->snappy)
Requirement already satisfied: enum34 in c:\programdata\anaconda2\lib\site-packages (from traitlets>=4.2->ipython>=0.13->snappy)
Requirement already satisfied: wcwidth in c:\programdata\anaconda2\lib\site-packages (from prompt_toolkit<2.0.0,>=1.0.4->ipython>=0.13->snappy)
Requirement already satisfied: scandir in c:\programdata\anaconda2\lib\site-packages (from pathlib2->ipython>=0.13->snappy)
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
