### ISSUE TITLE
tushare下载历史数据失败

### ISSUE THREAD

**Issue by silent494529371** [vnpy/vnpy#891]
## 环境

* 操作系统: 如Windows 7 
* vn.py版本: 最新mater更新版

## Issue类型
三选一：Question

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

1 进入目录\vnpy-1.8\examples\TushareDataService(数据库打开运行)
2 执行命令python downloadData.py

运行结果

--------------------------------------------------
开始下载合约分钟线数据
--------------------------------------------------
Traceback (most recent call last):
  File "downloadData.py", line 11, in <module>
    downloadAllMinuteBar()
  File "C:\edisk\quat\git\vnpy-1.8\examples\TushareDataService\dataService.py", line 87, in downloadAllMinuteBar
    downMinuteBarBySymbol(str(symbol))
  File "C:\edisk\quat\git\vnpy-1.8\examples\TushareDataService\dataService.py", line 63, in downMinuteBarBySymbol
    df = ts.bar(symbol, ktype='1min')
TypeError: bar() got an unexpected keyword argument 'ktype'

**Comment by vnpy** [comment]
已修复，请更新到最新版本
