### ISSUE TITLE
tushare下载历史数据失败 （issue 891 reopen)

### ISSUE THREAD

**Issue by silent494529371** [vnpy/vnpy#911]
## 环境

操作系统: 如Windows 7
vn.py版本: 最新mater更新版

## Issue类型
三选一：Bug

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

1 进入目录\vnpy-1.8\examples\TushareDataService(数据库打开运行)
2 执行命令python downloadData.py

运行结果
\Anaconda2\lib\pdb.py", line 1233, in _runscript
    self.run(statement)
  File "C:\Users\xxxx\Anaconda2\lib\bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "downloadData.py", line 11, in <module>
    downloadAllMinuteBar()
  File "dataService.py", line 88, in downloadAllMinuteBar
    downMinuteBarBySymbol(str(symbol))
  File "dataService.py", line 64, in downMinuteBarBySymbol
    df = ts.bar(symbol, freq='1min')
AttributeError: 'NoneType' object has no attribute 'sort_index'

**Comment by silent494529371** [comment]
在最新的dev版本上测试的结果

**Comment by silent494529371** [comment]
more comments on this issue when i run under the ubuntu with the latest dev branch. the failure as follows. report the "No module named vnpy.trader.vtObject"

./work/git/dev/dev/examples/TushareDataService/dataService.py", line 11, in <module>
    from vnpy.trader.vtObject import VtBarData
ImportError: No module named vnpy.trader.vtObject

**Comment by silent494529371** [comment]
sorry,  "No module named vnpy.trader.vtObject" go away after the steps as per
https://github.com/vnpy/vnpy/wiki/Ubuntu%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85.
'NoneType' object has no attribute 'sort_index' still exists.

**Comment by BillyZhangGuoping** [comment]
df = ts.bar(symbol, freq='1min')返回的是一个dataframe，很明显返回是空的，然后df = df.sort_index()默认排序失败。检查一个是symbol是否正确，还有是否争取连接了tushare。建议用QuantosDataService，更方便点。

**Comment by silent494529371** [comment]
@BillyZhangGuoping sorry, my ubuntu system can't input chinese, i tried with your path. it has this kind of error:
the command i run.(conda 4.5, ubuntu 14.04)
 python downloadData.py 

errors output.
Traceback (most recent call last):
  File "downloadData.py", line 10, in <module>
    from vnpy.trader.gateway.tkproGateway.DataApi import DataApi
  File "/home/yujs-2/anaconda2/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/trader/gateway/tkproGateway/__init__.py", line 4, in <module>
    from .tkproGateway import TkproGateway
  File "/home/yujs-2/anaconda2/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/trader/gateway/tkproGateway/tkproGateway.py", line 19, in <module>
    from .DataApi import DataApi
  File "/home/yujs-2/anaconda2/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/trader/gateway/tkproGateway/DataApi/__init__.py", line 10, in <module>
    from .data_api import DataApi
  File "/home/yujs-2/anaconda2/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/trader/gateway/tkproGateway/DataApi/data_api.py", line 13, in <module>
    from . import utils
  File "/home/yujs-2/anaconda2/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/trader/gateway/tkproGateway/DataApi/utils.py", line 9, in <module>
    import pandas    as pd
  File "/home/xxxx/anaconda2/lib/python2.7/site-packages/pandas/__init__.py", line 13, in <module>
    __import__(dependency)
  File "/home/xxx/anaconda2/lib/python2.7/site-packages/pytz/__init__.py", line 29, in <module>
    from pkg_resources import resource_stream
zlib.error: Error -2 while decompressing data: inconsistent stream state

any comments for these kind of error?

**Comment by BillyZhangGuoping** [comment]
pandas版本更新下，
