### ISSUE TITLE
v1.8 master运行回测文件错误

### ISSUE THREAD

**Issue by silent494529371** [vnpy/vnpy#912]
## 环境

* 操作系统: 如Windows 7
* Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8

## Issue类型
三选一：Enhancement

## 实际程序行为
Failed to import strategy file strategy_setting.json:
Traceback (most recent call last):
  File "C:\Users\xxxx\Anaconda2\lib\site-packages\vnpy\trader\app\ctaStrategy\strategy\__init__.py", line 18, in loadStrategyModule
    module = importlib.import_module(moduleName)
  File "C:\Users\xxxx\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named strategy_setting.json

## 重现步骤
最新版本直接命令行运行，
python .\CtaBacktesting\runBacktesting.py

**Comment by vnpy** [comment]
1. 请升级到最新版
2. 请去CtaBacktesting目录下运行
