### ISSUE TITLE
bug: v1.8.1 WebTrader docker demo has the ZMQError: Address already in use

### ISSUE THREAD

**Issue by yinchuandong** [vnpy/vnpy#953]
## 环境

* 操作系统: docker Ubuntu 16.04
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v1.8.1 master branch 20180630（下载日期）

## Issue类型
Bug

## 预期程序行为
I attempt to run the webtrader via Dockerfile in ``` /vnpy/docker/web ```, however, the container cannot be successfully created. The Dockerfile and readme.md provided in your examples are incorrect and out-of-date.

## 实际程序行为
Therefore, I writted my own Dockerfile as follows:
```
# Ubuntu 16.04 for running vn.py WebTrader

# modified by @yinchuandong 2018-06-30
#FROM continuumio/anaconda
FROM ubuntu:16.04

MAINTAINER vn.py project <vn.py@foxmail.com>

RUN echo "Use bash"
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN echo "Install software"
RUN apt-get update
RUN apt-get install -y gcc g++ cmake libboost-all-dev
RUN apt-get install -y git bzip2 vim nano
RUN apt-get install -y libgl1-mesa-glx libglib2.0 libsm6 libxrender1
RUN apt-get install -y wget qt5-default ttf-wqy-microhei
RUN apt install net-tools


RUN echo "Install pyenv....."
ENV PYENV_ROOT /root/.pyenv
ENV PATH /root/.pyenv/shims:/root/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN apt-get install -y git python-pip make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl
RUN curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
RUN pyenv install anaconda2-4.0.0
RUN pyenv global anaconda2-4.0.0


RUN echo "Install vn.py"
RUN git clone https://github.com/vnpy/vnpy.git
WORKDIR /vnpy
RUN conda install -y -c quantopian ta-lib
RUN echo $(pwd)
RUN pip install -r requirements.txt
RUN bash install.sh

RUN echo "Set Entry Point"
WORKDIR /vnpy/examples/WebTrader

RUN echo "Go to /vnpy/examples/WebTrader to start the server"
```

With my new Dockerfile, the container can be successfully created. It turns out that my Dockerfile works well. Then I went to ``` /vnpy/vnpy/examples/WebTrader```, the command ```python  webServer.py ``` can be successfully executed, but some errors occurred when executing ``` python run.py ```. I noticed that there are two processes ```webServer.py``` and ```tradingServer.py``` in ```run.py```.  I assume that the error was caused by ```run.py```. I also found you fixed this bug in [issue 881](https://github.com/vnpy/vnpy/issues/881), but unfortunately, it still exists. I hope you can address this issue. By the way, can you replace the existing web Dockerfile with my new Dockerfile? 

```
Process Process-1:
Traceback (most recent call last):
  File "/root/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/root/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/vnpy/examples/WebTrader/tradingServer.py", line 56, in main
    me.addApp(rpcService)
  File "/root/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/trader/vtEngine.py", line 86, in addApp
    self.appDict[appName] = appModule.appEngine(self, self.eventEngine)
  File "/root/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/trader/app/rpcService/rsEngine.py", line 32, in __init__
    self.loadSetting()
  File "/root/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/trader/app/rpcService/rsEngine.py", line 44, in loadSetting
 self.server = RpcServer(self.repAddress, self.pubAddress)
  File "/root/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/rpc/vnrpc.py", line 119, in __init__
    self.__socketREP.bind(repAddress)
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
    raise ZMQError(errno)
ZMQError: Address already in use

```

## 重现步骤

1. replace the original Dockerfile in ```/vnpy/docker/web```
2. go to the folder ```/vnpy/docker/web``` 
3. execute ```./build.sh```
4. execute ```./run.sh``` (you can enter the docker container)
5. go to the folder ```/vnpy/examples/WebTrader``` in the docker container
6. execute ```python run.py``` and you can reproduce the error.

**Comment by vnpy** [comment]
已修复
