### ISSUE TITLE
安装时报错 EOFError: EOF read where object expected

### ISSUE THREAD

**Issue by yhylord** [vnpy/vnpy#969]
## 环境

* 操作系统: Arch Linux
* Anaconda版本: Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: v.1.8.1

## Issue类型
三选一：Question

## 预期程序行为
`bash install.sh` 能成功安装

## 实际程序行为
安装时报错`EOFError: EOF read where object expected`，完整报错如下：
```
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    'tq': ["tornado>=4.5.1", "sortedcontainers>=1.5.7"],
  File "/home/yhylord/anaconda2/envs/vnpy/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/yhylord/anaconda2/envs/vnpy/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/yhylord/anaconda2/envs/vnpy/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/yhylord/anaconda2/envs/vnpy/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/yhylord/anaconda2/envs/vnpy/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/yhylord/anaconda2/envs/vnpy/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/yhylord/anaconda2/envs/vnpy/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/yhylord/anaconda2/envs/vnpy/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 217, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/yhylord/anaconda2/envs/vnpy/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 253, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/yhylord/anaconda2/envs/vnpy/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 363, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/yhylord/anaconda2/envs/vnpy/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 400, in scan_module
    code = marshal.load(f)
EOFError: EOF read where object expected
```

## 重现步骤
安装 Anaconda 与 PyQt4 等依赖后，运行`bash install.sh`，在 C++ 依赖编译成功后出现

**Comment by vnpy** [comment]
我来检查下，这个可能是天勤接口的问题

**Comment by vnpy** [comment]
检查后Windows和Ubuntu均无此问题，可能由于Arch Linux系统缘故，关闭Issue
