### ISSUE TITLE
运行VnTrader时，报错：No module named vnxtpquote

### ISSUE THREAD

**Issue by projoy** [vnpy/vnpy#970]
## 环境

* 操作系统: Ubuntu 16.04
* Anaconda版本: 如Anaconda 2 Python 2.7 64位
* vn.py版本: 如v1.8.1发行版

## Issue类型
三选一：Question

## 实际程序行为
运行：/export/quant/vnpy-1.8.1/examples/VnTrader$ python run.py时，报错

   from vnxtpquote import QuoteApi
ImportError: No module named vnxtpquote

帮忙看一下什么原因，谢谢
## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

` hadoop@pbdata:/export/quant/vnpy-1.8.1/examples/VnTrader$ python run.py
Traceback (most recent call last):
  File "run.py", line 27, in <module>
    from vnpy.trader.gateway import xtpGateway
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/trader/gateway/xtpGateway/__init__.py", line 4, in <module>
    from xtpGateway import XtpGateway
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/trader/gateway/xtpGateway/xtpGateway.py", line 11, in <module>
    from vnpy.api.xtp import *
  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/vnpy-1.8.1-py2.7.egg/vnpy/api/xtp/__init__.py", line 3, in <module>
    from vnxtpquote import QuoteApi
ImportError: No module named vnxtpquote

`

**Comment by projoy** [comment]
已解决
解决方法如下：
将vnpy-1.8.1/vnpy/api/xtp/CMakeLists.txt中：
`find_library(XTPAPI_MD_LIBRARY
  NAMES libxtpquoteapiD.so
  PATHS ${XTPAPI_PATH}) 
find_library(XTPAPI_TD_LIBRARY
  NAMES libxtptraderapiD.so
  PATHS ${XTPAPI_PATH})
`
修改成：
`find_library(XTPAPI_MD_LIBRARY
  NAMES libxtpquoteapi.so
  PATHS ${XTPAPI_PATH}) 
find_library(XTPAPI_TD_LIBRARY
  NAMES libxtptraderapi.so
  PATHS ${XTPAPI_PATH})
`
然后重新编译，即可

原因：[https://github.com/vnpy/vnpy/issues/916](url)

**Comment by vnpy** [comment]
已修复
