### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by leishuangjian** [vnpy/vnpy#981]
## 环境

* 操作系统: 如Windows 10
* Anaconda版本: 如Anaconda 4.0.0 Python 2.7 32位
* vn.py版本: 1.8.1

## Issue类型
三选一：Question

当安装完环境后运行实例出错。

(D:\software\Anaconda2) D:\software\vnpy\vnpy-1.8.1\examples\VnTrader>VnTrader.bat

(D:\software\Anaconda2) D:\software\vnpy\vnpy-1.8.1\examples\VnTrader>python run.py
D:\software\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\api\ib\__init__.py:3: RuntimeWarning: to-Python converter for class std::vector<class ibapi::shared_ptr<class OrderCondition>,class std::allocator<class ibapi::shared_ptr<class OrderCondition> > > already registered; second conversion method ignored.
  from vnib import *
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    from vnpy.trader.gateway import (femasGateway, xspeedGateway,
  File "D:\software\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\trader\gateway\futuGateway\__init__.py", line 4, in <module>
    from futuGateway import FutuGateway
  File "D:\software\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\trader\gateway\futuGateway\futuGateway.py", line 14, in <module>
    import futuquant as ft
  File "D:\software\Anaconda2\lib\site-packages\futuquant\__init__.py", line 18, in <module>
    from futuquant.quote.open_quote_context import OpenQuoteContext
  File "D:\software\Anaconda2\lib\site-packages\futuquant\quote\open_quote_context.py", line 11, in <module>
    from futuquant.common.open_context_base import OpenContextBase, ContextStatus
  File "D:\software\Anaconda2\lib\site-packages\futuquant\common\open_context_base.py", line 330
    def on_activate(self, conn_id, now: datetime):
                                      ^
SyntaxError: invalid syntax

(D:\software\Anaconda2) D:\software\vnpy\vnpy-1.8.1\examples\VnTrader>

由于是一个新手，对这个问题不是很明白，麻烦帮忙解决一下，非常感谢！！

## 重现步骤

针对Bug类型Issue，请提供具体重现步骤以及报错截图

**Comment by luyi1979** [comment]
将 run.py 文件中 futuGateway 相关的部分都注释掉就可以运行了
