### ISSUE TITLE
ccxt连接okex出错TypeError

### ISSUE THREAD

**Issue by xldistance** [vnpy/vnpy#995]
## 环境

* 操作系统: Windows 10
* Anaconda版本: Anaconda 5.2.0 Python 2.7 32位
* vn.py版本: 如v1.8.1

## Issue类型
三选一：Bug

## 预期程序行为
2018-07-25 15:11:07,380  INFO: CCXT 发生异常，错误代码：api，错误信息：Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\trader\gateway\ccxtGateway\ccxtGateway.py", line 208, in processReq
    callback(data, reqID)
  File "C:\ProgramData\Anaconda2\lib\site-packages\vnpy-1.8.1-py2.7.egg\vnpy\trader\gateway\ccxtGateway\ccxtGateway.py", line 513, in onQryDepth
    tick.datetime = datetime.fromtimestamp(data['timestamp']/1000)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by xldistance** [comment]
币圈的tick.datetime搞死人啊，vnpy对接的接口不少也有tick问题

**Comment by vnpy** [comment]
已修复，对timestamp字段做了检查，如果为空则使用本地时间
